# Strategy 3. Template-based query (2)

Template-based. Create a Query Template that has several different Cypher queries embedded as training cases for the LLM (along with the schema) and then use that as the basis for the query a user adds.

Three options are evaluated:
- 3a - only examples of correct queries are provided
- 3b - examples of correct queries and "normal" graph schema is provided
- 3c - examples of correct queries and "enhanced" graph schema is provided

In [3]:
import os
from dotenv import load_dotenv
from tqdm import tqdm
import json
import pandas as pd

# Load environment variables from the .env file
load_dotenv()

# Retrieve the variables from the environment
neo4j_uri = os.getenv("NEO4J_URI")
neo4j_username = os.getenv("NEO4J_USERNAME")
neo4j_password = os.getenv("NEO4J_PASSWORD")

# Check if any variable is missing
if not all([neo4j_uri, neo4j_username, neo4j_password]):
    raise EnvironmentError("One or more environment variables are missing: NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD")

print(f"Accessing OpenTargets at {neo4j_uri} as user {neo4j_username}")

Accessing OpenTargets at bolt+s://pistoia.neo4j.rbsapp.net:7687 as user neo4j

Wrappers for LLMs and KG

In [4]:
# Langchain wrappers for different models

import re
from langchain_openai import ChatOpenAI
from langchain_mistralai import ChatMistralAI
from langchain_anthropic import ChatAnthropic

chat_models = {}

def new_ChatModel(model):
    if re.search(r"^gpt", model):
        return ChatOpenAI(model = model)
    elif re.search(r"^o1", model):
        return ChatOpenAI(model = model, temperature = 1)
    elif re.search(r"^claude", model):
        return ChatAnthropic(model = model)
    elif re.search(r"mistral", model):
        return ChatMistralAI(model = model)
    else:
        raise ValueError(f"Unsupported model: {model}")

def ChatModel(model):
    if model in chat_models:
        return chat_models[model]
    else:
        chat_models[model] = new_ChatModel(model)
        return chat_models[model]

# models:
#   claude-3-5-sonnet-20240620
#   gpt-4o
#   o1-preview-2024-09-12
#   open-mistral-7b

# llm = ChatModel("gpt-4o")

In [18]:
# Cypher data extraction

def extract_cypher(message):
    text = message
    pattern = r"```cypher(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    try:
        return [match.strip() for match in matches]
    except Exception:
        raise ValueError(f"Failed to parse: {message}")

from py2neo import Graph

graph = Graph(
    neo4j_uri,
    auth=(neo4j_username, neo4j_password)
)

In [5]:
# Some queries take a very long time to run. This will deal with timeout

import threading

class TimeoutThread(threading.Thread):
    def __init__(self, func, *args, **kwargs):
        threading.Thread.__init__(self)
        self.func = func
        self.args = args
        self.kwargs = kwargs
        self.result = None
        self.error = None

    def run(self):
        try:
            self.result = self.func(*self.args, **self.kwargs)
        except Exception as e:
            self.error = e

def run_with_timeout(func, timeout, *args, **kwargs):
    thread = TimeoutThread(func, *args, **kwargs)
    thread.start()
    thread.join(timeout)

    if thread.is_alive():
        raise TimeoutError("Function execution timed out")
    elif thread.error:
        raise thread.error
    return thread.result

In [19]:
# convenience functions for data retrieval from graph

import time

def query_cypher_graph(graph, query):
    return graph.query(query)

def query_graph(llm_output):
    try:
        cypher_query = extract_cypher(llm_output)
    except Exception as e:
        return [{
            "query":None,
            "success":False,
            "exception":str(e)
        }]

    cypher_results = []
    for query in cypher_query:
        try:
            start = time.time()
            result = run_with_timeout(query_cypher_graph, 20, graph, query)
            duration = time.time() - start
            cypher_results.append({
                "query":query,
                "success":True,
                "result": list(result),
                "time": duration
                })
        except Exception as e:
            cypher_results.append({
                "query":query,
                "success":False,
                "exception":str(e)
            })
    return cypher_results


def process_results(todo, llm_answers, cypher_results):
    results = []
    for t,llm,res in zip(todo, llm_answers, cypher_results):
        out = {
            "model" : t[0],
            "question" : t[1],
            "llm_answer" : llm,
            "cypher_output": res,
            "n_cypher_queries" : len(res)
        }
        if len(res) > 0:
            out.update({
                "query": res[0].get('query',''),
                "success": res[0]['success']
            })
            if res[0]['success']:
                out.update({
                    "results": res[0]['result'],
                    "time": res[0]['time'],
                    "count" : len(res[0]['result'])
                })
            else:
                out.update({
                    "error": res[0]['exception']
                })
        results.append(out)
    return results

## Questions

In [8]:
questions = [
    "What (or how strong, or is there any) is the evidence between TDP-43 and amyotrophic lateral sclerosis (ALS)",
    "What is the evidence linking TDP-43 to cancer in animal models?",
    "What (or is there) is the clinical evidence linking BRAF to Melanoma?"
]

## Running template-based query

We'll give few examples of correct cypher queries. All queries will be related to the actual query we want LLM to make. 

- 3a will be prompt that only uses queries
- 3b will be also using graph schema

In [26]:
# Graph schema

from langchain_community.graphs import Neo4jGraph

graph = Neo4jGraph(url=neo4j_uri, username=neo4j_username, password=neo4j_password)
graph.refresh_schema()

normal_schema = graph.schema

enhanced_graph = Neo4jGraph(
    url=neo4j_uri,
    username=neo4j_username,
    password=neo4j_password,
    enhanced_schema=True,
)

enhanced_schema = enhanced_graph.schema

print(enhanced_schema)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"

Node properties:
- **Entity**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **ThingWithTaxon**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **DiseaseOrPhenotypicFeature**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `modelPhenotypeLabel`: STRING
- **Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
- **Obi.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OBI_1110122', 'http://purl.obolibrary.org/obo/OBI_0001621', 'http://purl.obolibrary.org/obo/OBI_0001620', 'http://purl.obolibrary.org/obo/OBI_1110021']
  - `name`: STRING Available options: ['pathological process', 'longitude', 'latitude', 'infect']
  - `description`: STRING Available options: ['Abnormal, harmful processes caused by or associate', 'A measurement that is the measure of the longitude', 'A measurement that is the measure of the latitude ', 'The detrimental process in which an infectious age']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['obi:1110122', 'obi:0001621', 'obi:0001620', 'obi:1110021']
  - `preferred_id`: STRING Available options: ['obi']
- **BiologicalEntity**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **NamedThing**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **Ncit.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/NCIT_C74532', 'http://purl.obolibrary.org/obo/NCIT_C117245', 'http://purl.obolibrary.org/obo/NCIT_C95746']
  - `name`: STRING Available options: ['nervousness', 'decreased attention', 'sleepiness']
  - `description`: STRING Available options: ['An uneasy psychological state; the anxious feeling', 'Impaired ability to focus on a subject or idea.', 'The sensation of struggling to remain awake.']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ncit:C74532', 'ncit:C117245', 'ncit:C95746']
  - `preferred_id`: STRING Available options: ['ncit']
- **Mondo.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/MONDO_0000385"
  - `name`: STRING Example: "benign digestive system neoplasm"
  - `description`: STRING Example: "A non-metastasizing neoplasm arising from any part"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "mondo:0000385"
  - `preferred_id`: STRING Available options: ['mondo']
- **Association**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **Literature.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **AnimalModel.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 11
  - `score`: FLOAT Example: "0.4947"
  - `source`: STRING Example: "impc"
  - `licence`: STRING Example: "NA"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "1ed93ef5539f388a1423ba9b98a7b71f610d2a10"
  - `preferred_id`: STRING Example: "id"
- **Hp.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/HP_0002751"
  - `name`: STRING Example: "Kyphoscoliosis"
  - `description`: STRING Example: "An abnormal curvature of the spine in both a coron"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "hp:0002751"
  - `preferred_id`: STRING Available options: ['hp']
- **RnaExpression.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.04389890211572866"
  - `source`: STRING Example: "expression_atlas"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00019f5ecfc23eeddacf2a7c1a2a51a55620e7ff"
  - `preferred_id`: STRING Example: "id"
  - `literature`: LIST Min Size: 1, Max Size: 1
- **Oba.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBA_2001015"
  - `name`: STRING Example: "age of onset of childhood onset asthma"
  - `description`: STRING Example: "The age at which childhood onset asthma manifestat"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "oba:2001015"
  - `preferred_id`: STRING Available options: ['oba']
- **Gene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **MouseGene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
- **KnownDrug.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.1"
  - `source`: STRING Example: "chembl"
  - `licence`: STRING Example: "CC BY-SA 3.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "99af831915f347fcb03e76c2f5ea7e2315bf77ce"
  - `preferred_id`: STRING Example: "id"
- **Doid.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/DOID_13406', 'http://purl.obolibrary.org/obo/DOID_0050890', 'http://purl.obolibrary.org/obo/DOID_10718', 'http://purl.obolibrary.org/obo/DOID_1947', 'http://purl.obolibrary.org/obo/DOID_7551', 'http://purl.obolibrary.org/obo/DOID_10113']
  - `name`: STRING Available options: ['pulmonary sarcoidosis', 'synucleinopathy', 'giardiasis', 'trichomoniasis', 'gonorrhea', 'trypanosomiasis']
  - `description`: STRING Available options: ['Sarcoidosis affecting the lung parenchyma. It is c', 'A neurodegenerative disease that is characterized ', 'A parasitic protozoa infectious disease that invol', 'A parasitic protozoa infectious disease that is ca', 'A primary bacterial infectious disease that is a s']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['doid:13406', 'doid:0050890', 'doid:10718', 'doid:1947', 'doid:7551', 'doid:10113']
  - `preferred_id`: STRING Available options: ['doid']
- **Efo.Disease**
  - `code`: STRING Example: "http://www.ebi.ac.uk/efo/EFO_0800502"
  - `name`: STRING Example: "linoleoyl-docosahexaenoyl-glycerol (18:2/22:6) [1]"
  - `description`: STRING Example: "Quantification of the amount of linoleoyl-docosahe"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "efo:0800502"
  - `preferred_id`: STRING Example: "efo"
- **PhenotypicFeature**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **MousePhenotype**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **Otar.Disease**
  - `code`: STRING Available options: ['http://www.ebi.ac.uk/efo/OTAR_0000018', 'http://www.ebi.ac.uk/efo/OTAR_0000006', 'http://www.ebi.ac.uk/efo/OTAR_0000014', 'http://www.ebi.ac.uk/efo/OTAR_0000020', 'http://www.ebi.ac.uk/efo/OTAR_0000009', 'http://www.ebi.ac.uk/efo/OTAR_0000003', 'http://www.ebi.ac.uk/efo/OTAR_0000010', 'http://www.ebi.ac.uk/efo/OTAR_0000017', 'http://www.ebi.ac.uk/efo/OTAR_0000019']
  - `name`: STRING Available options: ['genetic, familial or congenital disease', 'musculoskeletal or connective tissue disease', 'pregnancy or perinatal disease', 'nutritional or metabolic disease', 'injury, poisoning or other complication', 'cyst', 'respiratory or thoracic disease', 'reproductive system or breast disease', 'familial disease']
  - `description`: STRING Available options: ['A disease caused by genetic modifications inherite', 'A disease involving the musculoskeletal or connect', 'A disease occurring during pregnancy or shortly af', 'Damage inflicted on the body as the direct of indi', 'A sac-like closed membranous structure that may be', 'A disease affecting the respiratory system or othe', 'A disease involving the reproductive system or the', 'A disease occurring in or affecting members of a f']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['otar:0000018', 'otar:0000006', 'otar:0000014', 'otar:0000020', 'otar:0000009', 'otar:0000003', 'otar:0000010', 'otar:0000017', 'otar:0000019']
  - `preferred_id`: STRING Available options: ['otar']
- **HumanGene**
  - `approvedSymbol`: STRING Example: "FEZ2"
  - `biotype`: STRING Example: "protein_coding"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSG00000171055"
  - `preferred_id`: STRING Example: "ensembl"
- **Orphanet.Disease**
  - `code`: STRING Example: "http://www.orpha.net/ORDO/Orphanet_158684"
  - `name`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "orphanet:158684"
  - `preferred_id`: STRING Available options: ['orphanet']
  - `description`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
- **SomaticMutation.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 8
  - `score`: FLOAT Example: "0.25"
  - `source`: STRING Example: "cancer_gene_census"
  - `licence`: STRING Example: "Commercial use for Open Targets"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00bb9bb991a5d157ac87eb0a0a858d3225e91f7e"
  - `preferred_id`: STRING Example: "id"
- **AffectedPathway.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 21
  - `score`: FLOAT Example: "1.0"
  - `source`: STRING Example: "reactome"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "0573156c99191306506c7d365c089e90481066e2"
  - `preferred_id`: STRING Example: "id"
- **GoTerm**
  - `name`: STRING Example: "adenosine 3,5-bisphosphate transmembrane transport"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "go:0071106"
  - `preferred_id`: STRING Example: "go"
- **GeneticAssociation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.35"
  - `source`: STRING Example: "eva"
  - `licence`: STRING Example: "EMBL-EBI terms of use"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "4c75fa3ffc3e72f7b7496fd13377a701dac6e0e7"
  - `preferred_id`: STRING Example: "id"
- **Ogms.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OGMS_0000063']
  - `name`: STRING Available options: ['disease course']
  - `description`: STRING Available options: ['The totality of all processes through which a give']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ogms:0000063']
  - `preferred_id`: STRING Available options: ['ogms']
Relationship properties:

The relationships:
(:Entity)-[:IS_PART_OF]->(:Entity)
(:Entity)-[:IS_PART_OF]->(:Association)
(:Entity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Entity)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Association)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Entity)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Association)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Entity)
(:Disease)-[:IS_PART_OF]->(:Association)
(:Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Obi.Disease)-[:IS_PART_OF]->(:Entity)
(:Obi.Disease)-[:IS_PART_OF]->(:Association)
(:Obi.Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Obi.Disease)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:BiologicalEntity)-[:IS_PART_OF]->(:Entity)
(:BiologicalEntity)-[:IS_PART_OF]->(:Association)

In [52]:
open("normal_schema.txt", "w").write(normal_schema)
open("enhanced_schema.txt", "w").write(enhanced_schema)

25997

In [40]:
from langchain_core.prompts import PromptTemplate

query_example_1 = """\
Task: retreive associations between KRAS and cancer, rna expression only, and evidence score >= 0.1

```cypher
MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<-[:IS_PART_OF]-(disease:Disease)
WHERE gene.approvedSymbol = 'KRAS' 
  AND (LOWER(disease.name) CONTAINS ('cancer') OR LOWER(disease.name) CONTAINS ('carcin') OR LOWER(disease.name) CONTAINS ('neoplas'))
  AND assoc.score IS NOT NULL
  AND (assoc:`RnaExpression.GeneToDiseaseAssociation`)
  AND assoc.score >= 0.1
RETURN 
    gene.approvedSymbol as Gene,
    disease.name as Disease,
    head([label IN labels(assoc) WHERE label CONTAINS '.GeneToDiseaseAssociation']) as EvidenceType,
    assoc.score as Score,
    assoc.literature as Literature
ORDER BY assoc.score DESC
```\
"""

query_example_2 = """\
Task: retreive associations between ALK and non-small cell lung cancer, only known drugs

```cypher
MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<-[:IS_PART_OF]-(disease:Disease)
WHERE gene.approvedSymbol = 'ALK' 
  AND (LOWER(disease.name) CONTAINS ('non-small cell lung'))
  AND assoc.score IS NOT NULL
  AND (assoc:`KnownDrug.GeneToDiseaseAssociation`)
RETURN 
    gene.approvedSymbol as Gene,
    disease.name as Disease,
    head([label IN labels(assoc) WHERE label CONTAINS '.GeneToDiseaseAssociation']) as EvidenceType,
    assoc.score as Score,
    assoc.literature as Literature
ORDER BY assoc.score DESC
```\
"""


query_example_3 = """\
Task: how many evidence of each type there are between KRAS and colorectal cancer?

```cypher
MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<-[:IS_PART_OF]-(disease:Disease)
WHERE gene.approvedSymbol = 'KRAS' 
  AND (LOWER(disease.name) CONTAINS ('colorectal cancer'))
  AND assoc.score IS NOT NULL
RETURN 
    head([label IN labels(assoc) WHERE label CONTAINS '.GeneToDiseaseAssociation']) as EvidenceType,
    COUNT(*) as Count
ORDER BY Count DESC
```\
"""

examples = f"""\
Here are vew examples:
--------------------------------------------
{query_example_1}

{query_example_2}

{query_example_3}
--------------------------------------------
"""



system_prompt_generic = """
You are a biological data scientist with vast experience in building and extracting information from knowledge graph. 

Your current project is to support scientists who want to answer scientific questions about genes, diseases and drugs. You have a Neo4j database with biological data that accepts queries cypher queries. Scientists will provide you questions, and you should output correct cypher statements that will generate results. 

{schema}
{examples}
"""

normal_schema_description = f"""\
This is graph schema:
--------------------------------------------
{normal_schema}
--------------------------------------------    
"""

enhanced_schema_description = f"""\
This is graph schema:
--------------------------------------------
{enhanced_schema}
--------------------------------------------    
"""


system_prompt_no_schema = system_prompt_generic.format(examples = examples, schema = "")
system_prompt_normal_schema = system_prompt_generic.format(examples = examples, schema = normal_schema_description)
system_prompt_enhanced_schema = system_prompt_generic.format(examples = examples, schema = enhanced_schema_description)

template_query = """
{question}
"""

user_template = PromptTemplate.from_template(template_query)

# Option 3a - withouth schema

3 examples but no graph schema

In [22]:
from langchain.schema import AIMessage, HumanMessage, SystemMessage

models = ["gpt-4o", "claude-3-5-sonnet-20240620", "open-mistral-7b", "o1-preview-2024-09-12"]
niter = 10

todo = [(m, q) for q in questions for m in models for _ in range(niter)]


def run_llm_3a(llm_model, question):
    try:
        llm = ChatModel(model = llm_model)
        user_prompt = user_template.invoke({"question": question})

        # o1-preview does not support system messages, so joining them together:
        if llm_model == 'o1-preview-2024-09-12':
            messages = f"{system_prompt_no_schema}\n------------------------------------------\nUser question:\n{user_prompt.text}\n"
            result = llm.invoke(messages)
        else:
            messages = [
                SystemMessage(content=system_prompt_no_schema),
                HumanMessage(content=user_prompt.text)
            ]
            result = llm.invoke(messages)
        return result.content
    except Exception as e:
        print(e)
        return None


llm_answers = []
for llm_model, question in tqdm(todo, desc="Prompting LLM"):
    llm_answers.append(run_llm_3a(llm_model, question))

Prompting LLM: 100%|██████████| 120/120 [14:22<00:00,  7.18s/it]

In [23]:
import time
for i, (llm_model, question) in enumerate(todo):
    if not llm_answers[i]:
        llm_answers[i] = run_llm_3a(llm_model, question)
        time.sleep(2)

In [24]:
cypher_results = []
for answer in tqdm(llm_answers, desc="Querying graph"):
    cypher_results.append(query_graph(answer))

Querying graph: 100%|██████████| 120/120 [00:47<00:00,  2.52it/s]

In [25]:
results = process_results(todo, llm_answers, cypher_results)

results_df = pd.DataFrame(results)
results_df.to_excel("03a-evaluations.xlsx", index=False)
with open("03a-evaluations.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
results_df

,model,question,llm_answer,cypher_output,n_cypher_queries,query,success,results,time,count,error
0,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],2.535390,0.0,NaN
1,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(TARDBP, amyotrophic lateral sclerosis, Genet...",0.511704,1444.0,NaN
2,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(TARDBP, amyotrophic lateral sclerosis, Genet...",0.292627,1439.0,NaN
3,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.201686,0.0,NaN
4,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(TARDBP, amyotrophic lateral sclerosis, Genet...",0.287599,1439.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,Task: Retrieve associations between BRAF and M...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(BRAF, melanoma, KnownDrug.GeneToDiseaseAssoc...",0.218623,376.0,NaN
116,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To retrieve the clinical evidence linking BRAF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(BRAF, melanoma, KnownDrug.GeneToDiseaseAssoc...",0.195994,376.0,NaN
117,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(BRAF, melanoma, KnownDrug.GeneToDiseaseAssoc...",0.189169,376.0,NaN
118,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(BRAF, melanoma, KnownDrug.GeneToDiseaseAssoc...",0.246630,376.0,NaN
119,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[(BRAF, melanoma, KnownDrug.GeneToDiseaseAssoc...",0.244071,376.0,NaN

# Option 3b - with graph schema in the prompt

One correct query and 2 decoy queries + json examples

In [35]:
from langchain.schema import AIMessage, HumanMessage, SystemMessage

models = ["gpt-4o", "claude-3-5-sonnet-20240620", "open-mistral-7b", "o1-preview-2024-09-12"]
niter = 10

todo = [(m, q) for q in questions for m in models for _ in range(niter)]


def run_llm_3b(llm_model, question):
    try:
        llm = ChatModel(model = llm_model)
        user_prompt = user_template.invoke({"question": question})

        # o1-preview does not support system messages, so joining them together:
        if llm_model == 'o1-preview-2024-09-12':
            messages = f"{system_prompt_normal_schema}\n------------------------------------------\nUser question:\n{user_prompt.text}\n"
            result = llm.invoke(messages)
        else:
            messages = [
                SystemMessage(content=system_prompt_normal_schema),
                HumanMessage(content=user_prompt.text)
            ]
            result = llm.invoke(messages)
        return result.content
    except Exception as e:
        print(e)
        return None


llm_answers = []
for llm_model, question in tqdm(todo, desc="Prompting LLM"):
    llm_answers.append(run_llm_3b(llm_model, question))

Prompting LLM:  91%|█████████ | 109/120 [12:47<00:20,  1.86s/it]

Error response 429 while fetching https://api.mistral.ai/v1/chat/completions: {"message":"Requests rate limit exceeded"}

Prompting LLM: 100%|██████████| 120/120 [16:34<00:00,  8.29s/it]

In [36]:
import time
for i, (llm_model, question) in enumerate(todo):
    if not llm_answers[i]:
        llm_answers[i] = run_llm_3b(llm_model, question)
        time.sleep(2)

In [37]:
cypher_results = []
for answer in tqdm(llm_answers, desc="Querying graph"):
    cypher_results.append(query_graph(answer))

Querying graph: 100%|██████████| 120/120 [00:58<00:00,  2.04it/s]

In [38]:
results = process_results(todo, llm_answers, cypher_results)

results_df = pd.DataFrame(results)
results_df.to_excel("03b-evaluations.xlsx", index=False)
with open("03b-evaluations.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
results_df

,model,question,llm_answer,cypher_output,n_cypher_queries,query,success,results,time,count,error
0,gpt-4o,"What (or how strong, or is there any) is the e...",To retrieve the evidence between TDP-43 and am...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.241054,0.0,NaN
1,gpt-4o,"What (or how strong, or is there any) is the e...",To retrieve the evidence between TDP-43 and am...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.228451,0.0,NaN
2,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'TARDBP', 'Disease': 'amyotrophic la...",1.320475,1444.0,NaN
3,gpt-4o,"What (or how strong, or is there any) is the e...",To retrieve the evidence between TDP-43 and am...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.232043,0.0,NaN
4,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.232610,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.343579,304.0,NaN
116,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.292125,376.0,NaN
117,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,Task: Retrieve clinical evidence linking BRAF ...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.343658,376.0,NaN
118,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To determine the clinical evidence linking **B...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.312629,376.0,NaN
119,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",1.323397,5806.0,NaN

# Option 3c - with enhanced graph schema in the prompt

In [41]:
from langchain.schema import AIMessage, HumanMessage, SystemMessage

models = ["gpt-4o", "claude-3-5-sonnet-20240620", "open-mistral-7b", "o1-preview-2024-09-12"]
niter = 10

todo = [(m, q) for q in questions for m in models for _ in range(niter)]


def run_llm_3c(llm_model, question):
    try:
        llm = ChatModel(model = llm_model)
        user_prompt = user_template.invoke({"question": question})

        # o1-preview does not support system messages, so joining them together:
        if llm_model == 'o1-preview-2024-09-12':
            messages = f"{system_prompt_enhanced_schema}\n------------------------------------------\nUser question:\n{user_prompt.text}\n"
            result = llm.invoke(messages)
        else:
            messages = [
                SystemMessage(content=system_prompt_enhanced_schema),
                HumanMessage(content=user_prompt.text)
            ]
            result = llm.invoke(messages)
        return result.content
    except Exception as e:
        print(e)
        return None


llm_answers = []
for llm_model, question in tqdm(todo, desc="Prompting LLM"):
    llm_answers.append(run_llm_3c(llm_model, question))

Prompting LLM:   0%|          | 0/120 [00:00<?, ?it/s]

Prompting LLM:  58%|█████▊    | 70/120 [08:44<01:46,  2.14s/it]

Error response 429 while fetching https://api.mistral.ai/v1/chat/completions: {"message":"Requests rate limit exceeded"}

Prompting LLM: 100%|██████████| 120/120 [17:48<00:00,  8.90s/it]

In [43]:
import time
for i, (llm_model, question) in enumerate(todo):
    if not llm_answers[i]:
        llm_answers[i] = run_llm_3c(llm_model, question)
        time.sleep(2)

In [45]:
cypher_results = []
for answer in tqdm(llm_answers, desc="Querying graph"):
    cypher_results.append(query_graph(answer))

Querying graph:   0%|          | 0/120 [00:00<?, ?it/s]

Querying graph:  54%|█████▍    | 65/120 [00:21<00:11,  4.82it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: label)} {position: line: 2, column: 57, offset: 181} for query: "MATCH (gene:HumanGene {approvedSymbol: 'TDP-43'})-[:IS_PART_OF]->(assoc)<-[:IS_PART_OF]-(disease:DiseaseOrPhenotypicFeature)\nWHERE LOWER(disease.name) CONTAINS ('cancer') AND assoc.label = 'AnimalModel.GeneToDiseaseAssociation'\nRETURN assoc.score as EvidenceScore, assoc.literature as Literature"
Querying graph: 100%|██████████| 120/120 [00:43<00:00,  2.77it/s]

In [46]:
results = process_results(todo, llm_answers, cypher_results)

results_df = pd.DataFrame(results)
results_df.to_excel("03c-evaluations.xlsx", index=False)
with open("03c-evaluations.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
results_df

,model,question,llm_answer,cypher_output,n_cypher_queries,query,success,results,time,count,error
0,gpt-4o,"What (or how strong, or is there any) is the e...",To retrieve the evidence between TDP-43 and am...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.226036,0.0,NaN
1,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.227113,0.0,NaN
2,gpt-4o,"What (or how strong, or is there any) is the e...",```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.233582,0.0,NaN
3,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the evidence strength between TDP...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'TARDBP', 'Disease': 'amyotrophic la...",0.667542,1444.0,NaN
4,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the strength of evidence between ...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,[],0.223254,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To determine the clinical evidence linking **B...,[{'query': 'MATCH (gene:HumanGene)-[:IS_P...,2,MATCH \n (gene:HumanGene)-[:IS_PART_OF]->(a...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.300606,376.0,NaN
116,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,"Yes, there is clinical evidence linking **BRAF...",[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.302574,376.0,NaN
117,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking **BRAF**...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.289571,376.0,NaN
118,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.277590,376.0,NaN
119,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH (gene:HumanGene)-[:IS_PART_OF...,[{'query': 'MATCH (gene:HumanGene)-[:IS_PART_O...,1,MATCH (gene:HumanGene)-[:IS_PART_OF]->(assoc)<...,True,"[{'Gene': 'BRAF', 'Disease': 'melanoma', 'Evid...",0.300577,376.0,NaN