# Using DSPy framework

Training DSPy on true/false biomix questions can lead to overfitting due to the high level of background knowledge (~100%). To distinguish between its biological knowledge and knowledge graph utilization, we will train it to generate correct Cypher statements instead.

To achieve this, we need an extended biomix test set that includes genes, diseases, and the number of relationships between genes and diseases in the knowledge graph. We will then ask the LLM to generate queries that output the correct number of results.

In [16]:
import os
from dotenv import load_dotenv
from tqdm import tqdm
import json
import pandas as pd
import re

# Load environment variables from the .env file
load_dotenv()

# Retrieve the variables from the environment
neo4j_uri = os.getenv("NEO4J_URI")
neo4j_username = os.getenv("NEO4J_USERNAME")
neo4j_password = os.getenv("NEO4J_PASSWORD")

# Check if any variable is missing
if not all([neo4j_uri, neo4j_username, neo4j_password]):
    raise EnvironmentError("One or more environment variables are missing: NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD")

print(f"Accessing OpenTargets at {neo4j_uri} as user {neo4j_username}")

Accessing OpenTargets at bolt+s://pistoia.neo4j.rbsapp.net:7687 as user neo4j

In [3]:
from langchain_community.graphs import Neo4jGraph

enhanced_graph = Neo4jGraph(
    url=neo4j_uri,
    username=neo4j_username,
    password=neo4j_password,
    enhanced_schema=True,
)

enhanced_schema = enhanced_graph.schema

print(enhanced_schema)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"

Node properties:
- **Entity**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **ThingWithTaxon**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **DiseaseOrPhenotypicFeature**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `modelPhenotypeLabel`: STRING
- **Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
- **Obi.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OBI_1110122', 'http://purl.obolibrary.org/obo/OBI_0001621', 'http://purl.obolibrary.org/obo/OBI_0001620', 'http://purl.obolibrary.org/obo/OBI_1110021']
  - `name`: STRING Available options: ['pathological process', 'longitude', 'latitude', 'infect']
  - `description`: STRING Available options: ['Abnormal, harmful processes caused by or associate', 'A measurement that is the measure of the longitude', 'A measurement that is the measure of the latitude ', 'The detrimental process in which an infectious age']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['obi:1110122', 'obi:0001621', 'obi:0001620', 'obi:1110021']
  - `preferred_id`: STRING Available options: ['obi']
- **BiologicalEntity**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **NamedThing**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **Ncit.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/NCIT_C74532', 'http://purl.obolibrary.org/obo/NCIT_C117245', 'http://purl.obolibrary.org/obo/NCIT_C95746']
  - `name`: STRING Available options: ['nervousness', 'decreased attention', 'sleepiness']
  - `description`: STRING Available options: ['An uneasy psychological state; the anxious feeling', 'Impaired ability to focus on a subject or idea.', 'The sensation of struggling to remain awake.']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ncit:C74532', 'ncit:C117245', 'ncit:C95746']
  - `preferred_id`: STRING Available options: ['ncit']
- **Mondo.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/MONDO_0000385"
  - `name`: STRING Example: "benign digestive system neoplasm"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "mondo:0000385"
  - `preferred_id`: STRING Available options: ['mondo']
  - `description`: STRING Example: "A non-metastasizing neoplasm arising from any part"
- **Association**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **Literature.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **AnimalModel.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 11
  - `score`: FLOAT Example: "0.4947"
  - `source`: STRING Example: "impc"
  - `licence`: STRING Example: "NA"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "1ed93ef5539f388a1423ba9b98a7b71f610d2a10"
  - `preferred_id`: STRING Example: "id"
- **Hp.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/HP_0002751"
  - `name`: STRING Example: "Kyphoscoliosis"
  - `description`: STRING Example: "An abnormal curvature of the spine in both a coron"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "hp:0002751"
  - `preferred_id`: STRING Available options: ['hp']
- **RnaExpression.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.04389890211572866"
  - `source`: STRING Example: "expression_atlas"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00019f5ecfc23eeddacf2a7c1a2a51a55620e7ff"
  - `preferred_id`: STRING Example: "id"
- **Oba.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBA_2001015"
  - `name`: STRING Example: "age of onset of childhood onset asthma"
  - `description`: STRING Example: "The age at which childhood onset asthma manifestat"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "oba:2001015"
  - `preferred_id`: STRING Available options: ['oba']
- **Gene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **MouseGene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
- **KnownDrug.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.1"
  - `source`: STRING Example: "chembl"
  - `licence`: STRING Example: "CC BY-SA 3.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "99af831915f347fcb03e76c2f5ea7e2315bf77ce"
  - `preferred_id`: STRING Example: "id"
- **Doid.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/DOID_13406', 'http://purl.obolibrary.org/obo/DOID_0050890', 'http://purl.obolibrary.org/obo/DOID_10718', 'http://purl.obolibrary.org/obo/DOID_1947', 'http://purl.obolibrary.org/obo/DOID_7551', 'http://purl.obolibrary.org/obo/DOID_10113']
  - `name`: STRING Available options: ['pulmonary sarcoidosis', 'synucleinopathy', 'giardiasis', 'trichomoniasis', 'gonorrhea', 'trypanosomiasis']
  - `description`: STRING Available options: ['Sarcoidosis affecting the lung parenchyma. It is c', 'A neurodegenerative disease that is characterized ', 'A parasitic protozoa infectious disease that invol', 'A parasitic protozoa infectious disease that is ca', 'A primary bacterial infectious disease that is a s']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['doid:13406', 'doid:0050890', 'doid:10718', 'doid:1947', 'doid:7551', 'doid:10113']
  - `preferred_id`: STRING Available options: ['doid']
- **Efo.Disease**
  - `code`: STRING Example: "http://www.ebi.ac.uk/efo/EFO_0800502"
  - `name`: STRING Example: "linoleoyl-docosahexaenoyl-glycerol (18:2/22:6) [1]"
  - `description`: STRING Example: "Quantification of the amount of linoleoyl-docosahe"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "efo:0800502"
  - `preferred_id`: STRING Example: "efo"
- **PhenotypicFeature**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **MousePhenotype**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **Otar.Disease**
  - `code`: STRING Available options: ['http://www.ebi.ac.uk/efo/OTAR_0000018', 'http://www.ebi.ac.uk/efo/OTAR_0000006', 'http://www.ebi.ac.uk/efo/OTAR_0000014', 'http://www.ebi.ac.uk/efo/OTAR_0000020', 'http://www.ebi.ac.uk/efo/OTAR_0000009', 'http://www.ebi.ac.uk/efo/OTAR_0000003', 'http://www.ebi.ac.uk/efo/OTAR_0000010', 'http://www.ebi.ac.uk/efo/OTAR_0000017', 'http://www.ebi.ac.uk/efo/OTAR_0000019']
  - `name`: STRING Available options: ['genetic, familial or congenital disease', 'musculoskeletal or connective tissue disease', 'pregnancy or perinatal disease', 'nutritional or metabolic disease', 'injury, poisoning or other complication', 'cyst', 'respiratory or thoracic disease', 'reproductive system or breast disease', 'familial disease']
  - `description`: STRING Available options: ['A disease caused by genetic modifications inherite', 'A disease involving the musculoskeletal or connect', 'A disease occurring during pregnancy or shortly af', 'Damage inflicted on the body as the direct of indi', 'A sac-like closed membranous structure that may be', 'A disease affecting the respiratory system or othe', 'A disease involving the reproductive system or the', 'A disease occurring in or affecting members of a f']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['otar:0000018', 'otar:0000006', 'otar:0000014', 'otar:0000020', 'otar:0000009', 'otar:0000003', 'otar:0000010', 'otar:0000017', 'otar:0000019']
  - `preferred_id`: STRING Available options: ['otar']
- **HumanGene**
  - `approvedSymbol`: STRING Example: "FEZ2"
  - `biotype`: STRING Example: "protein_coding"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSG00000171055"
  - `preferred_id`: STRING Example: "ensembl"
- **Orphanet.Disease**
  - `code`: STRING Example: "http://www.orpha.net/ORDO/Orphanet_158684"
  - `name`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `description`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "orphanet:158684"
  - `preferred_id`: STRING Available options: ['orphanet']
- **SomaticMutation.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 8
  - `score`: FLOAT Example: "0.25"
  - `source`: STRING Example: "cancer_gene_census"
  - `licence`: STRING Example: "Commercial use for Open Targets"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00bb9bb991a5d157ac87eb0a0a858d3225e91f7e"
  - `preferred_id`: STRING Example: "id"
- **AffectedPathway.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "1.0"
  - `source`: STRING Example: "reactome"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "0573156c99191306506c7d365c089e90481066e2"
  - `preferred_id`: STRING Example: "id"
  - `literature`: LIST Min Size: 1, Max Size: 21
- **GoTerm**
  - `name`: STRING Example: "adenosine 3,5-bisphosphate transmembrane transport"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "go:0071106"
  - `preferred_id`: STRING Example: "go"
- **GeneticAssociation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.35"
  - `source`: STRING Example: "eva"
  - `licence`: STRING Example: "EMBL-EBI terms of use"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "4c75fa3ffc3e72f7b7496fd13377a701dac6e0e7"
  - `preferred_id`: STRING Example: "id"
- **Ogms.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OGMS_0000063']
  - `name`: STRING Available options: ['disease course']
  - `description`: STRING Available options: ['The totality of all processes through which a give']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ogms:0000063']
  - `preferred_id`: STRING Available options: ['ogms']
- **_GraphConfig**
  - `_objectPropertyLabel`: STRING Available options: ['Relationship']
  - `_rangeRel`: STRING Available options: ['RANGE']
  - `_classLabel`: STRING Available options: ['Class']
  - `_subClassOfRel`: STRING Available options: ['SCO']
  - `_handleMultival`: INTEGER Min: 0, Max: 0
  - `_dataTypePropertyLabel`: STRING Available options: ['Property']
  - `_subPropertyOfRel`: STRING Available options: ['SPO']
  - `_handleRDFTypes`: INTEGER Min: 0, Max: 0
  - `_classNamePropName`: STRING Available options: ['name']
  - `_handleVocabUris`: INTEGER Min: 0, Max: 0
  - `_applyNeo4jNaming`: BOOLEAN
  - `_relNamePropName`: STRING Available options: ['name']
  - `_domainRel`: STRING Available options: ['DOMAIN']
  - `_keepLangTag`: BOOLEAN
  - `_keepCustomDataTypes`: BOOLEAN
Relationship properties:

The relationships:
(:Entity)-[:IS_PART_OF]->(:Entity)
(:Entity)-[:IS_PART_OF]->(:Association)
(:Entity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Entity)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Association)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Entity)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Association)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Entity)
(:Disease)-[:IS_PART_OF]->(:Association)
(:Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)

In [5]:
# Cypher data extraction

def extract_cypher(message):
    text = message
    pattern = r"```cypher(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    try:
        return [match.strip() for match in matches]
    except Exception:
        raise ValueError(f"Failed to parse: {message}")

from py2neo import Graph

graph = Graph(
    neo4j_uri,
    auth=(neo4j_username, neo4j_password)
)

In [6]:
# Some queries take a very long time to run. This will deal with timeout

import threading

class TimeoutThread(threading.Thread):
    def __init__(self, func, *args, **kwargs):
        threading.Thread.__init__(self)
        self.func = func
        self.args = args
        self.kwargs = kwargs
        self.result = None
        self.error = None

    def run(self):
        try:
            self.result = self.func(*self.args, **self.kwargs)
        except Exception as e:
            self.error = e

def run_with_timeout(func, timeout, *args, **kwargs):
    thread = TimeoutThread(func, *args, **kwargs)
    thread.start()
    thread.join(timeout)

    if thread.is_alive():
        raise TimeoutError("Function execution timed out")
    elif thread.error:
        raise thread.error
    return thread.result

In [66]:
# convenience functions for data retrieval from graph

import time

def query_cypher_graph(graph, query):
    return graph.query(query)

def query_graph(llm_output):
    try:
        start = time.time()
        query = extract_cypher(llm_output)[0]
        result = run_with_timeout(query_cypher_graph, 60, graph, query)
        duration = time.time() - start
        return {
            "query":llm_output,
            "success":True,
            "result": list(result),
            "time": duration
        }
    except Exception as e:
        return {
            "query":llm_output,
            "result": f"Failed to execute query: {str(e)}",
            "success":False,
            "exception":str(e)
        }

In order to use DSPy prompt optimization capabilities we need a good evaluation dataset, so we'll use biomix for test and evaluation.

As a base query we will use an enchanced LLM schema that is provided by the LangChain.

In [8]:
# DSPy setup:

import dspy

llm = dspy.LM("openai/gpt-4o", max_tokens = 2000)
dspy.settings.configure(lm = llm)

d:\AppData\conda_envs\pistoia\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Loading biomix test-set

We need to load an extended version of BioMix test-set. It contains original disease names and gene names

In [28]:
questions_test = pd.read_excel("biomix_true_false_selected_augmented.xlsx")
questions_train = pd.read_excel("biomix_true_false_selected_augmented_2.xlsx")
questions_train['type'] = 'train'
questions_test['type'] = 'test'

questions = pd.concat([questions_train, questions_test])

We'll go over genes & diseases and query graph to retrieve the number of records. Results will be cached to speed things up. We'll do both exact (case-sensitive) and inexact (case-insensitive) queries. LLM result should lie between these two values in order to be considered correct

In [29]:
def run_gene_disease_query(gene, disease, substr=True):
    if substr:
        disease_query = f"LOWER(disease.name) CONTAINS LOWER('{disease}')"
    else:
        disease_query = f"LOWER(disease.name) = LOWER('{disease}')"
    query = f"""
MATCH (gene:HumanGene)-[:IS_PART_OF]-(assoc)-[:IS_PART_OF]-(disease:Disease)
WHERE gene.approvedSymbol = '{gene}'
  AND ({disease_query})
RETURN 
    gene.approvedSymbol as Gene,
    disease.name as Disease,
    head([label IN labels(assoc) WHERE label CONTAINS '.GeneToDiseaseAssociation']) as EvidenceType,
    assoc.score as Score,
    assoc.literature as Literature
ORDER BY assoc.score DESC
"""
    return list(graph.query(query))

In [32]:
# cache directories:

CACHE_DIR_EXACT = ".temp/gene-disease-exact"
CACHE_DIR_INEXACT = ".temp/gene-disease-inexact"

os.makedirs(CACHE_DIR_EXACT, exist_ok=True)
os.makedirs(CACHE_DIR_INEXACT, exist_ok=True)

count_exact = []
count_inexact = []

# iterating over the questions and running the queries, accumulating counts of results

for _, row in tqdm(questions.iterrows(), total=len(questions)):
    disease = row['s']
    gene = row['o']
    
    json_filename = os.path.join(f"{CACHE_DIR_EXACT}/{gene}-{disease}.json")
    if os.path.exists(json_filename):
        with open(json_filename) as f:
            res_exact = json.load(f)
    else:
        res_exact = run_gene_disease_query(gene, disease, substr=False)
        with open(json_filename, 'w') as f:
            json.dump(res_exact, f, indent=4)

    json_filename = os.path.join(f"{CACHE_DIR_INEXACT}/{gene}-{disease}.json")
    if os.path.exists(json_filename):
        with open(json_filename) as f:
            res_inexact = json.load(f)
    else:
        res_inexact = run_gene_disease_query(gene, disease, substr=True)
        with open(json_filename, 'w') as f:
            json.dump(res_inexact, f, indent=4)

    count_exact.append(len(res_exact))
    count_inexact.append(len(res_inexact))

questions['count_min'] = count_exact
questions['count_max'] = count_inexact
questions

100%|██████████| 199/199 [00:00<00:00, 204.71it/s]

,text,s,o,label,qid,rel,dir,s_type,o_type,p,q_type,type,count_min,count_max
0,Loeys-Dietz Syndrome associates Gene TGFBR1,Loeys-Dietz Syndrome,TGFBR1,True,110.0,disease_gene,direct,disease,gene,associated,tf,train,391,391
1,Congenital contractural arachnodactyly associa...,Congenital contractural arachnodactyly,FBN2,True,66.0,disease_gene,direct,disease,gene,associated,tf,train,1491,1491
2,Pseudoachondroplasia associates Gene COMP,Pseudoachondroplasia,COMP,True,290.0,disease_gene,direct,disease,gene,associated,tf,train,219,219
3,Fabry Disease associates Gene GLA,Fabry Disease,GLA,True,259.0,disease_gene,direct,disease,gene,associated,tf,train,1563,1563
4,Loeys-Dietz Syndrome associates Gene TGFBR2,Loeys-Dietz Syndrome,TGFBR2,True,195.0,disease_gene,direct,disease,gene,associated,tf,train,311,314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Polycythemia Vera is associated with Gene RPS6KA3,Polycythemia Vera,RPS6KA3,False,NaN,disease_gene,direct,disease,gene,associated,tf,test,0,0
96,BIETTI CRYSTALLINE CORNEORETINAL DYSTROPHY is ...,BIETTI CRYSTALLINE CORNEORETINAL DYSTROPHY,RUNX2,False,NaN,disease_gene,direct,disease,gene,associated,tf,test,0,0
97,Pierson syndrome is associated with Gene GDF5,Pierson syndrome,GDF5,False,NaN,disease_gene,direct,disease,gene,associated,tf,test,0,0
98,Cystinuria is associated with Gene GHR,Cystinuria,GHR,False,NaN,disease_gene,direct,disease,gene,associated,tf,test,0,0
99,Smith-Lemli-Opitz Syndrome is associated with ...,Smith-Lemli-Opitz Syndrome,TBX5,False,NaN,disease_gene,direct,disease,gene,associated,tf,test,0,0

In [35]:
testset = [dspy.Example(statement=x['text'], answer=(x['count_min'], x['count_min'])).with_inputs("statement") for _, x in questions.iterrows() if x['type'] == 'test']
trainset = [dspy.Example(statement=x['text'], answer=(x['count_min'], x['count_min'])).with_inputs("statement") for _, x in questions.iterrows() if x['type'] == 'train']

[Example({'statement': 'Loeys-Dietz Syndrome associates Gene TGFBR1', 'answer': (391, 391)}) (input_keys={'statement'}),
 Example({'statement': 'Congenital contractural arachnodactyly associates Gene FBN2', 'answer': (1491, 1491)}) (input_keys={'statement'}),
 Example({'statement': 'Pseudoachondroplasia associates Gene COMP', 'answer': (219, 219)}) (input_keys={'statement'}),
 Example({'statement': 'Fabry Disease associates Gene GLA', 'answer': (1563, 1563)}) (input_keys={'statement'}),
 Example({'statement': 'Loeys-Dietz Syndrome associates Gene TGFBR2', 'answer': (311, 311)}) (input_keys={'statement'}),
 Example({'statement': 'DOYNE HONEYCOMB RETINAL DYSTROPHY associates Gene EFEMP1', 'answer': (70, 70)}) (input_keys={'statement'}),
 Example({'statement': 'Multiple Endocrine Neoplasia Type 2b associates Gene RET', 'answer': (398, 398)}) (input_keys={'statement'}),
 Example({'statement': 'Tuberous Sclerosis associates Gene TSC2', 'answer': (8693, 8693)}) (input_keys={'statement'}),
 Example({'statement': 'Mulibrey Nanism is not associated with Gene TRIM37', 'answer': (152, 152)}) (input_keys={'statement'}),
 Example({'statement': 'CAMPOMELIC DYSPLASIA associates Gene SOX9', 'answer': (270, 270)}) (input_keys={'statement'}),
 Example({'statement': 'Nijmegen Breakage Syndrome is not associated with Gene NBN', 'answer': (2338, 2338)}) (input_keys={'statement'}),
 Example({'statement': 'Bernard-Soulier Syndrome associates Gene GP1BA', 'answer': (119, 119)}) (input_keys={'statement'}),
 Example({'statement': 'Carney Complex is not associated with Gene PRKAR1A', 'answer': (74, 74)}) (input_keys={'statement'}),
 Example({'statement': 'Denys-Drash Syndrome is not associated with Gene WT1', 'answer': (1130, 1130)}) (input_keys={'statement'}),
 Example({'statement': 'Gray Platelet Syndrome is not associated with Gene NBEAL2', 'answer': (310, 310)}) (input_keys={'statement'}),
 Example({'statement': 'Borjeson-Forssman-Lehmann syndrome is not associated with Gene PHF6', 'answer': (90, 90)}) (input_keys={'statement'}),
 Example({'statement': 'Pfeiffer Syndrome associates Gene FGFR2', 'answer': (179, 179)}) (input_keys={'statement'}),
 Example({'statement': 'Pseudoxanthoma Elasticum associates Gene ABCC6', 'answer': (958, 958)}) (input_keys={'statement'}),
 Example({'statement': 'Peutz-Jeghers Syndrome associates Gene STK11', 'answer': (1966, 1966)}) (input_keys={'statement'}),
 Example({'statement': 'Sandhoff Disease is not associated with Gene HEXB', 'answer': (504, 504)}) (input_keys={'statement'}),
 Example({'statement': 'Infantile hypophosphatasia associates Gene ALPL', 'answer': (20, 20)}) (input_keys={'statement'}),
 Example({'statement': 'Nail-Patella Syndrome associates Gene LMX1B', 'answer': (370, 370)}) (input_keys={'statement'}),
 Example({'statement': 'Alveolar rhabdomyosarcoma associates Gene PAX3', 'answer': (203, 203)}) (input_keys={'statement'}),
 Example({'statement': 'alpha-Mannosidosis associates Gene MAN2B1', 'answer': (997, 997)}) (input_keys={'statement'}),
 Example({'statement': 'Canavan Disease associates Gene ASPA', 'answer': (376, 376)}) (input_keys={'statement'}),
 Example({'statement': 'Achondroplasia is not associated with Gene FGFR3', 'answer': (299, 299)}) (input_keys={'statement'}),
 Example({'statement': 'L-2-HYDROXYGLUTARIC ACIDURIA associates Gene L2HGDH', 'answer': (164, 164)}) (input_keys={'statement'}),
 Example({'statement': 'Greig cephalopolysyndactyly syndrome associates Gene GLI3', 'answer': (691, 691)}) (input_keys={'statement'}),
 Example({'statement': 'Smith-Magenis syndrome associates Gene RAI1', 'answer': (124, 124)}) (input_keys={'statement'}),
 Example({'statement': 'Rothmund-Thomson syndrome is not associated with Gene RECQL4', 'answer': (147, 147)}) (input_keys={'statement'}),
 Example({'statement': 'Obesity is not associated with Gene PPARG', 'answer': (929, 929)}) (input_keys={'statement'}),
 Example({'statement': 'Angelman Syndrome is not associated with Gene UBE3A', 'answer': (721, 721)}) (input_keys={'statement'}),
 Example({'statement': 'Aspartylglucosaminuria is not associated with Gene AGA', 'answer': (359, 359)}) (input_keys={'statement'}),
 Example({'statement': 'Refsum Disease associates Gene PHYH', 'answer': (112, 112)}) (input_keys={'statement'}),
 Example({'statement': 'Autosomal dominant hypophosphatemic rickets associates Gene FGF23', 'answer': (162, 162)}) (input_keys={'statement'}),
 Example({'statement': 'Choroideremia is not associated with Gene CHM', 'answer': (202, 202)}) (input_keys={'statement'}),
 Example({'statement': 'Li-Fraumeni Syndrome is not associated with Gene TP53', 'answer': (2423, 2423)}) (input_keys={'statement'}),
 Example({'statement': 'Noonan Syndrome associates Gene KRAS', 'answer': (162, 162)}) (input_keys={'statement'}),
 Example({'statement': 'Hereditary hemorrhagic telangiectasia associates Gene ENG', 'answer': (886, 886)}) (input_keys={'statement'}),
 Example({'statement': 'Unverricht-Lundborg Syndrome is not associated with Gene CSTB', 'answer': (91, 91)}) (input_keys={'statement'}),
 Example({'statement': 'KLEEFSTRA SYNDROME 1 is not associated with Gene EHMT1', 'answer': (1104, 1104)}) (input_keys={'statement'}),
 Example({'statement': 'Hartnup Disease is not associated with Gene SLC6A19', 'answer': (125, 125)}) (input_keys={'statement'}),
 Example({'statement': 'Fatal Familial Insomnia is not associated with Gene PRNP', 'answer': (72, 72)}) (input_keys={'statement'}),
 Example({'statement': 'Hyperargininemia is not associated with Gene ARG1', 'answer': (315, 315)}) (input_keys={'statement'}),
 Example({'statement': 'Biotinidase Deficiency is not associated with Gene BTD', 'answer': (453, 453)}) (input_keys={'statement'}),
 Example({'statement': 'Congenital amegakaryocytic thrombocytopenia is not associated with Gene MPL', 'answer': (521, 521)}) (input_keys={'statement'}),
 Example({'statement': 'Paroxysmal Nonkinesigenic Dyskinesia 1 is not associated with Gene PNKD', 'answer': (377, 377)}) (input_keys={'statement'}),
 Example({'statement': 'Saethre-Chotzen Syndrome is not associated with Gene TWIST1', 'answer': (215, 215)}) (input_keys={'statement'}),
 Example({'statement': 'beta-Mannosidosis is not associated with Gene MANBA', 'answer': (274, 274)}) (input_keys={'statement'}),
 Example({'statement': 'Osteosarcoma is not associated with Gene TP53', 'answer': (833, 833)}) (input_keys={'statement'}),
 Example({'statement': 'CAMPOMELIC DYSPLASIA is not associated with Gene RECQL4', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Aspartylglucosaminuria is not associated with Gene FBN2', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Nijmegen Breakage Syndrome is not associated with Gene ENG', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'L-2-HYDROXYGLUTARIC ACIDURIA is not associated with Gene ABCC6', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Peutz-Jeghers Syndrome is not associated with Gene PHF6', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Greig cephalopolysyndactyly syndrome is not associated with Gene PHYH', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Pseudoachondroplasia is not associated with Gene WT1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Gray Platelet Syndrome is not associated with Gene BTD', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'L-2-HYDROXYGLUTARIC ACIDURIA is not associated with Gene FGFR3', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Noonan Syndrome is not associated with Gene EFEMP1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Autosomal dominant hypophosphatemic rickets is not associated with Gene CHM', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Aspartylglucosaminuria is not associated with Gene CSTB', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'L-2-HYDROXYGLUTARIC ACIDURIA is not associated with Gene MANBA', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Greig cephalopolysyndactyly syndrome is not associated with Gene ALPL', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Hyperargininemia is not associated with Gene GLI3', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Saethre-Chotzen Syndrome is not associated with Gene NBN', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Bernard-Soulier Syndrome is not associated with Gene FGFR2', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Refsum Disease is not associated with Gene PAX3', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'KLEEFSTRA SYNDROME 1 is not associated with Gene TGFBR2', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Gray Platelet Syndrome is not associated with Gene HEXB', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Biotinidase Deficiency is not associated with Gene TP53', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Loeys-Dietz Syndrome is not associated with Gene STK11', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Choroideremia is not associated with Gene L2HGDH', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Li-Fraumeni Syndrome is not associated with Gene MAN2B1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Noonan Syndrome is associated with Gene TSC2', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Alveolar rhabdomyosarcoma is associated with Gene TGFBR1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Rothmund-Thomson syndrome is associated with Gene EHMT1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'alpha-Mannosidosis is associated with Gene RET', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Congenital contractural arachnodactyly is associated with Gene TRIM37', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Pfeiffer Syndrome is associated with Gene UBE3A', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Paroxysmal Nonkinesigenic Dyskinesia 1 is associated with Gene ASPA', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Hyperargininemia is associated with Gene LMX1B', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Hereditary hemorrhagic telangiectasia is associated with Gene PPARG', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Pfeiffer Syndrome is associated with Gene GP1BA', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Noonan Syndrome is associated with Gene AGA', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'beta-Mannosidosis is associated with Gene NBEAL2', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Autosomal dominant hypophosphatemic rickets is associated with Gene MPL', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Obesity is associated with Gene PNKD', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'CAMPOMELIC DYSPLASIA is associated with Gene TWIST1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Multiple Endocrine Neoplasia Type 2b is associated with Gene GLA', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Denys-Drash Syndrome is associated with Gene SLC6A19', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Hereditary hemorrhagic telangiectasia is associated with Gene SOX9', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Congenital contractural arachnodactyly is associated with Gene COMP', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Hyperargininemia is associated with Gene FGF23', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Rothmund-Thomson syndrome is associated with Gene ARG1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Canavan Disease is associated with Gene PRKAR1A', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Peutz-Jeghers Syndrome is associated with Gene RAI1', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Bernard-Soulier Syndrome is associated with Gene PRNP', 'answer': (0, 0)}) (input_keys={'statement'}),
 Example({'statement': 'Aspartylglucosaminuria is associated with Gene KRAS', 'answer': (0, 0)}) (input_keys={'statement'})]

## DSPy cypher query strategy

In [69]:
class GenerateCypher(dspy.Signature):
    """Generate cypher statement to check correctness of a statement"""
    statement = dspy.InputField()
    neo4j_schema = dspy.InputField(desc="Schema of a neo4j database")
    cypher = dspy.OutputField(desc="Valid cypher query that can be used to check correctness of the statement")


class GraphQueryCoT(dspy.Module):

    def __init__(self, schema):
        super().__init__()
        self.generate_query  = dspy.ChainOfThought(GenerateCypher)
        self.schema = schema
    
    def forward(self, statement):
        return self.generate_query(statement=statement, neo4j_schema=self.schema)

cot_cypher = GraphQueryCoT(enhanced_schema)

answer = cot_cypher(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    reasoning='To verify the statement "Polycythemia Vera is not associated with Gene JAK2," we need to check if there is any association between the disease "Polycythemia Vera" and the gene "JAK2" in the database. The schema indicates that associations between genes and diseases are represented by the `GeneToDiseaseAssociation` node. We should look for a `GeneToDiseaseAssociation` relationship where the disease is "Polycythemia Vera" and the gene is "JAK2". The `Gene` node has an `approvedSymbol` property which can be used to identify the gene "JAK2". However, the schema does not explicitly list "Polycythemia Vera" as a disease name, so we will assume it is represented in one of the disease nodes. We will use a generic query to check for any such association.',
    cypher='```cypher\nMATCH (d:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[:IS_PART_OF]-(g:Gene)\nWHERE d.name = "Polycythemia Vera" AND g.approvedSymbol = "JAK2"\nRETURN a\n```'
)

In [74]:
def validate_query(example, pred, trace=None):
    res = query_graph(pred.cypher)

    if not res['success']:
        return False
    count = len(res['result'])
    
    if count >= example.answer[0] and count <= example.answer[1]:
        return True
    return False

In [75]:
from dspy.evaluate import Evaluate

fast_evaluate_program = Evaluate(devset = testset[:5], metric=validate_query, display_progress=True, display_table=10, provide_traceback=True)
evaluate_program = Evaluate(devset = testset, metric=validate_query, display_progress=True, display_table=10, provide_traceback=True)

Evaluating CoT before conducting MIPRO optimization

In [76]:
evaluate_program(cot_cypher)

Average Metric: 47.00 / 100 (47.0%): 100%|██████████| 100/100 [10:19<00:00,  6.19s/it]

2024/12/23 15:02:00 INFO dspy.evaluate.evaluate: Average Metric: 47 / 100 (47.0%)

,statement,answer,reasoning,cypher,validate_query
0,Polycythemia Vera is not associated with Gene JAK2,"(518, 518)","To verify the statement ""Polycythemia Vera is not associated with ...",```cypher\nMATCH (d:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(a:...,
1,Cystic Fibrosis associates Gene CFTR,"(7134, 7134)","The statement ""Cystic Fibrosis associates Gene CFTR"" implies a rel...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Cystic Fibr...",
2,Cleidocranial Dysplasia associates Gene RUNX2,"(392, 392)","The statement ""Cleidocranial Dysplasia associates Gene RUNX2"" sugg...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Cleidocrani...",
3,Ellis-Van Creveld Syndrome associates Gene EVC2,"(1150, 1150)","The statement ""Ellis-Van Creveld Syndrome associates Gene EVC2"" su...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Ellis-Van C...",
4,Juvenile polyposis syndrome associates Gene BMPR1A,"(1154, 1154)","The statement ""Juvenile polyposis syndrome associates Gene BMPR1A""...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Juvenile po...",
5,Laron Syndrome associates Gene GHR,"(252, 252)","The statement ""Laron Syndrome associates Gene GHR"" suggests that t...",MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[:IS_PART_O...,
6,Wiskott-Aldrich Syndrome is not associated with Gene WAS,"(545, 545)","To verify the statement ""Wiskott-Aldrich Syndrome is not associate...","MATCH (g:Gene {approvedSymbol: ""WAS""})-[:IS_PART_OF]->(a:GeneToDis...",
7,Smith-Lemli-Opitz Syndrome is not associated with Gene DHCR7,"(746, 746)","To verify the statement ""Smith-Lemli-Opitz Syndrome is not associa...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Smith-Lemli...",
8,Johanson-Blizzard syndrome associates Gene UBR1,"(53, 53)","The statement ""Johanson-Blizzard syndrome associates Gene UBR1"" im...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Johanson-Bl...",✔️ [True]
9,Noonan Syndrome associates Gene RAF1,"(209, 209)","The statement ""Noonan Syndrome associates Gene RAF1"" implies that ...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Noonan Synd...",

47.0

In [77]:
tp = dspy.MIPROv2(metric = validate_query, auto="light")
optimized_cot_cypher = tp.compile(cot_cypher, trainset=trainset)

2024/12/23 15:03:21 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 7
minibatch: True
num_candidates: 5
valset size: 79

2024/12/23 15:03:30 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2024/12/23 15:03:30 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2024/12/23 15:03:30 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=5 sets of demonstrations...

Bootstrapping set 1/5
Bootstrapping set 2/5
Bootstrapping set 3/5

100%|██████████| 20/20 [02:07<00:00,  6.39s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 4/5

100%|██████████| 20/20 [00:20<00:00,  1.01s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 5/5

 90%|█████████ | 18/20 [00:18<00:02,  1.01s/it]
2024/12/23 15:06:16 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2024/12/23 15:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.

Bootstrapped 2 full traces after 18 examples for up to 1 rounds, amounting to 18 attempts.

2024/12/23 15:06:24 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing instructions...

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Generate cypher statement to check correctness of a statement

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given a natural language statement that links genetic disorders or syndromes with specific genes, and a schema of a Neo4j database, generate a Cypher query to verify the correctness of the statement according to the database schema. Begin by reasoning through the statement step-by-step to ensure a logical and accurate transformation into a Cypher query. Use the Chain of Thought method to articulate your reasoning process, and then construct a valid Cypher query that can be executed to check the statement's validity within the context of the provided database schema.

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Using the provided Neo4j schema and a given statement about a gene-disease association, generate a Cypher query that verifies the accuracy of the statement by checking the existence of a corresponding relationship in the database. Provide step-by-step reasoning for the verification process and output the constructed Cypher query.

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: 3: Create a Cypher query to verify the accuracy of a given statement regarding gene-disease associations in a Neo4j database, using the provided schema to identify relevant nodes and relationships.

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: 4: Create a Cypher query to verify the accuracy of a genetic association statement between a disease and a gene. Utilize the provided Neo4j schema to identify and match the relevant nodes and relationships that represent the entities in the statement. Include a detailed reasoning process to explain the steps taken to construct the query. Return the generated Cypher query along with the reasoning.

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 15:06:59 INFO dspy.teleprompt.mipro_optimizer_v2: Evaluating the default program...

Average Metric: 42.00 / 79 (53.2%): 100%|██████████| 79/79 [01:04<00:00,  1.22it/s]

2024/12/23 15:08:04 INFO dspy.evaluate.evaluate: Average Metric: 42 / 79 (53.2%)
2024/12/23 15:08:04 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 53.16

2024/12/23 15:08:04 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2024/12/23 15:08:04 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

d:\AppData\conda_envs\pistoia\Lib\site-packages\optuna\_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2024/12/23 15:08:04 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 1 / 7 ==

Average Metric: 12.00 / 25 (48.0%): 100%|██████████| 25/25 [00:35<00:00,  1.42s/it]

2024/12/23 15:08:40 INFO dspy.evaluate.evaluate: Average Metric: 12 / 25 (48.0%)
2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0]
2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:08:40 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 2 / 7 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:32<00:00,  1.29s/it]

2024/12/23 15:09:12 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0]
2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:09:12 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 3 / 7 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [00:36<00:00,  1.47s/it]

2024/12/23 15:09:49 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0, 80.0]
2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:09:49 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 4 / 7 ==

Average Metric: 14.00 / 25 (56.0%): 100%|██████████| 25/25 [00:22<00:00,  1.11it/s]

2024/12/23 15:10:12 INFO dspy.evaluate.evaluate: Average Metric: 14 / 25 (56.0%)
2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 56.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0, 80.0, 56.0]
2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:10:12 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 5 / 7 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [00:34<00:00,  1.39s/it]

2024/12/23 15:10:46 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 3'].
2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0, 80.0, 56.0, 80.0]
2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:10:46 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 6 / 7 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [00:02<00:00, 11.71it/s]

2024/12/23 15:10:49 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0, 80.0, 56.0, 80.0, 52.0]
2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:10:49 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 7 / 7 ==

Average Metric: 18.00 / 25 (72.0%): 100%|██████████| 25/25 [00:35<00:00,  1.41s/it]

2024/12/23 15:11:24 INFO dspy.evaluate.evaluate: Average Metric: 18 / 25 (72.0%)
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 72.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 4'].
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [48.0, 68.0, 80.0, 56.0, 80.0, 52.0, 72.0]
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 1 =====
2024/12/23 15:11:24 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 80.0) from minibatch trials...

Average Metric: 51.00 / 79 (64.6%): 100%|██████████| 79/79 [01:04<00:00,  1.23it/s]

2024/12/23 15:12:29 INFO dspy.evaluate.evaluate: Average Metric: 51 / 79 (64.6%)
2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 64.56
2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 64.56]
2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 64.56
2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 15:12:29 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 64.56!

In [78]:
evaluate_program(optimized_cot_cypher)

Average Metric: 59.00 / 100 (59.0%): 100%|██████████| 100/100 [14:12<00:00,  8.52s/it]

2024/12/23 15:27:21 INFO dspy.evaluate.evaluate: Average Metric: 59 / 100 (59.0%)

,statement,answer,reasoning,cypher,validate_query
0,Polycythemia Vera is not associated with Gene JAK2,"(518, 518)","To verify the statement ""Polycythemia Vera is not associated with ...","```cypher\nMATCH (d:Disease {name: ""Polycythemia Vera""})-[:IS_PART...",
1,Cystic Fibrosis associates Gene CFTR,"(7134, 7134)","To verify the statement ""Cystic Fibrosis associates Gene CFTR,"" we...","```cypher\nMATCH (d:Disease {name: ""Cystic Fibrosis""})-[:IS_PART_O...",
2,Cleidocranial Dysplasia associates Gene RUNX2,"(392, 392)","To verify the statement ""Cleidocranial Dysplasia associates Gene R...","```cypher\nMATCH (d:Disease {name: ""Cleidocranial Dysplasia""})-[:I...",
3,Ellis-Van Creveld Syndrome associates Gene EVC2,"(1150, 1150)","To verify the statement ""Ellis-Van Creveld Syndrome associates Gen...","```cypher\nMATCH (d:Disease {name: ""Ellis-Van Creveld Syndrome""})-...",
4,Juvenile polyposis syndrome associates Gene BMPR1A,"(1154, 1154)","To verify the statement ""Juvenile polyposis syndrome associates Ge...","```cypher\nMATCH (d:Disease {name: ""Juvenile polyposis syndrome""})...",
5,Laron Syndrome associates Gene GHR,"(252, 252)","To verify the statement ""Laron Syndrome associates Gene GHR,"" we n...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Laron Syndr...",
6,Wiskott-Aldrich Syndrome is not associated with Gene WAS,"(545, 545)","To verify the statement ""Wiskott-Aldrich Syndrome is not associate...","```cypher\nMATCH (d:Disease {name: ""Wiskott-Aldrich Syndrome""})-[:...",
7,Smith-Lemli-Opitz Syndrome is not associated with Gene DHCR7,"(746, 746)","To verify the statement ""Smith-Lemli-Opitz Syndrome is not associa...","```cypher\nMATCH (g:Gene {approvedSymbol: ""DHCR7""})-[:IS_PART_OF]-...",
8,Johanson-Blizzard syndrome associates Gene UBR1,"(53, 53)","To verify the statement ""Johanson-Blizzard syndrome associates Gen...","```cypher\nMATCH (d:DiseaseOrPhenotypicFeature {name: ""Johanson-Bl...",✔️ [True]
9,Noonan Syndrome associates Gene RAF1,"(209, 209)","To verify the statement ""Noonan Syndrome associates Gene RAF1"" usi...","```cypher\nMATCH (d:Disease {name: ""Noonan Syndrome""})-[:IS_PART_O...",

59.0

In [79]:
dspy.inspect_history(1)

[2024-12-23T15:27:20.848492]

System message:

Your input fields are:
1. `statement` (str)
2. `neo4j_schema` (str): Schema of a neo4j database

Your output fields are:
1. `reasoning` (str)
2. `cypher` (str): Valid cypher query that can be used to check correctness of the statement

All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## statement ## ]]
{statement}

[[ ## neo4j_schema ## ]]
{neo4j_schema}

[[ ## reasoning ## ]]
{reasoning}

[[ ## cypher ## ]]
{cypher}

[[ ## completed ## ]]

In adhering to this structure, your objective is:
        Create a Cypher query to verify the accuracy of a genetic association statement between a disease and a gene. Utilize the provided Neo4j schema to identify and match the relevant nodes and relationships that represent the entities in the statement. Include a detailed reasoning process to explain the steps taken to construct the query. Return the generated Cypher query along with the reasoning.


User message:

[[ ## statement ## ]]
Smith-Lemli-Opitz Syndrome is associated with Gene TBX5

[[ ## neo4j_schema ## ]]
Node properties:
- **Entity**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **ThingWithTaxon**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **DiseaseOrPhenotypicFeature**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `modelPhenotypeLabel`: STRING
- **Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
- **Obi.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OBI_1110122', 'http://purl.obolibrary.org/obo/OBI_0001621', 'http://purl.obolibrary.org/obo/OBI_0001620', 'http://purl.obolibrary.org/obo/OBI_1110021']
  - `name`: STRING Available options: ['pathological process', 'longitude', 'latitude', 'infect']
  - `description`: STRING Available options: ['Abnormal, harmful processes caused by or associate', 'A measurement that is the measure of the longitude', 'A measurement that is the measure of the latitude ', 'The detrimental process in which an infectious age']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['obi:1110122', 'obi:0001621', 'obi:0001620', 'obi:1110021']
  - `preferred_id`: STRING Available options: ['obi']
- **BiologicalEntity**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **NamedThing**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **Ncit.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/NCIT_C74532', 'http://purl.obolibrary.org/obo/NCIT_C117245', 'http://purl.obolibrary.org/obo/NCIT_C95746']
  - `name`: STRING Available options: ['nervousness', 'decreased attention', 'sleepiness']
  - `description`: STRING Available options: ['An uneasy psychological state; the anxious feeling', 'Impaired ability to focus on a subject or idea.', 'The sensation of struggling to remain awake.']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ncit:C74532', 'ncit:C117245', 'ncit:C95746']
  - `preferred_id`: STRING Available options: ['ncit']
- **Mondo.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/MONDO_0000385"
  - `name`: STRING Example: "benign digestive system neoplasm"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "mondo:0000385"
  - `preferred_id`: STRING Available options: ['mondo']
  - `description`: STRING Example: "A non-metastasizing neoplasm arising from any part"
- **Association**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **Literature.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **AnimalModel.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 11
  - `score`: FLOAT Example: "0.4947"
  - `source`: STRING Example: "impc"
  - `licence`: STRING Example: "NA"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "1ed93ef5539f388a1423ba9b98a7b71f610d2a10"
  - `preferred_id`: STRING Example: "id"
- **Hp.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/HP_0002751"
  - `name`: STRING Example: "Kyphoscoliosis"
  - `description`: STRING Example: "An abnormal curvature of the spine in both a coron"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "hp:0002751"
  - `preferred_id`: STRING Available options: ['hp']
- **RnaExpression.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.04389890211572866"
  - `source`: STRING Example: "expression_atlas"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00019f5ecfc23eeddacf2a7c1a2a51a55620e7ff"
  - `preferred_id`: STRING Example: "id"
- **Oba.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBA_2001015"
  - `name`: STRING Example: "age of onset of childhood onset asthma"
  - `description`: STRING Example: "The age at which childhood onset asthma manifestat"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "oba:2001015"
  - `preferred_id`: STRING Available options: ['oba']
- **Gene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **MouseGene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
- **KnownDrug.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.1"
  - `source`: STRING Example: "chembl"
  - `licence`: STRING Example: "CC BY-SA 3.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "99af831915f347fcb03e76c2f5ea7e2315bf77ce"
  - `preferred_id`: STRING Example: "id"
- **Doid.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/DOID_13406', 'http://purl.obolibrary.org/obo/DOID_0050890', 'http://purl.obolibrary.org/obo/DOID_10718', 'http://purl.obolibrary.org/obo/DOID_1947', 'http://purl.obolibrary.org/obo/DOID_7551', 'http://purl.obolibrary.org/obo/DOID_10113']
  - `name`: STRING Available options: ['pulmonary sarcoidosis', 'synucleinopathy', 'giardiasis', 'trichomoniasis', 'gonorrhea', 'trypanosomiasis']
  - `description`: STRING Available options: ['Sarcoidosis affecting the lung parenchyma. It is c', 'A neurodegenerative disease that is characterized ', 'A parasitic protozoa infectious disease that invol', 'A parasitic protozoa infectious disease that is ca', 'A primary bacterial infectious disease that is a s']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['doid:13406', 'doid:0050890', 'doid:10718', 'doid:1947', 'doid:7551', 'doid:10113']
  - `preferred_id`: STRING Available options: ['doid']
- **Efo.Disease**
  - `code`: STRING Example: "http://www.ebi.ac.uk/efo/EFO_0800502"
  - `name`: STRING Example: "linoleoyl-docosahexaenoyl-glycerol (18:2/22:6) [1]"
  - `description`: STRING Example: "Quantification of the amount of linoleoyl-docosahe"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "efo:0800502"
  - `preferred_id`: STRING Example: "efo"
- **PhenotypicFeature**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **MousePhenotype**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **Otar.Disease**
  - `code`: STRING Available options: ['http://www.ebi.ac.uk/efo/OTAR_0000018', 'http://www.ebi.ac.uk/efo/OTAR_0000006', 'http://www.ebi.ac.uk/efo/OTAR_0000014', 'http://www.ebi.ac.uk/efo/OTAR_0000020', 'http://www.ebi.ac.uk/efo/OTAR_0000009', 'http://www.ebi.ac.uk/efo/OTAR_0000003', 'http://www.ebi.ac.uk/efo/OTAR_0000010', 'http://www.ebi.ac.uk/efo/OTAR_0000017', 'http://www.ebi.ac.uk/efo/OTAR_0000019']
  - `name`: STRING Available options: ['genetic, familial or congenital disease', 'musculoskeletal or connective tissue disease', 'pregnancy or perinatal disease', 'nutritional or metabolic disease', 'injury, poisoning or other complication', 'cyst', 'respiratory or thoracic disease', 'reproductive system or breast disease', 'familial disease']
  - `description`: STRING Available options: ['A disease caused by genetic modifications inherite', 'A disease involving the musculoskeletal or connect', 'A disease occurring during pregnancy or shortly af', 'Damage inflicted on the body as the direct of indi', 'A sac-like closed membranous structure that may be', 'A disease affecting the respiratory system or othe', 'A disease involving the reproductive system or the', 'A disease occurring in or affecting members of a f']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['otar:0000018', 'otar:0000006', 'otar:0000014', 'otar:0000020', 'otar:0000009', 'otar:0000003', 'otar:0000010', 'otar:0000017', 'otar:0000019']
  - `preferred_id`: STRING Available options: ['otar']
- **HumanGene**
  - `approvedSymbol`: STRING Example: "FEZ2"
  - `biotype`: STRING Example: "protein_coding"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSG00000171055"
  - `preferred_id`: STRING Example: "ensembl"
- **Orphanet.Disease**
  - `code`: STRING Example: "http://www.orpha.net/ORDO/Orphanet_158684"
  - `name`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `description`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "orphanet:158684"
  - `preferred_id`: STRING Available options: ['orphanet']
- **SomaticMutation.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 8
  - `score`: FLOAT Example: "0.25"
  - `source`: STRING Example: "cancer_gene_census"
  - `licence`: STRING Example: "Commercial use for Open Targets"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00bb9bb991a5d157ac87eb0a0a858d3225e91f7e"
  - `preferred_id`: STRING Example: "id"
- **AffectedPathway.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "1.0"
  - `source`: STRING Example: "reactome"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "0573156c99191306506c7d365c089e90481066e2"
  - `preferred_id`: STRING Example: "id"
  - `literature`: LIST Min Size: 1, Max Size: 21
- **GoTerm**
  - `name`: STRING Example: "adenosine 3,5-bisphosphate transmembrane transport"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "go:0071106"
  - `preferred_id`: STRING Example: "go"
- **GeneticAssociation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.35"
  - `source`: STRING Example: "eva"
  - `licence`: STRING Example: "EMBL-EBI terms of use"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "4c75fa3ffc3e72f7b7496fd13377a701dac6e0e7"
  - `preferred_id`: STRING Example: "id"
- **Ogms.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OGMS_0000063']
  - `name`: STRING Available options: ['disease course']
  - `description`: STRING Available options: ['The totality of all processes through which a give']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ogms:0000063']
  - `preferred_id`: STRING Available options: ['ogms']
- **_GraphConfig**
  - `_objectPropertyLabel`: STRING Available options: ['Relationship']
  - `_rangeRel`: STRING Available options: ['RANGE']
  - `_classLabel`: STRING Available options: ['Class']
  - `_subClassOfRel`: STRING Available options: ['SCO']
  - `_handleMultival`: INTEGER Min: 0, Max: 0
  - `_dataTypePropertyLabel`: STRING Available options: ['Property']
  - `_subPropertyOfRel`: STRING Available options: ['SPO']
  - `_handleRDFTypes`: INTEGER Min: 0, Max: 0
  - `_classNamePropName`: STRING Available options: ['name']
  - `_handleVocabUris`: INTEGER Min: 0, Max: 0
  - `_applyNeo4jNaming`: BOOLEAN
  - `_relNamePropName`: STRING Available options: ['name']
  - `_domainRel`: STRING Available options: ['DOMAIN']
  - `_keepLangTag`: BOOLEAN
  - `_keepCustomDataTypes`: BOOLEAN
Relationship properties:

The relationships:
(:Entity)-[:IS_PART_OF]->(:Entity)
(:Entity)-[:IS_PART_OF]->(:Association)
(:Entity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Entity)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Association)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)

47% -> 59% is a progress, but we'd expect 100% on such a simple task. 

Can we utilize heavy MIPROv2?

In [81]:
tp_heavy = dspy.MIPROv2(metric = validate_query, auto="heavy")
optimized_cot_cypher_heavy = tp_heavy.compile(cot_cypher, trainset=trainset)

2024/12/23 15:31:29 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING HEAVY AUTO RUN SETTINGS:
num_trials: 50
minibatch: True
num_candidates: 38
valset size: 79

2024/12/23 15:31:33 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2024/12/23 15:31:33 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2024/12/23 15:31:33 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=38 sets of demonstrations...

Bootstrapping set 1/38
Bootstrapping set 2/38
Bootstrapping set 3/38

100%|██████████| 20/20 [00:18<00:00,  1.09it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 4/38

100%|██████████| 20/20 [00:18<00:00,  1.10it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 5/38

 90%|█████████ | 18/20 [00:21<00:02,  1.17s/it]

Bootstrapped 2 full traces after 18 examples for up to 1 rounds, amounting to 18 attempts.
Bootstrapping set 6/38

  5%|▌         | 1/20 [00:00<00:08,  2.19it/s]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.
Bootstrapping set 7/38

 60%|██████    | 12/20 [00:10<00:07,  1.14it/s]

Bootstrapped 2 full traces after 12 examples for up to 1 rounds, amounting to 12 attempts.
Bootstrapping set 8/38

 40%|████      | 8/20 [00:11<00:17,  1.44s/it]

Bootstrapped 1 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.
Bootstrapping set 9/38

100%|██████████| 20/20 [00:20<00:00,  1.01s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 10/38

100%|██████████| 20/20 [00:17<00:00,  1.16it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 11/38

 40%|████      | 8/20 [00:10<00:15,  1.32s/it]

Bootstrapped 1 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.
Bootstrapping set 12/38

100%|██████████| 20/20 [00:22<00:00,  1.11s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 13/38

100%|██████████| 20/20 [00:21<00:00,  1.07s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 14/38

 30%|███       | 6/20 [00:01<00:02,  5.13it/s]

Bootstrapped 1 full traces after 6 examples for up to 1 rounds, amounting to 6 attempts.
Bootstrapping set 15/38

100%|██████████| 20/20 [00:20<00:00,  1.03s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 16/38

 30%|███       | 6/20 [00:11<00:26,  1.86s/it]

Bootstrapped 1 full traces after 6 examples for up to 1 rounds, amounting to 6 attempts.
Bootstrapping set 17/38

100%|██████████| 20/20 [00:20<00:00,  1.01s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 18/38

 75%|███████▌  | 15/20 [00:19<00:06,  1.28s/it]

Bootstrapped 2 full traces after 15 examples for up to 1 rounds, amounting to 15 attempts.
Bootstrapping set 19/38

100%|██████████| 20/20 [00:17<00:00,  1.17it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 20/38

100%|██████████| 20/20 [00:19<00:00,  1.01it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 21/38

 65%|██████▌   | 13/20 [00:06<00:03,  1.87it/s]

Bootstrapped 1 full traces after 13 examples for up to 1 rounds, amounting to 13 attempts.
Bootstrapping set 22/38

 20%|██        | 4/20 [00:00<00:02,  5.63it/s]

Bootstrapped 1 full traces after 4 examples for up to 1 rounds, amounting to 4 attempts.
Bootstrapping set 23/38

 20%|██        | 4/20 [00:13<00:53,  3.35s/it]

Bootstrapped 1 full traces after 4 examples for up to 1 rounds, amounting to 4 attempts.
Bootstrapping set 24/38

100%|██████████| 20/20 [00:16<00:00,  1.18it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 25/38

 40%|████      | 8/20 [00:01<00:02,  5.57it/s]

Bootstrapped 1 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.
Bootstrapping set 26/38

 55%|█████▌    | 11/20 [00:12<00:10,  1.15s/it]

Bootstrapped 1 full traces after 11 examples for up to 1 rounds, amounting to 11 attempts.
Bootstrapping set 27/38

 20%|██        | 4/20 [00:07<00:29,  1.86s/it]

Bootstrapped 1 full traces after 4 examples for up to 1 rounds, amounting to 4 attempts.
Bootstrapping set 28/38

 60%|██████    | 12/20 [00:15<00:10,  1.31s/it]

Bootstrapped 2 full traces after 12 examples for up to 1 rounds, amounting to 12 attempts.
Bootstrapping set 29/38

 95%|█████████▌| 19/20 [00:16<00:00,  1.14it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 19 attempts.
Bootstrapping set 30/38

100%|██████████| 20/20 [00:16<00:00,  1.19it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 31/38

 35%|███▌      | 7/20 [00:08<00:15,  1.16s/it]

Bootstrapped 1 full traces after 7 examples for up to 1 rounds, amounting to 7 attempts.
Bootstrapping set 32/38

 40%|████      | 8/20 [00:15<00:22,  1.88s/it]

Bootstrapped 1 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.
Bootstrapping set 33/38

100%|██████████| 20/20 [00:17<00:00,  1.17it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 34/38

 95%|█████████▌| 19/20 [00:19<00:01,  1.03s/it]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 19 attempts.
Bootstrapping set 35/38

100%|██████████| 20/20 [00:19<00:00,  1.01it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 36/38

100%|██████████| 20/20 [00:18<00:00,  1.08it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 37/38

100%|██████████| 20/20 [00:16<00:00,  1.18it/s]

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 20 attempts.
Bootstrapping set 38/38

 95%|█████████▌| 19/20 [00:18<00:00,  1.03it/s]
2024/12/23 15:40:17 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2024/12/23 15:40:17 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2024/12/23 15:40:17 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing instructions...

Bootstrapped 2 full traces after 19 examples for up to 1 rounds, amounting to 19 attempts.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Generate cypher statement to check correctness of a statement

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Imagine you are a bioinformatics researcher tasked with verifying the accuracy of genetic disorder-gene association claims using a Neo4j database. Your job is crucial because the results will influence ongoing genetic research projects and potential medical treatments. Given a statement asserting a specific gene-disease association and a Neo4j database schema, generate a Cypher query to verify the statement's correctness. Ensure your reasoning is detailed and logical, as the integrity of the research depends on the accuracy of your verification process.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Imagine you are tasked with ensuring the accuracy of critical genetic research data used for developing life-saving treatments. Your goal is to verify the correctness of statements regarding gene-disease associations by generating precise Cypher queries. Given a statement and a Neo4j schema, produce a step-by-step reasoning and a Cypher query to determine if the association exists in the database, thereby validating or refuting the claim. Your output will directly impact the reliability of the research findings and subsequent medical advancements.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 3: Create a Cypher query to validate the accuracy of a given statement about gene-disease associations using the specified Neo4j schema. Ensure the query identifies relevant nodes and relationships, and provide a logical reasoning process that outlines the steps taken to construct the query. The output should include both the reasoning and the Cypher query for checking the statement's validity within the graph database structure.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 4: Create a Cypher query to evaluate the validity of a genetic association statement. Given a statement that describes a potential relationship between a disease and a gene, along with a Neo4j database schema, determine if the relationship exists within the database. The output should include a step-by-step reasoning process and a Cypher query that searches for a `GeneToDiseaseAssociation` node connecting the specified disease and gene nodes. Use the provided schema to accurately identify the relevant nodes and relationships, ensuring the query reflects the database's structure and organization.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 5: You are a bioinformatics expert tasked with verifying genetic associations in a Neo4j graph database. Your goal is to generate a Cypher query that can determine the validity of a given statement concerning the association between a specific genetic disorder and a gene. Consider the database schema provided, and reason step by step to identify the relevant nodes and relationships. Use this information to construct a Cypher query that checks if the stated association exists. If the association is found, the statement is incorrect; otherwise, it is correct.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 6: You are a bioinformatics expert specializing in genetic data analysis. Your task is to generate a Cypher query that can verify the correctness of a given statement regarding gene-disease associations in a Neo4j database. Consider the provided statement and Neo4j schema, and construct a query that identifies the relevant nodes and relationships to determine if the association described in the statement is valid. Ensure your reasoning is clear and step-by-step to support the logic behind the query generation.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 7: Create a Cypher query to verify if a specified disease-gene association exists within a Neo4j database schema. Use the provided statement and schema to identify relevant nodes and relationships, ensuring the query checks for a `GeneToDiseaseAssociation` between the disease and gene mentioned in the statement.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 8: Create a Cypher query to evaluate the validity of a genetic association statement. Given a statement that describes a potential relationship between a disease and a gene, along with a Neo4j database schema, determine if the relationship exists within the database. The output should include a step-by-step reasoning process and a Cypher query that searches for a `GeneToDiseaseAssociation` node connecting the specified disease and gene nodes. Use the provided schema to accurately identify the relevant nodes and relationships, ensuring the query reflects the database's structure and organization.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 9: Create a Cypher query to evaluate the validity of a gene-disease association statement using a Neo4j graph database. The query should identify if there is a `GeneToDiseaseAssociation` relationship between the specified disease and gene nodes within the provided schema. Include a step-by-step reasoning to explain the logic behind the query construction.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 10: To verify the correctness of a statement regarding gene-disease associations, generate a Cypher query that matches the specified statement against a Neo4j database schema. Start by identifying the disease and gene mentioned in the statement. Use the schema to determine if a `GeneToDiseaseAssociation` node exists that links a `Disease` node with the specified disease name and a `Gene` node with the specified approved symbol. If such an association exists, the statement is incorrect; if not, it is correct. Provide the reasoning behind your query construction to ensure clarity in the verification process.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 11: You are a bioinformatics expert working with a Neo4j graph database. Your task is to generate a Cypher query to verify the correctness of a given statement that suggests an association between a specific disease and a gene. Use the provided statement and Neo4j schema to construct a query that checks for the existence of a `GeneToDiseaseAssociation` between the disease and gene nodes. Ensure your reasoning is clear and logical, outlining the steps taken to determine the validity of the statement.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 12: Create a Cypher query to verify the accuracy of a genetic association statement between a disease and a gene. Utilize the provided Neo4j schema to identify and match the relevant nodes and relationships that represent the entities in the statement. Include a detailed reasoning process to explain the steps taken to construct the query. Return the generated Cypher query along with the reasoning.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 13: Write a Cypher query to determine if a given statement about a gene-disease association is correct, using the provided Neo4j schema for guidance.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 14: Create a Cypher query to verify the accuracy of a given statement regarding gene-disease associations in a Neo4j database, using the provided schema to identify relevant nodes and relationships.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 15: Craft a Cypher query to validate the association between a disease and a gene as described in the input statement, using the provided Neo4j database schema. Ensure the query checks for a `GeneToDiseaseAssociation` relationship between the relevant disease and gene nodes, and return the nodes and relationship if they exist.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 16: You are a bioinformatics expert working with a Neo4j graph database. Your task is to generate a Cypher query to verify the correctness of a given statement that suggests an association between a specific disease and a gene. Use the provided statement and Neo4j schema to construct a query that checks for the existence of a `GeneToDiseaseAssociation` between the disease and gene nodes. Ensure your reasoning is clear and logical, outlining the steps taken to determine the validity of the statement.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 17: You are a bioinformatics expert specializing in genetic data analysis. Your task is to generate a Cypher query that can verify the correctness of a given statement regarding gene-disease associations in a Neo4j database. Consider the provided statement and Neo4j schema, and construct a query that identifies the relevant nodes and relationships to determine if the association described in the statement is valid. Ensure your reasoning is clear and step-by-step to support the logic behind the query generation.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 18: Create a Cypher query to validate the accuracy of a given statement about gene-disease associations using the specified Neo4j schema. Ensure the query identifies relevant nodes and relationships, and provide a logical reasoning process that outlines the steps taken to construct the query. The output should include both the reasoning and the Cypher query for checking the statement's validity within the graph database structure.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 19: Create a Cypher query to verify the accuracy of a genetic association statement between a disease and a gene. Utilize the provided Neo4j schema to identify and match the relevant nodes and relationships that represent the entities in the statement. Include a detailed reasoning process to explain the steps taken to construct the query. Return the generated Cypher query along with the reasoning.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 20: You are tasked with verifying the accuracy of a critical biomedical assertion regarding gene-disease associations. Given a statement and a Neo4j database schema, generate a Cypher query to determine the validity of the statement by checking for the existence of a specific `GeneToDiseaseAssociation` node. This task is essential for ensuring the integrity of genetic research data, which can impact patient diagnosis and treatment. Carefully analyze the schema and statement to construct a precise query that will either confirm or refute the association in question.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 21: You are tasked with verifying the accuracy of a critical biomedical assertion regarding gene-disease associations. Given a statement and a Neo4j database schema, generate a Cypher query to determine the validity of the statement by checking for the existence of a specific `GeneToDiseaseAssociation` node. This task is essential for ensuring the integrity of genetic research data, which can impact patient diagnosis and treatment. Carefully analyze the schema and statement to construct a precise query that will either confirm or refute the association in question.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 22: Using the provided statement about a gene-disease association and the schema of a Neo4j database, generate a Cypher query to verify the correctness of the association. Your task is to identify the nodes and relationships within the database that correspond to the disease and gene mentioned in the statement. Construct a Cypher query that matches these nodes and checks for a `GeneToDiseaseAssociation` relationship between them. Ensure your query is valid and can accurately confirm whether the specified association exists in the database. Provide a detailed reasoning process for how you derive the query, considering the types of nodes and relationships involved.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 23: Create a Cypher query to validate the accuracy of a given statement about gene-disease associations using the specified Neo4j schema. Ensure the query identifies relevant nodes and relationships, and provide a logical reasoning process that outlines the steps taken to construct the query. The output should include both the reasoning and the Cypher query for checking the statement's validity within the graph database structure.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 24: To verify the correctness of a statement regarding gene-disease associations, generate a Cypher query that matches the specified statement against a Neo4j database schema. Start by identifying the disease and gene mentioned in the statement. Use the schema to determine if a `GeneToDiseaseAssociation` node exists that links a `Disease` node with the specified disease name and a `Gene` node with the specified approved symbol. If such an association exists, the statement is incorrect; if not, it is correct. Provide the reasoning behind your query construction to ensure clarity in the verification process.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 25: Using the provided statement about a gene-disease association and the schema of a Neo4j database, generate a Cypher query to verify the correctness of the association. Your task is to identify the nodes and relationships within the database that correspond to the disease and gene mentioned in the statement. Construct a Cypher query that matches these nodes and checks for a `GeneToDiseaseAssociation` relationship between them. Ensure your query is valid and can accurately confirm whether the specified association exists in the database. Provide a detailed reasoning process for how you derive the query, considering the types of nodes and relationships involved.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 26: Given a statement suggesting an association between a disease and a gene, and a Neo4j database schema, generate a Cypher query to verify the correctness of the association. Use the schema to identify potential nodes and relationships, and construct a query that matches these nodes and relationships to check if the association exists in the database. Provide both the reasoning process and the Cypher query as outputs.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 27: Imagine you are tasked with verifying critical gene-disease associations in a large-scale genetic research project. Your goal is to ensure the accuracy of statements linking specific genetic disorders with genes using a Neo4j database. For each statement provided, generate a Cypher query that determines whether the statement is correct by checking for the presence or absence of a `GeneToDiseaseAssociation` node between the relevant disease and gene nodes. Provide a detailed reasoning process to accompany your query, explaining each step of your logic to ensure transparency and reliability in your findings. This verification is crucial for advancing research and ensuring the integrity of genetic data.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 28: Create a Cypher query to verify the accuracy of a genetic association statement between a disease and a gene. Utilize the provided Neo4j schema to identify and match the relevant nodes and relationships that represent the entities in the statement. Include a detailed reasoning process to explain the steps taken to construct the query. Return the generated Cypher query along with the reasoning.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 29: Imagine you are tasked with ensuring the accuracy of critical genetic research data used for developing life-saving treatments. Your goal is to verify the correctness of statements regarding gene-disease associations by generating precise Cypher queries. Given a statement and a Neo4j schema, produce a step-by-step reasoning and a Cypher query to determine if the association exists in the database, thereby validating or refuting the claim. Your output will directly impact the reliability of the research findings and subsequent medical advancements.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 30: Using the provided statement about a gene-disease association and the schema of a Neo4j database, generate a Cypher query to verify the correctness of the association. Your task is to identify the nodes and relationships within the database that correspond to the disease and gene mentioned in the statement. Construct a Cypher query that matches these nodes and checks for a `GeneToDiseaseAssociation` relationship between them. Ensure your query is valid and can accurately confirm whether the specified association exists in the database. Provide a detailed reasoning process for how you derive the query, considering the types of nodes and relationships involved.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 31: Using the provided statement about a gene-disease association and the schema of a Neo4j database, generate a Cypher query to verify the correctness of the association. Your task is to identify the nodes and relationships within the database that correspond to the disease and gene mentioned in the statement. Construct a Cypher query that matches these nodes and checks for a `GeneToDiseaseAssociation` relationship between them. Ensure your query is valid and can accurately confirm whether the specified association exists in the database. Provide a detailed reasoning process for how you derive the query, considering the types of nodes and relationships involved.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 32: Imagine you are tasked with verifying critical gene-disease associations in a large-scale genetic research project. Your goal is to ensure the accuracy of statements linking specific genetic disorders with genes using a Neo4j database. For each statement provided, generate a Cypher query that determines whether the statement is correct by checking for the presence or absence of a `GeneToDiseaseAssociation` node between the relevant disease and gene nodes. Provide a detailed reasoning process to accompany your query, explaining each step of your logic to ensure transparency and reliability in your findings. This verification is crucial for advancing research and ensuring the integrity of genetic data.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 33: Using the provided Neo4j schema and a given statement about a gene-disease association, generate a Cypher query that verifies the accuracy of the statement by checking the existence of a corresponding relationship in the database. Provide step-by-step reasoning for the verification process and output the constructed Cypher query.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 34: Create a Cypher query to evaluate the validity of a gene-disease association statement using a Neo4j graph database. The query should identify if there is a `GeneToDiseaseAssociation` relationship between the specified disease and gene nodes within the provided schema. Include a step-by-step reasoning to explain the logic behind the query construction.

2024/12/23 15:41:21 INFO dspy.teleprompt.mipro_optimizer_v2: 35: Create a Cypher query to evaluate the validity of a gene-disease association statement using a Neo4j graph database. The query should identify if there is a `GeneToDiseaseAssociation` relationship between the specified disease and gene nodes within the provided schema. Include a step-by-step reasoning to explain the logic behind the query construction.


Average Metric: 42.00 / 79 (53.2%): 100%|██████████| 79/79 [00:11<00:00,  7.01it/s]

2024/12/23 15:41:33 INFO dspy.evaluate.evaluate: Average Metric: 42 / 79 (53.2%)
2024/12/23 15:41:33 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 53.16

2024/12/23 15:41:33 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2024/12/23 15:41:33 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

d:\AppData\conda_envs\pistoia\Lib\site-packages\optuna\_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2024/12/23 15:41:33 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 1 / 50 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [00:22<00:00,  1.13it/s]

2024/12/23 15:41:55 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 26', 'Predictor 0: Few-Shot Set 10'].
2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0]
2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:41:55 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 2 / 50 ==

Average Metric: 14.00 / 25 (56.0%): 100%|██████████| 25/25 [01:07<00:00,  2.68s/it]

2024/12/23 15:43:03 INFO dspy.evaluate.evaluate: Average Metric: 14 / 25 (56.0%)
2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 56.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 7', 'Predictor 0: Few-Shot Set 15'].
2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0]
2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:43:03 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 3 / 50 ==

Average Metric: 15.00 / 25 (60.0%): 100%|██████████| 25/25 [00:22<00:00,  1.09it/s]

2024/12/23 15:43:26 INFO dspy.evaluate.evaluate: Average Metric: 15 / 25 (60.0%)
2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 8', 'Predictor 0: Few-Shot Set 20'].
2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0]
2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:43:26 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 4 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:38<00:00,  1.55s/it]

2024/12/23 15:44:05 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 7', 'Predictor 0: Few-Shot Set 11'].
2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0]
2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:44:05 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 5 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:22<00:00,  1.12it/s]

2024/12/23 15:44:27 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 5', 'Predictor 0: Few-Shot Set 20'].
2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0]
2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:44:27 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 6 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:22<00:00,  1.14it/s]

2024/12/23 15:44:49 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 21', 'Predictor 0: Few-Shot Set 0'].
2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0]
2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:44:49 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 7 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:35<00:00,  1.42s/it]

2024/12/23 15:45:25 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 34', 'Predictor 0: Few-Shot Set 9'].
2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0]
2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:45:25 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 8 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:45<00:00,  1.82s/it]

2024/12/23 15:46:11 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 32', 'Predictor 0: Few-Shot Set 3'].
2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0]
2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:46:11 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 9 / 50 ==

Average Metric: 0.00 / 100 (0.0%):   5%|▌         | 5/100 [55:03<17:25:58, 660.61s/it]
Average Metric: 24.00 / 25 (96.0%): 100%|██████████| 25/25 [01:11<00:00,  2.86s/it]

2024/12/23 15:47:23 INFO dspy.evaluate.evaluate: Average Metric: 24 / 25 (96.0%)
2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 96.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 21', 'Predictor 0: Few-Shot Set 26'].
2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0]
2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: ============================


2024/12/23 15:47:23 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 10 / 50 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [00:24<00:00,  1.01it/s]

2024/12/23 15:47:48 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 24'].
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0]
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16]
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 53.16
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 1 =====
2024/12/23 15:47:48 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 96.0) from minibatch trials...

Average Metric: 57.00 / 79 (72.2%): 100%|██████████| 79/79 [02:44<00:00,  2.08s/it]

2024/12/23 15:50:33 INFO dspy.evaluate.evaluate: Average Metric: 57 / 79 (72.2%)
2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 72.15
2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 15:50:33 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 11 / 50 ==

Average Metric: 19.00 / 25 (76.0%): 100%|██████████| 25/25 [01:07<00:00,  2.69s/it]

2024/12/23 15:51:41 INFO dspy.evaluate.evaluate: Average Metric: 19 / 25 (76.0%)
2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 76.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 18', 'Predictor 0: Few-Shot Set 26'].
2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0]
2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:51:41 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 12 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:21<00:00,  1.17it/s]

2024/12/23 15:52:02 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 21', 'Predictor 0: Few-Shot Set 5'].
2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0]
2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:52:02 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 13 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:23<00:00,  1.05it/s]

2024/12/23 15:52:27 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 12', 'Predictor 0: Few-Shot Set 24'].
2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0]
2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:52:27 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 14 / 50 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [00:15<00:00,  1.58it/s]

2024/12/23 15:52:43 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 13'].
2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0]
2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 15 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:40<00:00,  1.61s/it]

2024/12/23 15:53:23 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 21', 'Predictor 0: Few-Shot Set 26'].
2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0]
2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:53:23 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 16 / 50 ==

Average Metric: 23.00 / 25 (92.0%): 100%|██████████| 25/25 [01:11<00:00,  2.87s/it]

2024/12/23 15:54:35 INFO dspy.evaluate.evaluate: Average Metric: 23 / 25 (92.0%)
2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 92.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 35', 'Predictor 0: Few-Shot Set 25'].
2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0]
2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:54:35 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 17 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [01:05<00:00,  2.61s/it]

2024/12/23 15:55:40 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 27', 'Predictor 0: Few-Shot Set 25'].
2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0]
2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:55:40 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 18 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [01:13<00:00,  2.94s/it]

2024/12/23 15:56:54 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 35', 'Predictor 0: Few-Shot Set 25'].
2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0]
2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:56:54 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 19 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:26<00:00,  1.05s/it]

2024/12/23 15:57:21 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 35', 'Predictor 0: Few-Shot Set 2'].
2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0]
2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:57:21 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 20 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:37<00:00,  1.50s/it]

2024/12/23 15:57:59 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 16', 'Predictor 0: Few-Shot Set 37'].
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0]
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15]
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: =============================

2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 2 =====
2024/12/23 15:57:59 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 80.0) from minibatch trials...

Average Metric: 52.00 / 79 (65.8%): 100%|██████████| 79/79 [00:30<00:00,  2.57it/s]

2024/12/23 15:58:29 INFO dspy.evaluate.evaluate: Average Metric: 52 / 79 (65.8%)
2024/12/23 15:58:29 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 15:58:29 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:58:29 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 15:58:29 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 15:58:29 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 21 / 50 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [01:10<00:00,  2.81s/it]

2024/12/23 15:59:40 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 22', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0]
2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 15:59:40 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 22 / 50 ==

Average Metric: 15.00 / 25 (60.0%): 100%|██████████| 25/25 [00:52<00:00,  2.12s/it]

2024/12/23 16:00:33 INFO dspy.evaluate.evaluate: Average Metric: 15 / 25 (60.0%)
2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 17'].
2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0]
2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:00:33 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 23 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:27<00:00,  1.09s/it]

2024/12/23 16:01:00 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 24', 'Predictor 0: Few-Shot Set 24'].
2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0]
2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:01:01 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 24 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:43<00:00,  1.73s/it]

2024/12/23 16:01:44 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 1'].
2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0]
2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:01:44 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 25 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [02:22<00:00,  5.69s/it]

2024/12/23 16:04:06 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 37', 'Predictor 0: Few-Shot Set 27'].
2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0]
2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:04:06 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 26 / 50 ==

Average Metric: 18.00 / 25 (72.0%): 100%|██████████| 25/25 [01:05<00:00,  2.62s/it]

2024/12/23 16:05:12 INFO dspy.evaluate.evaluate: Average Metric: 18 / 25 (72.0%)
2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 72.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 29', 'Predictor 0: Few-Shot Set 22'].
2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0]
2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:05:12 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 27 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:34<00:00,  1.37s/it]

2024/12/23 16:05:47 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 15', 'Predictor 0: Few-Shot Set 34'].
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0]
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 28 / 50 ==

Average Metric: 12.00 / 25 (48.0%): 100%|██████████| 25/25 [00:00<00:00, 36.04it/s]

2024/12/23 16:05:47 INFO dspy.evaluate.evaluate: Average Metric: 12 / 25 (48.0%)
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 24'].
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0]
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:05:47 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 29 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [01:00<00:00,  2.41s/it]

2024/12/23 16:06:48 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 30', 'Predictor 0: Few-Shot Set 12'].
2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0]
2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:06:48 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 30 / 50 ==

Average Metric: 18.00 / 25 (72.0%): 100%|██████████| 25/25 [00:45<00:00,  1.84s/it]

2024/12/23 16:07:34 INFO dspy.evaluate.evaluate: Average Metric: 18 / 25 (72.0%)
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 72.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 31', 'Predictor 0: Few-Shot Set 18'].
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0]
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82]
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 3 =====
2024/12/23 16:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 80.0) from minibatch trials...

Average Metric: 56.00 / 79 (70.9%): 100%|██████████| 79/79 [02:55<00:00,  2.22s/it]

2024/12/23 16:10:30 INFO dspy.evaluate.evaluate: Average Metric: 56 / 79 (70.9%)
2024/12/23 16:10:30 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:10:30 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:10:30 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 16:10:30 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 16:10:30 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 31 / 50 ==

Average Metric: 19.00 / 25 (76.0%): 100%|██████████| 25/25 [00:57<00:00,  2.29s/it]

2024/12/23 16:11:27 INFO dspy.evaluate.evaluate: Average Metric: 19 / 25 (76.0%)
2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 76.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 11', 'Predictor 0: Few-Shot Set 14'].
2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0]
2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:11:27 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 32 / 50 ==

Average Metric: 15.00 / 25 (60.0%): 100%|██████████| 25/25 [00:19<00:00,  1.31it/s]

2024/12/23 16:11:46 INFO dspy.evaluate.evaluate: Average Metric: 15 / 25 (60.0%)
2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 10', 'Predictor 0: Few-Shot Set 21'].
2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0]
2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:11:46 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 33 / 50 ==

Average Metric: 18.00 / 25 (72.0%): 100%|██████████| 25/25 [00:40<00:00,  1.63s/it]

2024/12/23 16:12:27 INFO dspy.evaluate.evaluate: Average Metric: 18 / 25 (72.0%)
2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 72.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 22', 'Predictor 0: Few-Shot Set 6'].
2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0]
2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:12:27 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 34 / 50 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [01:12<00:00,  2.91s/it]

2024/12/23 16:13:40 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 17', 'Predictor 0: Few-Shot Set 7'].
2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0]
2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:13:40 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 35 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [00:23<00:00,  1.07it/s]

2024/12/23 16:14:04 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 9', 'Predictor 0: Few-Shot Set 36'].
2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0]
2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:14:04 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 36 / 50 ==

Average Metric: 15.00 / 25 (60.0%): 100%|██████████| 25/25 [00:39<00:00,  1.59s/it]

2024/12/23 16:14:44 INFO dspy.evaluate.evaluate: Average Metric: 15 / 25 (60.0%)
2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 6', 'Predictor 0: Few-Shot Set 29'].
2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0]
2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:14:44 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 37 / 50 ==

Average Metric: 19.00 / 25 (76.0%): 100%|██████████| 25/25 [00:41<00:00,  1.65s/it]

2024/12/23 16:15:25 INFO dspy.evaluate.evaluate: Average Metric: 19 / 25 (76.0%)
2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 76.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 28', 'Predictor 0: Few-Shot Set 32'].
2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0]
2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:15:25 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 38 / 50 ==

Average Metric: 17.00 / 25 (68.0%): 100%|██████████| 25/25 [01:29<00:00,  3.59s/it]

2024/12/23 16:16:55 INFO dspy.evaluate.evaluate: Average Metric: 17 / 25 (68.0%)
2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 68.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 14', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0]
2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 39 / 50 ==

Average Metric: 14.00 / 25 (56.0%): 100%|██████████| 25/25 [01:05<00:00,  2.61s/it]

2024/12/23 16:18:00 INFO dspy.evaluate.evaluate: Average Metric: 14 / 25 (56.0%)
2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 56.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 8'].
2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0]
2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:18:00 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 40 / 50 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [00:44<00:00,  1.77s/it]

2024/12/23 16:18:44 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 3', 'Predictor 0: Few-Shot Set 33'].
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0]
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89]
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 4 =====
2024/12/23 16:18:44 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 78.0) from minibatch trials...

Average Metric: 56.00 / 79 (70.9%): 100%|██████████| 79/79 [03:12<00:00,  2.43s/it]

2024/12/23 16:21:57 INFO dspy.evaluate.evaluate: Average Metric: 56 / 79 (70.9%)
2024/12/23 16:21:57 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:21:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:21:57 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 16:21:57 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 16:21:57 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 41 / 50 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [01:00<00:00,  2.40s/it]

2024/12/23 16:22:57 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 23', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0]
2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:22:57 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 42 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [01:06<00:00,  2.66s/it]

2024/12/23 16:24:04 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0]
2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:24:04 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 43 / 50 ==

Average Metric: 15.00 / 25 (60.0%): 100%|██████████| 25/25 [00:22<00:00,  1.09it/s]

2024/12/23 16:24:27 INFO dspy.evaluate.evaluate: Average Metric: 15 / 25 (60.0%)
2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 13', 'Predictor 0: Few-Shot Set 10'].
2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0]
2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:24:27 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 44 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [00:37<00:00,  1.52s/it]

2024/12/23 16:25:05 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 23', 'Predictor 0: Few-Shot Set 18'].
2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0]
2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:25:05 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 45 / 50 ==

Average Metric: 16.00 / 25 (64.0%): 100%|██████████| 25/25 [01:14<00:00,  2.97s/it]

2024/12/23 16:26:19 INFO dspy.evaluate.evaluate: Average Metric: 16 / 25 (64.0%)
2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 64.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 26', 'Predictor 0: Few-Shot Set 31'].
2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0]
2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:26:19 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 46 / 50 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [00:43<00:00,  1.73s/it]

2024/12/23 16:27:03 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 20', 'Predictor 0: Few-Shot Set 35'].
2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0, 80.0]
2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:27:03 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 47 / 50 ==

Average Metric: 19.00 / 25 (76.0%): 100%|██████████| 25/25 [02:50<00:00,  6.84s/it]

2024/12/23 16:29:54 INFO dspy.evaluate.evaluate: Average Metric: 19 / 25 (76.0%)
2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 76.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 32', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0, 80.0, 76.0]
2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:29:54 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 48 / 50 ==

Average Metric: 20.00 / 25 (80.0%): 100%|██████████| 25/25 [00:37<00:00,  1.49s/it]

2024/12/23 16:30:31 INFO dspy.evaluate.evaluate: Average Metric: 20 / 25 (80.0%)
2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 80.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 25', 'Predictor 0: Few-Shot Set 28'].
2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0, 80.0, 76.0, 80.0]
2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:30:31 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 49 / 50 ==

Average Metric: 18.00 / 25 (72.0%): 100%|██████████| 25/25 [00:50<00:00,  2.00s/it]

2024/12/23 16:31:21 INFO dspy.evaluate.evaluate: Average Metric: 18 / 25 (72.0%)
2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 72.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 36', 'Predictor 0: Few-Shot Set 19'].
2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0, 80.0, 76.0, 80.0, 72.0]
2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:31:21 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 50 / 50 ==

Average Metric: 19.00 / 25 (76.0%): 100%|██████████| 25/25 [00:42<00:00,  1.69s/it]

2024/12/23 16:32:04 INFO dspy.evaluate.evaluate: Average Metric: 19 / 25 (76.0%)
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 76.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 22', 'Predictor 0: Few-Shot Set 30'].
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [52.0, 56.0, 60.0, 64.0, 68.0, 64.0, 68.0, 68.0, 96.0, 80.0, 76.0, 64.0, 64.0, 52.0, 68.0, 92.0, 64.0, 64.0, 64.0, 64.0, 80.0, 60.0, 68.0, 64.0, 64.0, 72.0, 68.0, 48.0, 64.0, 72.0, 76.0, 60.0, 72.0, 52.0, 68.0, 60.0, 76.0, 68.0, 56.0, 52.0, 80.0, 64.0, 60.0, 64.0, 64.0, 80.0, 76.0, 80.0, 72.0, 76.0]
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89]
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: =============================


2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 5 =====
2024/12/23 16:32:04 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 80.0) from minibatch trials...

Average Metric: 57.00 / 79 (72.2%): 100%|██████████| 79/79 [02:38<00:00,  2.00s/it]

2024/12/23 16:34:42 INFO dspy.evaluate.evaluate: Average Metric: 57 / 79 (72.2%)
2024/12/23 16:34:42 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [53.16, 72.15, 65.82, 70.89, 70.89, 72.15]
2024/12/23 16:34:42 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 72.15
2024/12/23 16:34:42 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/23 16:34:42 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/23 16:34:42 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 72.15!

In [82]:
evaluate_program(optimized_cot_cypher_heavy)

Average Metric: 67.00 / 100 (67.0%): 100%|██████████| 100/100 [24:00<00:00, 14.40s/it]

2024/12/23 17:05:20 INFO dspy.evaluate.evaluate: Average Metric: 67 / 100 (67.0%)

,statement,answer,reasoning,cypher,validate_query
0,Polycythemia Vera is not associated with Gene JAK2,"(518, 518)","The statement ""Polycythemia Vera is not associated with Gene JAK2""...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
1,Cystic Fibrosis associates Gene CFTR,"(7134, 7134)","The statement ""Cystic Fibrosis associates Gene CFTR"" implies that ...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
2,Cleidocranial Dysplasia associates Gene RUNX2,"(392, 392)","The statement ""Cleidocranial Dysplasia associates Gene RUNX2"" impl...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
3,Ellis-Van Creveld Syndrome associates Gene EVC2,"(1150, 1150)","The statement ""Ellis-Van Creveld Syndrome associates Gene EVC2"" im...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
4,Juvenile polyposis syndrome associates Gene BMPR1A,"(1154, 1154)","The statement ""Juvenile polyposis syndrome associates Gene BMPR1A""...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
5,Laron Syndrome associates Gene GHR,"(252, 252)","The statement ""Laron Syndrome associates Gene GHR"" implies a relat...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
6,Wiskott-Aldrich Syndrome is not associated with Gene WAS,"(545, 545)","The statement ""Wiskott-Aldrich Syndrome is not associated with Gen...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
7,Smith-Lemli-Opitz Syndrome is not associated with Gene DHCR7,"(746, 746)","The statement ""Smith-Lemli-Opitz Syndrome is not associated with G...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,
8,Johanson-Blizzard syndrome associates Gene UBR1,"(53, 53)","The statement ""Johanson-Blizzard syndrome associates Gene UBR1"" im...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,✔️ [True]
9,Noonan Syndrome associates Gene RAF1,"(209, 209)","The statement ""Noonan Syndrome associates Gene RAF1"" implies that ...",```cypher MATCH (d)-[:IS_PART_OF]->(a:GeneToDiseaseAssociation)<-[...,✔️ [True]

67.0

So: 
- default CoT: 47%
- "light" optimized CoT: 59%
- "heavy" optimized CoT: 67%

In [83]:
optimized_cot_cypher_heavy.save("09-optimized_cot_cypher_heavy-gpt4o.json", save_field_meta=True)
optimized_cot_cypher.save("09-optimized_cot_cypher-gpt4o.json", save_field_meta=True)

WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.
WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.