# Using DSPy framework

In [2]:
import os
from dotenv import load_dotenv
from tqdm import tqdm
import json
import pandas as pd
import re

# Load environment variables from the .env file
load_dotenv()

# Retrieve the variables from the environment
neo4j_uri = os.getenv("NEO4J_URI")
neo4j_username = os.getenv("NEO4J_USERNAME")
neo4j_password = os.getenv("NEO4J_PASSWORD")

# Check if any variable is missing
if not all([neo4j_uri, neo4j_username, neo4j_password]):
    raise EnvironmentError("One or more environment variables are missing: NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD")

print(f"Accessing OpenTargets at {neo4j_uri} as user {neo4j_username}")

Accessing OpenTargets at bolt+s://pistoia.neo4j.rbsapp.net:7687 as user neo4j

In [3]:
from langchain_community.graphs import Neo4jGraph

enhanced_graph = Neo4jGraph(
    url=neo4j_uri,
    username=neo4j_username,
    password=neo4j_password,
    enhanced_schema=True,
)

enhanced_schema = enhanced_graph.schema

print(enhanced_schema)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"

Node properties:
- **Entity**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `modelPhenotypeLabel`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **ThingWithTaxon**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **DiseaseOrPhenotypicFeature**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `modelPhenotypeLabel`: STRING
- **Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
- **Obi.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OBI_1110122', 'http://purl.obolibrary.org/obo/OBI_0001621', 'http://purl.obolibrary.org/obo/OBI_0001620', 'http://purl.obolibrary.org/obo/OBI_1110021']
  - `name`: STRING Available options: ['pathological process', 'longitude', 'latitude', 'infect']
  - `description`: STRING Available options: ['Abnormal, harmful processes caused by or associate', 'A measurement that is the measure of the longitude', 'A measurement that is the measure of the latitude ', 'The detrimental process in which an infectious age']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['obi:1110122', 'obi:0001621', 'obi:0001620', 'obi:1110021']
  - `preferred_id`: STRING Available options: ['obi']
- **BiologicalEntity**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **NamedThing**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **Ncit.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/NCIT_C74532', 'http://purl.obolibrary.org/obo/NCIT_C117245', 'http://purl.obolibrary.org/obo/NCIT_C95746']
  - `name`: STRING Available options: ['nervousness', 'decreased attention', 'sleepiness']
  - `description`: STRING Available options: ['An uneasy psychological state; the anxious feeling', 'Impaired ability to focus on a subject or idea.', 'The sensation of struggling to remain awake.']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ncit:C74532', 'ncit:C117245', 'ncit:C95746']
  - `preferred_id`: STRING Available options: ['ncit']
- **Mondo.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/MONDO_0000385"
  - `name`: STRING Example: "benign digestive system neoplasm"
  - `description`: STRING Example: "A non-metastasizing neoplasm arising from any part"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "mondo:0000385"
  - `preferred_id`: STRING Available options: ['mondo']
- **Association**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **Literature.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **AnimalModel.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 11
  - `score`: FLOAT Example: "0.4947"
  - `source`: STRING Example: "impc"
  - `licence`: STRING Example: "NA"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "1ed93ef5539f388a1423ba9b98a7b71f610d2a10"
  - `preferred_id`: STRING Example: "id"
- **Hp.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/HP_0002751"
  - `name`: STRING Example: "Kyphoscoliosis"
  - `description`: STRING Example: "An abnormal curvature of the spine in both a coron"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "hp:0002751"
  - `preferred_id`: STRING Available options: ['hp']
- **RnaExpression.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.04389890211572866"
  - `source`: STRING Example: "expression_atlas"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00019f5ecfc23eeddacf2a7c1a2a51a55620e7ff"
  - `preferred_id`: STRING Example: "id"
- **Oba.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBA_2001015"
  - `name`: STRING Example: "age of onset of childhood onset asthma"
  - `description`: STRING Example: "The age at which childhood onset asthma manifestat"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "oba:2001015"
  - `preferred_id`: STRING Available options: ['oba']
- **Gene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **MouseGene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
- **KnownDrug.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.1"
  - `source`: STRING Example: "chembl"
  - `licence`: STRING Example: "CC BY-SA 3.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "99af831915f347fcb03e76c2f5ea7e2315bf77ce"
  - `preferred_id`: STRING Example: "id"
- **Doid.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/DOID_13406', 'http://purl.obolibrary.org/obo/DOID_0050890', 'http://purl.obolibrary.org/obo/DOID_10718', 'http://purl.obolibrary.org/obo/DOID_1947', 'http://purl.obolibrary.org/obo/DOID_7551', 'http://purl.obolibrary.org/obo/DOID_10113']
  - `name`: STRING Available options: ['pulmonary sarcoidosis', 'synucleinopathy', 'giardiasis', 'trichomoniasis', 'gonorrhea', 'trypanosomiasis']
  - `description`: STRING Available options: ['Sarcoidosis affecting the lung parenchyma. It is c', 'A neurodegenerative disease that is characterized ', 'A parasitic protozoa infectious disease that invol', 'A parasitic protozoa infectious disease that is ca', 'A primary bacterial infectious disease that is a s']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['doid:13406', 'doid:0050890', 'doid:10718', 'doid:1947', 'doid:7551', 'doid:10113']
  - `preferred_id`: STRING Available options: ['doid']
- **Efo.Disease**
  - `code`: STRING Example: "http://www.ebi.ac.uk/efo/EFO_0800502"
  - `name`: STRING Example: "linoleoyl-docosahexaenoyl-glycerol (18:2/22:6) [1]"
  - `description`: STRING Example: "Quantification of the amount of linoleoyl-docosahe"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "efo:0800502"
  - `preferred_id`: STRING Example: "efo"
- **PhenotypicFeature**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **MousePhenotype**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **Otar.Disease**
  - `code`: STRING Available options: ['http://www.ebi.ac.uk/efo/OTAR_0000018', 'http://www.ebi.ac.uk/efo/OTAR_0000006', 'http://www.ebi.ac.uk/efo/OTAR_0000014', 'http://www.ebi.ac.uk/efo/OTAR_0000020', 'http://www.ebi.ac.uk/efo/OTAR_0000009', 'http://www.ebi.ac.uk/efo/OTAR_0000003', 'http://www.ebi.ac.uk/efo/OTAR_0000010', 'http://www.ebi.ac.uk/efo/OTAR_0000017', 'http://www.ebi.ac.uk/efo/OTAR_0000019']
  - `name`: STRING Available options: ['genetic, familial or congenital disease', 'musculoskeletal or connective tissue disease', 'pregnancy or perinatal disease', 'nutritional or metabolic disease', 'injury, poisoning or other complication', 'cyst', 'respiratory or thoracic disease', 'reproductive system or breast disease', 'familial disease']
  - `description`: STRING Available options: ['A disease caused by genetic modifications inherite', 'A disease involving the musculoskeletal or connect', 'A disease occurring during pregnancy or shortly af', 'Damage inflicted on the body as the direct of indi', 'A sac-like closed membranous structure that may be', 'A disease affecting the respiratory system or othe', 'A disease involving the reproductive system or the', 'A disease occurring in or affecting members of a f']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['otar:0000018', 'otar:0000006', 'otar:0000014', 'otar:0000020', 'otar:0000009', 'otar:0000003', 'otar:0000010', 'otar:0000017', 'otar:0000019']
  - `preferred_id`: STRING Available options: ['otar']
- **HumanGene**
  - `approvedSymbol`: STRING Example: "FEZ2"
  - `biotype`: STRING Example: "protein_coding"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSG00000171055"
  - `preferred_id`: STRING Example: "ensembl"
- **Orphanet.Disease**
  - `code`: STRING Example: "http://www.orpha.net/ORDO/Orphanet_158684"
  - `name`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "orphanet:158684"
  - `preferred_id`: STRING Available options: ['orphanet']
  - `description`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
- **SomaticMutation.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 8
  - `score`: FLOAT Example: "0.25"
  - `source`: STRING Example: "cancer_gene_census"
  - `licence`: STRING Example: "Commercial use for Open Targets"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00bb9bb991a5d157ac87eb0a0a858d3225e91f7e"
  - `preferred_id`: STRING Example: "id"
- **AffectedPathway.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 21
  - `score`: FLOAT Example: "1.0"
  - `source`: STRING Example: "reactome"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "0573156c99191306506c7d365c089e90481066e2"
  - `preferred_id`: STRING Example: "id"
- **GoTerm**
  - `name`: STRING Example: "adenosine 3,5-bisphosphate transmembrane transport"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "go:0071106"
  - `preferred_id`: STRING Example: "go"
- **GeneticAssociation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.35"
  - `source`: STRING Example: "eva"
  - `licence`: STRING Example: "EMBL-EBI terms of use"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "4c75fa3ffc3e72f7b7496fd13377a701dac6e0e7"
  - `preferred_id`: STRING Example: "id"
- **Ogms.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OGMS_0000063']
  - `name`: STRING Available options: ['disease course']
  - `description`: STRING Available options: ['The totality of all processes through which a give']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ogms:0000063']
  - `preferred_id`: STRING Available options: ['ogms']
- **_GraphConfig**
  - `_objectPropertyLabel`: STRING Available options: ['Relationship']
  - `_rangeRel`: STRING Available options: ['RANGE']
  - `_classLabel`: STRING Available options: ['Class']
  - `_subClassOfRel`: STRING Available options: ['SCO']
  - `_handleMultival`: INTEGER Min: 0, Max: 0
  - `_dataTypePropertyLabel`: STRING Available options: ['Property']
  - `_subPropertyOfRel`: STRING Available options: ['SPO']
  - `_handleRDFTypes`: INTEGER Min: 0, Max: 0
  - `_classNamePropName`: STRING Available options: ['name']
  - `_handleVocabUris`: INTEGER Min: 0, Max: 0
  - `_applyNeo4jNaming`: BOOLEAN
  - `_relNamePropName`: STRING Available options: ['name']
  - `_domainRel`: STRING Available options: ['DOMAIN']
  - `_keepLangTag`: BOOLEAN
  - `_keepCustomDataTypes`: BOOLEAN
Relationship properties:

The relationships:
(:Entity)-[:IS_PART_OF]->(:Entity)
(:Entity)-[:IS_PART_OF]->(:Association)
(:Entity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Entity)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Association)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Entity)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Association)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Entity)
(:Disease)-[:IS_PART_OF]->(:Association)
(:Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)

In [4]:
# Cypher data extraction

def extract_cypher(message):
    text = message
    pattern = r"```cypher(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    try:
        return [match.strip() for match in matches]
    except Exception:
        raise ValueError(f"Failed to parse: {message}")

from py2neo import Graph

graph = Graph(
    neo4j_uri,
    auth=(neo4j_username, neo4j_password)
)

In [5]:
# Some queries take a very long time to run. This will deal with timeout

import threading

class TimeoutThread(threading.Thread):
    def __init__(self, func, *args, **kwargs):
        threading.Thread.__init__(self)
        self.func = func
        self.args = args
        self.kwargs = kwargs
        self.result = None
        self.error = None

    def run(self):
        try:
            self.result = self.func(*self.args, **self.kwargs)
        except Exception as e:
            self.error = e

def run_with_timeout(func, timeout, *args, **kwargs):
    thread = TimeoutThread(func, *args, **kwargs)
    thread.start()
    thread.join(timeout)

    if thread.is_alive():
        raise TimeoutError("Function execution timed out")
    elif thread.error:
        raise thread.error
    return thread.result

In [23]:
# convenience functions for data retrieval from graph

import time

def query_cypher_graph(graph, query):
    return graph.query(query)

def query_graph(llm_output):
    try:
        start = time.time()
        result = run_with_timeout(query_cypher_graph, 20, graph, llm_output)
        duration = time.time() - start
        return {
            "query":llm_output,
            "success":True,
            "result": list(result),
            "time": duration
        }
    except Exception as e:
        return {
            "query":llm_output,
            "result": f"Failed to execute query: {str(e)}",
            "success":False,
            "exception":str(e)
        }

In order to use DSPy prompt optimization capabilities we need a good evaluation dataset, so we'll use biomix for test and evaluation.

As a base query we will use an enchanced LLM schema that is provided by the LangChain.

In [7]:
# DSPy setup:

import dspy

llm = dspy.LM("openai/gpt-4o", max_tokens = 2000)
dspy.settings.configure(lm = llm)

d:\AppData\conda_envs\pistoia\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Loading test-set

In [8]:
import random

questions_test = pd.read_csv("biomix_true_false_selected_augmented.csv").rename(columns={"text":"question" , "label": "answer"}).sample(frac=1, random_state=42).reset_index(drop=True)
questions_train = pd.read_csv("biomix_true_false_selected_augmented_2.csv").rename(columns={"text":"question" , "label": "answer"}).sample(frac=1, random_state=42).reset_index(drop=True)


testset = [dspy.Example(statement=x['question'], answer=x['answer']).with_inputs("statement") for _, x in questions_test.iterrows()]
trainset = [dspy.Example(statement=x['question'], answer=x['answer']).with_inputs("statement") for _, x in questions_train.iterrows()]

## Evaluating DSPy strategies

### 9.1 Naive QA

Just predicting truthfulness of a statement

In [9]:
# First version is a simple QA to answer question:

predict = dspy.Predict("statement -> answer")
answer = predict(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    answer='The statement is incorrect. Polycythemia Vera is associated with the JAK2 gene mutation. Most patients with Polycythemia Vera have a mutation in the JAK2 gene, specifically JAK2 V617F.'
)

In [10]:
# Doing the same but with signatures:

from pydantic import BaseModel, Field

class AnswerCorrectness(BaseModel):
    correctness: bool = Field(description="Correctness of the statement")
    explanation: str = Field(description="Explanation of the correctness")
    

class QACorrectness(dspy.Signature):
    """Given the statement, evaluate its correctness"""
    statement: str = dspy.InputField(desc="The statement to be evaluated")
    answer: AnswerCorrectness = dspy.OutputField()

predict = dspy.Predict(QACorrectness)
answer = predict(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    answer=AnswerCorrectness(correctness=False, explanation='Polycythemia Vera is associated with mutations in the JAK2 gene, specifically the JAK2 V617F mutation, which is present in the majority of cases.')
)

In [11]:
# Evaluating with dspy Evaluate
from dspy.evaluate import Evaluate
from dspy.evaluate.metrics import answer_exact_match

def validate_answer(example, pred, trace=None):
    return example.answer == pred.answer.correctness

evaluate_program = Evaluate(devset = testset, metric=validate_answer, display_progress=True, display_table=10, provide_traceback=True)

In [12]:
eval = evaluate_program(predict)
print(eval)

Average Metric: 100.00 / 100 (100.0%): 100%|██████████| 100/100 [02:01<00:00,  1.22s/it]

2024/12/15 00:55:17 INFO dspy.evaluate.evaluate: Average Metric: 100 / 100 (100.0%)

,statement,example_answer,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,correctness=False explanation='Argininosuccinic Aciduria is not as...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,correctness=True explanation='Cherubism is a genetic disorder char...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,correctness=True explanation='Cystinuria is a genetic disorder cha...,✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,correctness=False explanation='Pierson syndrome is indeed associat...,✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,correctness=False explanation='Mastocytosis is indeed associated w...,✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,correctness=True explanation='Argininosuccinic Aciduria is a disor...,✔️ [True]
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,correctness=True explanation='Bernard-Soulier Syndrome is a rare i...,✔️ [True]
7,CHARGE Syndrome is associated with Gene APRT,False,correctness=False explanation='CHARGE Syndrome is associated with ...,✔️ [True]
8,Progeria associates Gene LMNA,True,"correctness=True explanation='Progeria, specifically Hutchinson-Gi...",✔️ [True]
9,Polycythemia Vera is not associated with Gene JAK2,False,correctness=False explanation='Polycythemia Vera is associated wit...,✔️ [True]

100.0

### 9.2 Naive Chain Of Thought

Think step-by-step; output reflection

In [13]:
# chain of thought

cot = dspy.ChainOfThought(QACorrectness)
answer = cot(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    reasoning='Polycythemia Vera (PV) is a type of blood cancer characterized by an increase in red blood cells. It is strongly associated with mutations in the JAK2 gene, specifically the JAK2 V617F mutation, which is present in the majority of PV cases. This mutation leads to the overproduction of blood cells. Therefore, the statement that Polycythemia Vera is not associated with the JAK2 gene is incorrect.',
    answer=AnswerCorrectness(correctness=False, explanation='Polycythemia Vera is indeed associated with the JAK2 gene, particularly the JAK2 V617F mutation, which is found in most cases of the disease.')
)

In [14]:
eval = evaluate_program(cot)
print(eval)

Average Metric: 100.00 / 100 (100.0%): 100%|██████████| 100/100 [03:11<00:00,  1.91s/it]

2024/12/15 00:58:30 INFO dspy.evaluate.evaluate: Average Metric: 100 / 100 (100.0%)

,statement,example_answer,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,Argininosuccinic Aciduria is a rare genetic disorder that affects ...,correctness=False explanation='Argininosuccinic Aciduria is caused...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,Cherubism is a genetic disorder characterized by abnormal bone tis...,correctness=True explanation='Cherubism is associated with mutatio...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,Cystinuria is a genetic disorder characterized by the defective tr...,correctness=True explanation='Cystinuria is associated with mutati...,✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,Pierson syndrome is a rare genetic disorder characterized by conge...,correctness=False explanation='Pierson syndrome is associated with...,✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,Mastocytosis is a condition characterized by an abnormal accumulat...,correctness=False explanation='Mastocytosis is indeed associated w...,✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,Argininosuccinic aciduria is a rare genetic disorder that affects ...,correctness=True explanation='Argininosuccinic aciduria is indeed ...,✔️ [True]
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,Bernard-Soulier Syndrome is a rare inherited bleeding disorder cha...,correctness=True explanation='Bernard-Soulier Syndrome is associat...,✔️ [True]
7,CHARGE Syndrome is associated with Gene APRT,False,CHARGE Syndrome is a genetic disorder that is associated with muta...,correctness=False explanation='CHARGE Syndrome is associated with ...,✔️ [True]
8,Progeria associates Gene LMNA,True,"Progeria, specifically Hutchinson-Gilford Progeria Syndrome (HGPS)...","correctness=True explanation='Progeria, specifically Hutchinson-Gi...",✔️ [True]
9,Polycythemia Vera is not associated with Gene JAK2,False,Polycythemia Vera (PV) is a type of blood cancer characterized by ...,correctness=False explanation='Polycythemia Vera is indeed associa...,✔️ [True]

100.0

In [15]:
dspy.inspect_history(1)

[2024-12-15T00:58:30.242276]

System message:

Your input fields are:
1. `statement` (str): The statement to be evaluated

Your output fields are:
1. `reasoning` (str)
2. `answer` (AnswerCorrectness)

All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## statement ## ]]
{statement}

[[ ## reasoning ## ]]
{reasoning}

[[ ## answer ## ]]
{answer}        # note: the value you produce must be pareseable according to the following JSON schema: {"type": "object", "properties": {"correctness": {"type": "boolean", "description": "Correctness of the statement", "title": "Correctness"}, "explanation": {"type": "string", "description": "Explanation of the correctness", "title": "Explanation"}}, "required": ["correctness", "explanation"], "title": "AnswerCorrectness"}

[[ ## completed ## ]]

In adhering to this structure, your objective is:
        Given the statement, evaluate its correctness


User message:

[[ ## statement ## ]]
Adenine phosphoribosyltransferase deficiency is not associated with Gene LMNA

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
Adenine phosphoribosyltransferase (APRT) deficiency is a rare genetic disorder that affects the body's ability to recycle adenine, leading to the accumulation of 2,8-dihydroxyadenine, which can cause kidney stones and renal failure. This condition is caused by mutations in the APRT gene, not the LMNA gene. The LMNA gene is associated with a different set of disorders, including laminopathies such as Emery-Dreifuss muscular dystrophy, familial partial lipodystrophy, and Hutchinson-Gilford progeria syndrome. Therefore, the statement that APRT deficiency is not associated with the LMNA gene is correct.

[[ ## answer ## ]]
{"correctness": true, "explanation": "Adenine phosphoribosyltransferase deficiency is caused by mutations in the APRT gene, not the LMNA gene. The LMNA gene is associated with other disorders, such as laminopathies, but not with APRT deficiency."}

[[ ## completed ## ]]

### 9.3 Optimized Chain of Thought

Using MIPROv2 optimizer to prompt-optimize CoT

In [16]:
tp = dspy.MIPROv2(metric = validate_answer, auto="light")
optimized_cot = tp.compile(cot, trainset=trainset)

2024/12/15 00:58:30 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 7
minibatch: True
num_candidates: 5
valset size: 79

2024/12/15 01:02:31 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2024/12/15 01:02:31 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2024/12/15 01:02:31 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=5 sets of demonstrations...

Bootstrapping set 1/5
Bootstrapping set 2/5
Bootstrapping set 3/5

 20%|██        | 4/20 [00:11<00:44,  2.78s/it]

Bootstrapped 4 full traces after 4 examples for up to 1 rounds, amounting to 4 attempts.
Bootstrapping set 4/5

 15%|█▌        | 3/20 [00:08<00:47,  2.78s/it]

Bootstrapped 3 full traces after 3 examples for up to 1 rounds, amounting to 3 attempts.
Bootstrapping set 5/5

 10%|█         | 2/20 [00:04<00:44,  2.49s/it]
2024/12/15 01:02:55 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2024/12/15 01:02:55 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.

Bootstrapped 2 full traces after 2 examples for up to 1 rounds, amounting to 2 attempts.

2024/12/15 01:03:03 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing instructions...

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the statement, evaluate its correctness

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Evaluate the correctness of the given statement by applying a logical, step-by-step reasoning process. Start by carefully analyzing the statement to identify key elements and relationships. Then, construct a detailed reasoning sequence that systematically verifies each component of the statement, considering any relevant background information or context. Conclude with a definitive answer that clearly states whether the statement is correct or incorrect, supported by the reasoning provided. Ensure the reasoning is thorough and the conclusion is well-justified.

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Examine the provided statement about a genetic condition and its association with a specific gene. Use your knowledge to determine the accuracy of the statement, providing a step-by-step reasoning process and a final evaluation of correctness. Include an explanation that supports your conclusion.

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: 3: Analyze the provided genetic association statement to determine its correctness. Provide a step-by-step reasoning that explains your conclusion, and state whether the statement is true or false based on established genetic knowledge.

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: 4: Analyze the provided statement about a genetic disease and its association with a specific gene. Use your knowledge of genetic and medical information to determine if the statement is correct. Provide a detailed reasoning process that explains your conclusion, and state whether the statement is true or false based on the evidence.

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 01:03:23 INFO dspy.teleprompt.mipro_optimizer_v2: Evaluating the default program...

Average Metric: 79.00 / 79 (100.0%): 100%|██████████| 79/79 [00:31<00:00,  2.50it/s]

2024/12/15 01:03:54 INFO dspy.evaluate.evaluate: Average Metric: 79 / 79 (100.0%)
2024/12/15 01:03:54 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 100.0

2024/12/15 01:03:54 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2024/12/15 01:03:54 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

d:\AppData\conda_envs\pistoia\Lib\site-packages\optuna\_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2024/12/15 01:03:54 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 1 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:10<00:00,  2.31it/s]

2024/12/15 01:04:05 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 1'].
2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0]
2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:04:05 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 2 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:15<00:00,  1.57it/s]

2024/12/15 01:04:21 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1'].
2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0]
2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:04:21 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 3 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:18<00:00,  1.38it/s]

2024/12/15 01:04:40 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 1'].
2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0, 100.0]
2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:04:40 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 4 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:09<00:00,  2.61it/s]

2024/12/15 01:04:49 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1'].
2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0, 100.0, 100.0]
2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:04:49 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 5 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:14<00:00,  1.77it/s]

2024/12/15 01:05:03 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 3'].
2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0, 100.0, 100.0, 100.0]
2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:05:03 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 6 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:10<00:00,  2.45it/s]

2024/12/15 01:05:14 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1'].
2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:05:14 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 7 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:11<00:00,  2.11it/s]

2024/12/15 01:05:26 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 4', 'Predictor 0: Few-Shot Set 4'].
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0]
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 1 =====
2024/12/15 01:05:26 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 100.0) from minibatch trials...

Average Metric: 79.00 / 79 (100.0%): 100%|██████████| 79/79 [00:29<00:00,  2.72it/s]

2024/12/15 01:05:55 INFO dspy.evaluate.evaluate: Average Metric: 79 / 79 (100.0%)
2024/12/15 01:05:55 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [100.0, 100.0]
2024/12/15 01:05:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:05:55 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/15 01:05:55 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 01:05:55 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 100.0!

In [17]:
eval_optimized = evaluate_program(optimized_cot)
print(eval_optimized)

Average Metric: 100.00 / 100 (100.0%): 100%|██████████| 100/100 [00:00<00:00, 339.64it/s]

2024/12/15 01:05:55 INFO dspy.evaluate.evaluate: Average Metric: 100 / 100 (100.0%)

,statement,example_answer,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,Argininosuccinic Aciduria is a rare genetic disorder that affects ...,correctness=False explanation='Argininosuccinic Aciduria is caused...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,Cherubism is a genetic disorder characterized by abnormal bone tis...,correctness=True explanation='Cherubism is associated with mutatio...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,Cystinuria is a genetic disorder characterized by the defective tr...,correctness=True explanation='Cystinuria is associated with mutati...,✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,Pierson syndrome is a rare genetic disorder characterized by conge...,correctness=False explanation='Pierson syndrome is associated with...,✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,Mastocytosis is a condition characterized by an abnormal accumulat...,correctness=False explanation='Mastocytosis is indeed associated w...,✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,Argininosuccinic aciduria is a rare genetic disorder that affects ...,correctness=True explanation='Argininosuccinic aciduria is indeed ...,✔️ [True]
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,Bernard-Soulier Syndrome is a rare inherited bleeding disorder cha...,correctness=True explanation='Bernard-Soulier Syndrome is associat...,✔️ [True]
7,CHARGE Syndrome is associated with Gene APRT,False,CHARGE Syndrome is a genetic disorder that is associated with muta...,correctness=False explanation='CHARGE Syndrome is associated with ...,✔️ [True]
8,Progeria associates Gene LMNA,True,"Progeria, specifically Hutchinson-Gilford Progeria Syndrome (HGPS)...","correctness=True explanation='Progeria, specifically Hutchinson-Gi...",✔️ [True]
9,Polycythemia Vera is not associated with Gene JAK2,False,Polycythemia Vera (PV) is a type of blood cancer characterized by ...,correctness=False explanation='Polycythemia Vera is indeed associa...,✔️ [True]

100.0

In [18]:
optimized_cot.save("09-optimized_cot.json", save_field_meta=True)

WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.

In [19]:
dspy.inspect_history(n=1)

[2024-12-15T01:05:55.604952]

System message:

Your input fields are:
1. `statement` (str): The statement to be evaluated

Your output fields are:
1. `reasoning` (str)
2. `answer` (AnswerCorrectness)

All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## statement ## ]]
{statement}

[[ ## reasoning ## ]]
{reasoning}

[[ ## answer ## ]]
{answer}        # note: the value you produce must be pareseable according to the following JSON schema: {"type": "object", "properties": {"correctness": {"type": "boolean", "description": "Correctness of the statement", "title": "Correctness"}, "explanation": {"type": "string", "description": "Explanation of the correctness", "title": "Explanation"}}, "required": ["correctness", "explanation"], "title": "AnswerCorrectness"}

[[ ## completed ## ]]

In adhering to this structure, your objective is:
        Given the statement, evaluate its correctness


User message:

[[ ## statement ## ]]
Adenine phosphoribosyltransferase deficiency is not associated with Gene LMNA

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
Adenine phosphoribosyltransferase (APRT) deficiency is a rare genetic disorder that affects the body's ability to recycle adenine, leading to the accumulation of 2,8-dihydroxyadenine, which can cause kidney stones and renal failure. This condition is caused by mutations in the APRT gene, not the LMNA gene. The LMNA gene is associated with a different set of disorders, including laminopathies such as Emery-Dreifuss muscular dystrophy, familial partial lipodystrophy, and Hutchinson-Gilford progeria syndrome. Therefore, the statement that APRT deficiency is not associated with the LMNA gene is correct.

[[ ## answer ## ]]
{"correctness": true, "explanation": "Adenine phosphoribosyltransferase deficiency is caused by mutations in the APRT gene, not the LMNA gene. The LMNA gene is associated with other disorders, such as laminopathies, but not with APRT deficiency."}

[[ ## completed ## ]]

### 9.4 QA with cypher retrieval

This will work like RAG, but instead of semantic retrieval we will use Cypher retrieval

In [20]:
class GenerateCypher(dspy.Signature):
    """Generate cypher statement to check correctness of a statement"""
    statement = dspy.InputField()
    schema = dspy.InputField(desc="Schema of a neo4j database")
    cypher = dspy.OutputField(desc="Valid cypher query that can be used to check correctness of the statement")

cot_cypher = dspy.ChainOfThought(GenerateCypher)
answer = cot_cypher(statement = "Polycythemia Vera is not associated with Gene JAK2", schema=enhanced_schema)
answer

d:\AppData\conda_envs\pistoia\Lib\site-packages\pydantic\_internal\_fields.py:172: UserWarning: Field name "schema" in "GenerateCypher" shadows an attribute in parent "Signature"
  warnings.warn(
d:\AppData\conda_envs\pistoia\Lib\site-packages\pydantic\_internal\_fields.py:172: UserWarning: Field name "schema" in "StringSignature" shadows an attribute in parent "Signature"
  warnings.warn(

Prediction(
    reasoning='To verify the statement "Polycythemia Vera is not associated with Gene JAK2," we need to check if there is any association between the disease "Polycythemia Vera" and the gene "JAK2" in the database. The schema provides various nodes and relationships, including `GeneToDiseaseAssociation`, which is likely the relevant relationship type for this query. We will look for a `GeneToDiseaseAssociation` relationship between a `Disease` node with the name "Polycythemia Vera" and a `Gene` node with the approved symbol "JAK2". If such a relationship exists, it would contradict the statement.',
    cypher='```cypher\nMATCH (d:Disease {name: "Polycythemia Vera"})-[:IS_PART_OF]->(gda:GeneToDiseaseAssociation)<-[:IS_PART_OF]-(g:Gene {approvedSymbol: "JAK2"})\nRETURN gda\n```'
)

In [24]:
# More complicated module similar to RAG

class QACorrectnessContext(dspy.Signature):
    """Given the statement and cypher results, evaluate correctness of the statement with respect to the data in the graph. Do not use prior knowledge of biology"""
    statement: str = dspy.InputField(desc="The statement to be evaluated")
    context = dspy.InputField(desc="Results of cypher query to check the validity of statemet agains ground truth")
    answer: AnswerCorrectness = dspy.OutputField()

class GraphRAG(dspy.Module):

    def __init__(self, schema):
        super().__init__()
        self.generate_query  = dspy.ChainOfThought(GenerateCypher)
        self.generate_answer = dspy.ChainOfThought(QACorrectnessContext)
        self.schema = schema
    
    def forward(self, statement):
        query = self.generate_query(statement=statement, schema=self.schema)
        result = query_graph(query.cypher)
        query_result = str(result['result'])
        answer = self.generate_answer(statement=statement, context=query_result)
        return answer
    

graph_rag = GraphRAG(enhanced_schema)
answer = graph_rag(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

d:\AppData\conda_envs\pistoia\Lib\site-packages\pydantic\_internal\_fields.py:172: UserWarning: Field name "schema" in "StringSignature" shadows an attribute in parent "Signature"
  warnings.warn(

Prediction(
    reasoning='The context provided indicates a syntax error in the cypher query, which means the query did not execute successfully. Therefore, we do not have any data from the graph to confirm or refute the statement that "Polycythemia Vera is not associated with Gene JAK2". Without the results of a successful query, we cannot determine the correctness of the statement based on the provided context.',
    answer=AnswerCorrectness(correctness=False, explanation='The query to check the association between Polycythemia Vera and Gene JAK2 failed due to a syntax error, so we cannot determine the correctness of the statement based on the provided context.')
)

In [25]:
evaluate_program(graph_rag)

Average Metric: 54.00 / 100 (54.0%): 100%|██████████| 100/100 [08:22<00:00,  5.03s/it]

2024/12/15 01:25:35 INFO dspy.evaluate.evaluate: Average Metric: 54 / 100 (54.0%)

,statement,example_answer,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,"The context provided indicates a syntax error in the cypher query,...",correctness=False explanation='The cypher query failed due to a sy...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,"The context provided is an empty result set from a cypher query, w...",correctness=True explanation='The database query returned no resul...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,"The context provided is empty, which means there is no data availa...",correctness=False explanation='The context does not provide any in...,
3,Pierson syndrome is not associated with Gene LAMB2,False,The context provided indicates that there was a syntax error in th...,correctness=False explanation='The query to check the association ...,✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,The context provided indicates that there was a syntax error in th...,correctness=False explanation='The query to check the association ...,✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,The context provided indicates that there was a syntax error in th...,"correctness=False explanation=""The query to verify the association...",
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,The context provided indicates that there was a syntax error in th...,correctness=False explanation='The query to verify the association...,
7,CHARGE Syndrome is associated with Gene APRT,False,"The context provided indicates a syntax error in the cypher query,...",correctness=False explanation='The query to verify the association...,✔️ [True]
8,Progeria associates Gene LMNA,True,"The context provided indicates a syntax error in the cypher query,...",correctness=False explanation='The cypher query failed due to a sy...,
9,Polycythemia Vera is not associated with Gene JAK2,False,"The context provided indicates a syntax error in the cypher query,...",correctness=False explanation='The query to check the association ...,✔️ [True]

54.0

### 9.5. Optimized QC with cypher retrieval

In [26]:
tp = dspy.MIPROv2(metric = validate_answer, auto="light")
optimized_rag = tp.compile(graph_rag, trainset=trainset)

2024/12/15 01:36:27 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 7
minibatch: True
num_candidates: 3
valset size: 79

2024/12/15 01:36:30 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2024/12/15 01:36:30 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2024/12/15 01:36:30 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=3 sets of demonstrations...

Bootstrapping set 1/3
Bootstrapping set 2/3
Bootstrapping set 3/3

  0%|          | 0/20 [00:00<?, ?it/s]2024/12/15 01:36:38 ERROR dspy.teleprompt.bootstrap: Failed to run or to evaluate example Example({'statement': 'L-2-HYDROXYGLUTARIC ACIDURIA is not associated with Gene MANBA', 'answer': True}) (input_keys={'statement'}) with <function validate_answer at 0x000002020C075580> due to 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type.
 25%|██▌       | 5/20 [00:30<01:31,  6.10s/it]
2024/12/15 01:37:01 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2024/12/15 01:37:01 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2024/12/15 01:37:01 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing instructions...

Bootstrapped 4 full traces after 5 examples for up to 1 rounds, amounting to 5 attempts.

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Generate cypher statement to check correctness of a statement

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Imagine you are a researcher tasked with verifying the accuracy of a critical genetic association claim that could impact future medical treatments. Your job is to generate a Cypher query that will be executed against a Neo4j graph database to assess the validity of this claim. You are provided with the statement in question and the schema of the database. Carefully construct a Cypher statement that will accurately determine the correctness of the statement, ensuring that your approach is methodical and precise.

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Create a Cypher query that verifies the validity of a given statement about a disease-gene association using the provided Neo4j database schema. Ensure that the query checks for the presence or absence of the specified relationship and returns the results needed to confirm the statement's correctness.

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the statement and cypher results, evaluate correctness of the statement with respect to the data in the graph. Do not use prior knowledge of biology

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Imagine you are a genetic researcher tasked with verifying the validity of critical gene-disease association claims that could impact future medical treatments. Given the statement and the results from a Cypher query executed on the graph database, carefully evaluate the correctness of the statement solely based on the provided data. Your assessment will help decide whether to pursue further research on these associations, so accuracy is paramount. Do not rely on any prior biological knowledge; base your reasoning strictly on the data presented in the graph.

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: 2: You are a data analyst tasked with verifying the correctness of statements regarding gene-disease associations using results from a Neo4j graph database. For each statement provided, analyze the context of the cypher query results. If the query fails due to syntax errors, use logical reasoning based on the provided context to determine the likelihood of the statement's correctness. Provide a detailed explanation of your reasoning process and conclude with a verdict on the statement's correctness, without relying on prior biological knowledge.

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 01:37:30 INFO dspy.teleprompt.mipro_optimizer_v2: Evaluating the default program...

Average Metric: 38.00 / 79 (48.1%): 100%|██████████| 79/79 [01:17<00:00,  1.02it/s]

2024/12/15 01:38:48 INFO dspy.evaluate.evaluate: Average Metric: 38 / 79 (48.1%)
2024/12/15 01:38:48 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 48.1

2024/12/15 01:38:48 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2024/12/15 01:38:48 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

d:\AppData\conda_envs\pistoia\Lib\site-packages\optuna\_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2024/12/15 01:38:48 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 1 / 7 ==
d:\AppData\conda_envs\pistoia\Lib\site-packages\pydantic\_internal\_fields.py:172: UserWarning: Field name "schema" in "StringSignature" shadows an attribute in parent "Signature"
  warnings.warn(

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:44<00:00,  1.79s/it]

2024/12/15 01:39:32 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0]
2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:39:32 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 2 / 7 ==

Average Metric: 2.00 / 3 (66.7%):  12%|█▏        | 3/25 [00:03<00:18,  1.17it/s]

2024/12/15 01:39:36 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Saethre-Chotzen Syndrome is not associated with Gene NBN', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 4.00 / 5 (80.0%):  24%|██▍       | 6/25 [00:04<00:12,  1.54it/s]

2024/12/15 01:39:37 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Greig cephalopolysyndactyly syndrome is not associated with Gene ALPL', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 5.00 / 6 (83.3%):  28%|██▊       | 7/25 [00:05<00:09,  1.89it/s]

2024/12/15 01:39:39 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Aspartylglucosaminuria is not associated with Gene AGA', 'answer': False}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 7.00 / 9 (77.8%):  44%|████▍     | 11/25 [00:07<00:07,  1.89it/s]

2024/12/15 01:39:41 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Refsum Disease associates Gene PHYH', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 7.00 / 9 (77.8%):  52%|█████▏    | 13/25 [00:08<00:07,  1.61it/s]

2024/12/15 01:39:41 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Nail-Patella Syndrome associates Gene LMX1B', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 9.00 / 11 (81.8%):  60%|██████    | 15/25 [00:09<00:04,  2.04it/s]

2024/12/15 01:39:42 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Tuberous Sclerosis associates Gene TSC2', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 9.00 / 11 (81.8%):  68%|██████▊   | 17/25 [00:09<00:02,  2.79it/s]

2024/12/15 01:39:42 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'alpha-Mannosidosis associates Gene MAN2B1', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 12.00 / 14 (85.7%):  84%|████████▍ | 21/25 [00:11<00:01,  2.60it/s]

2024/12/15 01:39:45 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Choroideremia is not associated with Gene CHM', 'answer': False}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 12.00 / 14 (85.7%):  88%|████████▊ | 22/25 [00:12<00:01,  2.13it/s]

2024/12/15 01:39:45 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Gray Platelet Syndrome is not associated with Gene NBEAL2', 'answer': False}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 12.00 / 14 (85.7%):  92%|█████████▏| 23/25 [00:13<00:01,  1.76it/s]

2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0]
2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:39:47 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 3 / 7 ==

Exception occurred: 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type
Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:37<00:00,  1.52s/it]

2024/12/15 01:40:25 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0, 100.0]
2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:40:25 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 4 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:09<00:00,  2.60it/s]

2024/12/15 01:40:35 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0, 100.0, 100.0]
2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:40:35 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 5 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:08<00:00,  3.05it/s]

2024/12/15 01:40:43 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0, 100.0, 100.0, 100.0]
2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:40:43 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 6 / 7 ==

Average Metric: 12.00 / 14 (85.7%):  92%|█████████▏| 23/25 [01:15<00:06,  3.28s/it]
Average Metric: 9.00 / 9 (100.0%):  36%|███▌      | 9/25 [00:15<00:17,  1.08s/it]

2024/12/15 01:40:59 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Aspartylglucosaminuria is not associated with Gene AGA', 'answer': False}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 18.00 / 18 (100.0%):  76%|███████▌  | 19/25 [00:28<00:07,  1.28s/it]

2024/12/15 01:41:12 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'CAMPOMELIC DYSPLASIA is not associated with Gene RECQL4', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 19.00 / 19 (100.0%):  80%|████████  | 20/25 [00:29<00:05,  1.18s/it]

2024/12/15 01:41:12 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Pfeiffer Syndrome associates Gene FGFR2', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 21.00 / 21 (100.0%):  96%|█████████▌| 24/25 [00:32<00:00,  1.09it/s]

2024/12/15 01:41:18 ERROR dspy.utils.parallelizer: Error processing item Example({'statement': 'Fabry Disease associates Gene GLA', 'answer': True}) (input_keys={'statement'}): 1 validation error for AnswerCorrectness
correctness
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type. Set `provide_traceback=True` to see the stack trace.

Average Metric: 21.00 / 21 (100.0%): 100%|██████████| 25/25 [00:35<00:00,  1.41s/it]

2024/12/15 01:41:18 INFO dspy.evaluate.evaluate: Average Metric: 21.0 / 25 (84.0%)
2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 84.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 1'].
2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0, 100.0, 100.0, 100.0, 84.0]
2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:41:18 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 7 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:21<00:00,  1.15it/s]

2024/12/15 01:41:40 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [100.0, 0.0, 100.0, 100.0, 100.0, 84.0, 100.0]
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1]
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 48.1
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 1 =====
2024/12/15 01:41:40 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 100.0) from minibatch trials...

Average Metric: 79.00 / 79 (100.0%): 100%|██████████| 79/79 [01:14<00:00,  1.06it/s]

2024/12/15 01:42:54 INFO dspy.evaluate.evaluate: Average Metric: 79 / 79 (100.0%)
2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 100.0
2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [48.1, 100.0]
2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 01:42:54 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 100.0!

In [27]:
evaluate_program(optimized_rag)
optimized_cot.save("09.5-optimized_rag_gpt4omini.json", save_field_meta=True)

Average Metric: 100.00 / 100 (100.0%): 100%|██████████| 100/100 [09:43<00:00,  5.83s/it]

2024/12/15 02:04:23 INFO dspy.evaluate.evaluate: Average Metric: 100 / 100 (100.0%)

,statement,example_answer,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,"The context indicates a syntax error in the cypher query, preventi...",correctness=False explanation='The query failed due to a syntax er...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,"The context indicates a syntax error in the cypher query, preventi...","correctness=True explanation='Despite the query error, Cherubism i...",✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,"The context indicates a syntax error in the cypher query, preventi...","correctness=True explanation=""Despite the query error, Cystinuria ...",✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,"The context indicates a syntax error in the cypher query, preventi...","correctness=False explanation='Despite the query error, Pierson sy...",✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,"The context indicates a syntax error in the cypher query, preventi...","correctness=False explanation='Despite the query error, Mastocytos...",✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,"The context indicates a syntax error in the cypher query, preventi...","correctness=True explanation='Despite the query error, Argininosuc...",✔️ [True]
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,"The context indicates a syntax error in the cypher query, preventi...","correctness=True explanation='Despite the query error, Bernard-Sou...",✔️ [True]
7,CHARGE Syndrome is associated with Gene APRT,False,"The context provided indicates a syntax error in the cypher query,...",correctness=False explanation='The query failed due to a syntax er...,✔️ [True]
8,Progeria associates Gene LMNA,True,"The context indicates a syntax error in the cypher query, preventi...","correctness=True explanation='Despite the query error, Progeria is...",✔️ [True]
9,Polycythemia Vera is not associated with Gene JAK2,False,"The context indicates a syntax error in the cypher query, preventi...","correctness=False explanation='Despite the query error, Polycythem...",✔️ [True]

WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.

### 9.5 QA with ReAct

In [28]:
class AnswerCorrectness(BaseModel):
    correctness: bool = Field(description="Correctness of the statement")
    explanation: str = Field(description="Explanation of the correctness")
    

class QACorrectness(dspy.Signature):
    """Given the statement, evaluate its correctness using information in the knowledge graph"""
    statement: str = dspy.InputField(desc="The statement to be evaluated")
    answer: AnswerCorrectness = dspy.OutputField()

def run_cypher_query(cypher_statement:str) -> str:
    """Given the cypher statement, run the query and return the result"""
    result = query_graph(cypher_statement)
    return result

naive_react = dspy.ReAct(QACorrectness, tools = [run_cypher_query])
answer = naive_react(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    trajectory={'thought_0': 'To evaluate the correctness of the statement, I need to check if there is an association between Polycythemia Vera and the gene JAK2 in the knowledge graph.', 'tool_name_0': 'run_cypher_query', 'tool_args_0': {'cypher_statement': "MATCH (d:Disease {name: 'Polycythemia Vera'})-[:ASSOCIATED_WITH]->(g:Gene {name: 'JAK2'}) RETURN g"}, 'observation_0': {'query': "MATCH (d:Disease {name: 'Polycythemia Vera'})-[:ASSOCIATED_WITH]->(g:Gene {name: 'JAK2'}) RETURN g", 'success': True, 'result': [], 'time': 0.11180853843688965}, 'thought_1': 'The query result is an empty list, which indicates that there is no association between Polycythemia Vera and the gene JAK2 in the knowledge graph. Therefore, the statement "Polycythemia Vera is not associated with Gene JAK2" is correct.', 'tool_name_1': 'finish', 'tool_args_1': {}, 'observation_1': 'Completed.'},
    reasoning='The query to the knowledge graph returned an empty result, indicating that there is no recorded association between Polycythemia Vera and the gene JAK2. This supports the statement that "Polycythemia Vera is not associated with Gene JAK2" as being correct according to the data available in the knowledge graph.',
    answer=AnswerCorrectness(correctness=True, explanation="The knowledge graph does not show an association between Polycythemia Vera and the gene JAK2, supporting the statement's correctness.")
)

In [29]:
evaluate_program(naive_react)

Average Metric: 51.00 / 100 (51.0%): 100%|██████████| 100/100 [07:38<00:00,  4.59s/it]

2024/12/15 02:15:21 INFO dspy.evaluate.evaluate: Average Metric: 51 / 100 (51.0%)

,statement,example_answer,trajectory,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,"{'thought_0': 'To evaluate the correctness of the statement, I nee...",The statement claims that Argininosuccinic Aciduria is associated ...,correctness=False explanation='The knowledge graph does not show a...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,"{'thought_0': 'To evaluate the correctness of the statement ""Cheru...","The statement ""Cherubism is not associated with Gene UBR1"" was eva...",correctness=True explanation='The knowledge graph query returned n...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,"{'thought_0': 'To evaluate the correctness of the statement, I nee...",The query executed in the knowledge graph returned an empty result...,correctness=True explanation='The knowledge graph query returned n...,✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,"{'thought_0': 'To evaluate the correctness of the statement, I nee...","The query to the knowledge graph returned an empty result, indicat...",correctness=True explanation='The knowledge graph query returned n...,
4,Mastocytosis is not associated with Gene KIT,False,"{'thought_0': 'To evaluate the correctness of the statement ""Masto...","The statement ""Mastocytosis is not associated with Gene KIT"" was e...","correctness=True explanation=""The knowledge graph query returned n...",
5,Argininosuccinic Aciduria associates Gene ASL,True,"{'thought_0': 'To evaluate the correctness of the statement ""Argin...","The statement ""Argininosuccinic Aciduria associates Gene ASL"" was ...",correctness=False explanation='The knowledge graph does not show a...,
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,"{'thought_0': 'To evaluate the correctness of the statement ""Berna...","The statement ""Bernard-Soulier Syndrome associates Gene GP1BB"" was...",correctness=False explanation='The knowledge graph does not show a...,
7,CHARGE Syndrome is associated with Gene APRT,False,{'thought_0': 'I need to verify if CHARGE Syndrome is associated w...,The query to the knowledge graph did not return any associations b...,correctness=False explanation='The knowledge graph does not show a...,✔️ [True]
8,Progeria associates Gene LMNA,True,"{'thought_0': 'To evaluate the correctness of the statement ""Proge...","The statement ""Progeria associates Gene LMNA"" was evaluated by que...",correctness=False explanation='The knowledge graph does not show a...,
9,Polycythemia Vera is not associated with Gene JAK2,False,"{'thought_0': 'To evaluate the correctness of the statement, I nee...","The statement ""Polycythemia Vera is not associated with Gene JAK2""...","correctness=True explanation=""The knowledge graph query returned n...",

51.0

Doesn't really work as planned; need to do some optimizations

### 9.6 Optimized QA with ReAct

In [30]:
class AnswerCorrectness(BaseModel):
    correctness: bool = Field(description="Correctness of the statement")
    explanation: str = Field(description="Explanation of the correctness")
    

class QACorrectness(dspy.Signature):
    """Given the statement, evaluate its correctness using information in the knowledge graph"""
    statement: str = dspy.InputField(desc="The statement to be evaluated")
    answer: AnswerCorrectness = dspy.OutputField()

def run_cypher_query(cypher_statement:str) -> str:
    """Given the cypher statement, run the query and return the result"""
    result = query_graph(cypher_statement)
    return result

naive_react = dspy.ReAct(QACorrectness, tools = [run_cypher_query])
answer = naive_react(statement = "Polycythemia Vera is not associated with Gene JAK2")
answer

Prediction(
    trajectory={'thought_0': 'To evaluate the correctness of the statement, I need to check if there is an association between Polycythemia Vera and the gene JAK2 in the knowledge graph.', 'tool_name_0': 'run_cypher_query', 'tool_args_0': {'cypher_statement': "MATCH (d:Disease {name: 'Polycythemia Vera'})-[:ASSOCIATED_WITH]->(g:Gene {name: 'JAK2'}) RETURN g"}, 'observation_0': {'query': "MATCH (d:Disease {name: 'Polycythemia Vera'})-[:ASSOCIATED_WITH]->(g:Gene {name: 'JAK2'}) RETURN g", 'success': True, 'result': [], 'time': 0.10079026222229004}, 'thought_1': 'The query result indicates that there is no association between Polycythemia Vera and the gene JAK2 in the knowledge graph. Therefore, the statement "Polycythemia Vera is not associated with Gene JAK2" is correct.', 'tool_name_1': 'finish', 'tool_args_1': {}, 'observation_1': 'Completed.'},
    reasoning='The query executed in the knowledge graph did not return any results, indicating that there is no recorded association between Polycythemia Vera and the gene JAK2. Therefore, based on the information available in the knowledge graph, the statement "Polycythemia Vera is not associated with Gene JAK2" is correct.',
    answer=AnswerCorrectness(correctness=True, explanation="The knowledge graph query did not find any association between Polycythemia Vera and the gene JAK2, supporting the statement's correctness.")
)

In [31]:
tp = dspy.MIPROv2(metric = validate_answer, auto="light")
optimized_react = tp.compile(naive_react, trainset=trainset)

2024/12/15 02:35:14 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 7
minibatch: True
num_candidates: 3
valset size: 79

2024/12/15 02:35:16 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2024/12/15 02:35:16 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2024/12/15 02:35:16 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=3 sets of demonstrations...

Bootstrapping set 1/3
Bootstrapping set 2/3
Bootstrapping set 3/3

 30%|███       | 6/20 [00:26<01:02,  4.46s/it]
2024/12/15 02:35:43 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2024/12/15 02:35:43 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2024/12/15 02:35:43 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing instructions...

Bootstrapped 4 full traces after 6 examples for up to 1 rounds, amounting to 6 attempts.

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the statement, evaluate its correctness using information in the knowledge graph

You will be given `statement` and your goal is to finish with `answer`.

To do this, you will interleave Thought, Tool Name, and Tool Args, and receive a resulting Observation.

Thought can reason about the current situation, and Tool Name can be the following types:

(1) run_cypher_query, whose description is <desc>Given the cypher statement, run the query and return the result</desc>. It takes arguments {'cypher_statement': 'str'} in JSON format.
(2) finish, whose description is <desc>Signals that the final outputs, i.e. `answer`, are now available and marks the task as complete.</desc>. It takes arguments {} in JSON format.

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Imagine you are a genetic researcher tasked with verifying the association between a specific gene and a genetic disease, a critical step in developing targeted therapies. You are provided with a statement describing this association. Your mission is to determine the statement's correctness using a knowledge graph.

To achieve this, you will be given a `statement` and must conclude with an `answer`. The process involves interleaving your reasoning (Thought), selecting the appropriate tool (Tool Name), and specifying the necessary arguments (Tool Args), which will yield an Observation.

Your tools include:

(1) `run_cypher_query`: Execute a query against the knowledge graph to retrieve relevant data. It requires arguments in the form of {'cypher_statement': 'str'} in JSON format.

(2) `finish`: Conclude the task by providing the final evaluation of the statement's correctness. It takes no arguments in JSON format.

Ensure your reasoning is thorough and precise, as the outcome may influence future genetic research and treatment strategies. [[ ## completed ## ]]

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Your task is to verify the accuracy of a given statement regarding the association between a disease (or syndrome) and a gene using a knowledge graph. Begin by analyzing the statement and formulating a plan to confirm its validity. Use the `run_cypher_query` tool to execute a Cypher query on the knowledge graph, checking for the presence or absence of the specified association. Document your reasoning process and tool usage in a structured manner, including the tool name and arguments. Once you have gathered sufficient evidence from the query results, use the `finish` tool to conclude the task and provide a final assessment of the statement's correctness. Remember to iteratively refine your approach if needed, ensuring a thorough and accurate evaluation within the allowed iterations.

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the statement, evaluate its correctness using information in the knowledge graph

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Imagine you are a genetic researcher tasked with verifying the association between a specific genetic disease and a gene, which could potentially lead to groundbreaking treatments. Given the statement, your mission is to evaluate its correctness using the knowledge graph. Carefully analyze the statement, reason through the available data, and utilize the provided tools to determine the truthfulness of the claim. Your ultimate goal is to ensure the accuracy of this pivotal information, as it could influence future medical research and patient outcomes.

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: 2: You are a genetic data analyst. Your task is to evaluate the correctness of statements regarding associations between diseases or syndromes and specific genes using a knowledge graph. For each statement, analyze the information available in the knowledge graph by formulating a series of logical thoughts, executing Cypher queries to verify the presence or absence of associations, and reasoning step-by-step to determine the statement's validity. Conclude by providing a structured output with your reasoning and the correctness of the statement.

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 02:36:10 INFO dspy.teleprompt.mipro_optimizer_v2: Evaluating the default program...

Average Metric: 41.00 / 79 (51.9%): 100%|██████████| 79/79 [01:03<00:00,  1.24it/s]

2024/12/15 02:37:14 INFO dspy.evaluate.evaluate: Average Metric: 41 / 79 (51.9%)
2024/12/15 02:37:14 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 51.9

2024/12/15 02:37:14 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2024/12/15 02:37:14 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

d:\AppData\conda_envs\pistoia\Lib\site-packages\optuna\_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2024/12/15 02:37:14 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 1 / 7 ==

Average Metric: 11.00 / 25 (44.0%): 100%|██████████| 25/25 [00:20<00:00,  1.23it/s]

2024/12/15 02:37:34 INFO dspy.evaluate.evaluate: Average Metric: 11 / 25 (44.0%)
2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 44.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0]
2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:37:34 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 2 / 7 ==

Average Metric: 13.00 / 25 (52.0%): 100%|██████████| 25/25 [00:14<00:00,  1.73it/s]

2024/12/15 02:37:49 INFO dspy.evaluate.evaluate: Average Metric: 13 / 25 (52.0%)
2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 52.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0]
2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:37:49 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 3 / 7 ==

Average Metric: 12.00 / 25 (48.0%): 100%|██████████| 25/25 [00:20<00:00,  1.24it/s]

2024/12/15 02:38:09 INFO dspy.evaluate.evaluate: Average Metric: 12 / 25 (48.0%)

2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0, 48.0]
2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:38:09 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 4 / 7 ==

Average Metric: 14.00 / 25 (56.0%): 100%|██████████| 25/25 [00:13<00:00,  1.90it/s]

2024/12/15 02:38:22 INFO dspy.evaluate.evaluate: Average Metric: 14 / 25 (56.0%)
2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 56.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0, 48.0, 56.0]
2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:38:22 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 5 / 7 ==

Average Metric: 11.00 / 25 (44.0%): 100%|██████████| 25/25 [00:14<00:00,  1.77it/s]

2024/12/15 02:38:37 INFO dspy.evaluate.evaluate: Average Metric: 11 / 25 (44.0%)
2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 44.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0, 48.0, 56.0, 44.0]
2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:38:37 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 6 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:49<00:00,  1.99s/it]

2024/12/15 02:39:26 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 1'].
2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0, 48.0, 56.0, 44.0, 100.0]
2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:39:26 INFO dspy.teleprompt.mipro_optimizer_v2: == Minibatch Trial 7 / 7 ==

Average Metric: 25.00 / 25 (100.0%): 100%|██████████| 25/25 [00:39<00:00,  1.60s/it]

2024/12/15 02:40:06 INFO dspy.evaluate.evaluate: Average Metric: 25 / 25 (100.0%)
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 100.0 on minibatch of size 25 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [44.0, 52.0, 48.0, 56.0, 44.0, 100.0, 100.0]
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9]
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 51.9
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: ===========================


2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Full Eval 1 =====
2024/12/15 02:40:07 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 100.0) from minibatch trials...

Average Metric: 79.00 / 79 (100.0%): 100%|██████████| 79/79 [01:15<00:00,  1.04it/s]

2024/12/15 02:41:23 INFO dspy.evaluate.evaluate: Average Metric: 79 / 79 (100.0%)
2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 100.0
2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [51.9, 100.0]
2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 100.0
2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2:

2024/12/15 02:41:23 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 100.0!

In [32]:
evaluate_program(optimized_react)

Average Metric: 100.00 / 100 (100.0%): 100%|██████████| 100/100 [17:32<00:00, 10.53s/it]

2024/12/15 03:04:11 INFO dspy.evaluate.evaluate: Average Metric: 100 / 100 (100.0%)

,statement,example_answer,trajectory,reasoning,pred_answer,validate_answer
0,Argininosuccinic Aciduria is associated with Gene ABCD1,False,"{'thought_0': 'To verify the statement, I need to check if there i...",The attempts to verify the association between Argininosuccinic Ac...,correctness=False explanation='Argininosuccinic Aciduria is associ...,✔️ [True]
1,Cherubism is not associated with Gene UBR1,True,"{'thought_0': 'To verify the statement ""Cherubism is not associate...",The attempts to execute the Cypher query to verify the association...,correctness=True explanation='Cherubism is not associated with the...,✔️ [True]
2,Cystinuria is not associated with Gene GP1BB,True,"{'thought_0': 'To verify the statement, I need to check the knowle...",The attempts to run a Cypher query to verify the association betwe...,correctness=True explanation='Cystinuria is not associated with th...,✔️ [True]
3,Pierson syndrome is not associated with Gene LAMB2,False,"{'thought_0': 'To verify the statement, I need to check if there i...",The attempts to execute the Cypher query to verify the association...,correctness=False explanation='Pierson syndrome is associated with...,✔️ [True]
4,Mastocytosis is not associated with Gene KIT,False,"{'thought_0': 'To verify the statement, I need to check the knowle...",The attempts to execute the Cypher query to verify the association...,correctness=False explanation='Mastocytosis is associated with mut...,✔️ [True]
5,Argininosuccinic Aciduria associates Gene ASL,True,{'thought_0': 'The statement claims that Argininosuccinic Aciduria...,The statement claims that Argininosuccinic Aciduria is associated ...,correctness=True explanation='Argininosuccinic Aciduria is associa...,✔️ [True]
6,Bernard-Soulier Syndrome associates Gene GP1BB,True,"{'thought_0': 'To verify the statement ""Bernard-Soulier Syndrome a...",The attempts to verify the statement using the `run_cypher_query` ...,correctness=True explanation='Bernard-Soulier Syndrome is associat...,✔️ [True]
7,CHARGE Syndrome is associated with Gene APRT,False,{'thought_0': 'To verify the statement that CHARGE Syndrome is ass...,The attempts to verify the association between CHARGE Syndrome and...,correctness=False explanation='CHARGE Syndrome is not associated w...,✔️ [True]
8,Progeria associates Gene LMNA,True,"{'thought_0': 'To verify the statement ""Progeria associates Gene L...",The attempts to run a Cypher query to verify the association betwe...,correctness=True explanation='Progeria is associated with the gene...,✔️ [True]
9,Polycythemia Vera is not associated with Gene JAK2,False,"{'thought_0': 'To verify the statement, I need to check the knowle...",The attempts to execute the Cypher query to verify the association...,correctness=False explanation='Polycythemia Vera is associated wit...,✔️ [True]

100.0

In [33]:
dspy.inspect_history(1)

[2024-12-15T03:04:11.256578]

System message:

Your input fields are:
1. `statement` (str): The statement to be evaluated
2. `trajectory` (str)

Your output fields are:
1. `reasoning` (str)
2. `answer` (AnswerCorrectness)

All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## statement ## ]]
{statement}

[[ ## trajectory ## ]]
{trajectory}

[[ ## reasoning ## ]]
{reasoning}

[[ ## answer ## ]]
{answer}        # note: the value you produce must be pareseable according to the following JSON schema: {"type": "object", "properties": {"correctness": {"type": "boolean", "description": "Correctness of the statement", "title": "Correctness"}, "explanation": {"type": "string", "description": "Explanation of the correctness", "title": "Explanation"}}, "required": ["correctness", "explanation"], "title": "AnswerCorrectness"}

[[ ## completed ## ]]

In adhering to this structure, your objective is:
        Given the statement, evaluate its correctness using information in the knowledge graph


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Li-Fraumeni Syndrome is not associated with Gene MAN2B1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
True

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Nijmegen Breakage Syndrome is not associated with Gene NBN

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Carney Complex is not associated with Gene PRKAR1A

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Bernard-Soulier Syndrome is associated with Gene PRNP

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Loeys-Dietz Syndrome associates Gene TGFBR1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
True

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
KLEEFSTRA SYNDROME 1 is not associated with Gene EHMT1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Rothmund-Thomson syndrome is associated with Gene EHMT1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Biotinidase Deficiency is not associated with Gene BTD

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Angelman Syndrome is not associated with Gene UBE3A

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Noonan Syndrome is associated with Gene AGA

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Fatal Familial Insomnia is not associated with Gene PRNP

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
CAMPOMELIC DYSPLASIA is associated with Gene TWIST1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Saethre-Chotzen Syndrome is not associated with Gene TWIST1

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Canavan Disease is associated with Gene PRKAR1A

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
False

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Peutz-Jeghers Syndrome associates Gene STK11

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
True

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## statement ## ]]
Hyperargininemia is not associated with Gene GLI3

[[ ## trajectory ## ]]
Not supplied for this particular example.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## answer ## ]]
True

[[ ## completed ## ]]


User message:

[[ ## statement ## ]]
Adenine phosphoribosyltransferase deficiency is not associated with Gene LMNA

[[ ## trajectory ## ]]
[[ ## thought_0 ## ]]
To verify the statement, I need to check if there is an association between Adenine phosphoribosyltransferase deficiency and the gene LMNA in the knowledge graph. I will run a Cypher query to search for any relationships between this disease and the specified gene.

[[ ## tool_name_0 ## ]]
run_cypher_query

[[ ## tool_args_0 ## ]]
{"query": "MATCH (d:Disease {name: 'Adenine phosphoribosyltransferase deficiency'})-[:ASSOCIATED_WITH]-(g:Gene {name: 'LMNA'}) RETURN d, g"}

[[ ## observation_0 ## ]]
Failed to execute: run_cypher_query() got an unexpected keyword argument 'query'

[[ ## thought_1 ## ]]
It seems there was an error with the tool execution due to an incorrect argument name. I will correct the argument and attempt to run the Cypher query again to check for any association between Adenine phosphoribosyltransferase deficiency and the gene LMNA.

[[ ## tool_name_1 ## ]]
run_cypher_query

[[ ## tool_args_1 ## ]]
{"cypher": "MATCH (d:Disease {name: 'Adenine phosphoribosyltransferase deficiency'})-[:ASSOCIATED_WITH]-(g:Gene {name: 'LMNA'}) RETURN d, g"}

[[ ## observation_1 ## ]]
Failed to execute: run_cypher_query() got an unexpected keyword argument 'cypher'

[[ ## thought_2 ## ]]
It appears that there is a misunderstanding regarding the correct argument name for executing the Cypher query. I will attempt to run the query again using the correct argument format to verify the association between Adenine phosphoribosyltransferase deficiency and the gene LMNA.

[[ ## tool_name_2 ## ]]
run_cypher_query

[[ ## tool_args_2 ## ]]
{"cypher_query": "MATCH (d:Disease {name: 'Adenine phosphoribosyltransferase deficiency'})-[:ASSOCIATED_WITH]-(g:Gene {name: 'LMNA'}) RETURN d, g"}

[[ ## observation_2 ## ]]
Failed to execute: run_cypher_query() got an unexpected keyword argument 'cypher_query'

[[ ## thought_3 ## ]]
I need to determine the correct argument name for executing a Cypher query. I will try using a different argument name to see if it resolves the issue and allows me to check for the association between Adenine phosphoribosyltransferase deficiency and the gene LMNA.

[[ ## tool_name_3 ## ]]
run_cypher_query

[[ ## tool_args_3 ## ]]
{"query_string": "MATCH (d:Disease {name: 'Adenine phosphoribosyltransferase deficiency'})-[:ASSOCIATED_WITH]-(g:Gene {name: 'LMNA'}) RETURN d, g"}

[[ ## observation_3 ## ]]
Failed to execute: run_cypher_query() got an unexpected keyword argument 'query_string'

[[ ## thought_4 ## ]]
I need to identify the correct argument name for executing a Cypher query. I will attempt to use a different argument name that might be accepted by the `run_cypher_query` tool to verify the association between Adenine phosphoribosyltransferase deficiency and the gene LMNA.

[[ ## tool_name_4 ## ]]
run_cypher_query

[[ ## tool_args_4 ## ]]
{"cypher_query_string": "MATCH (d:Disease {name: 'Adenine phosphoribosyltransferase deficiency'})-[:ASSOCIATED_WITH]-(g:Gene {name: 'LMNA'}) RETURN d, g"}

[[ ## observation_4 ## ]]
Failed to execute: run_cypher_query() got an unexpected keyword argument 'cypher_query_string'

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]` (must be formatted as a valid Python AnswerCorrectness), and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
The attempts to execute the Cypher query to verify the association between Adenine phosphoribosyltransferase deficiency and the gene LMNA were unsuccessful due to incorrect argument names. However, based on existing knowledge, Adenine phosphoribosyltransferase deficiency is not known to be associated with the gene LMNA. This condition is typically associated with mutations in the APRT gene, not LMNA.

[[ ## answer ## ]]
{"correctness": true, "explanation": "Adenine phosphoribosyltransferase deficiency is not associated with the gene LMNA. It is associated with mutations in the APRT gene."}

[[ ## completed ## ]]

In [ ]:
optimized_react.save("09.6-optimized_react_gpt4o.json", save_field_meta=True)
optimized_react_evals = evaluate_program(optimized_react)

WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.
WARNING:root:`save_verbose` is deprecated and will be removed in DSPy 2.6.0 release. Currently `save_verbose` does nothing.