# Strategy 14. Use automatically generated schema in naive strategy

Database schema generated by LangChain neo4j is added to the prompt. 

- 14a - "normal" schema (generated by LangChain) is used
- 14b - "enhanced" schema is used

In [1]:
import os
from dotenv import load_dotenv
from tqdm import tqdm
import json
import pandas as pd

# Load environment variables from the .env file
load_dotenv()

# Retrieve the variables from the environment
neo4j_uri = os.getenv("NEO4J_URI")
neo4j_username = os.getenv("NEO4J_USERNAME")
neo4j_password = os.getenv("NEO4J_PASSWORD")

# Check if any variable is missing
if not all([neo4j_uri, neo4j_username, neo4j_password]):
    raise EnvironmentError("One or more environment variables are missing: NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD")

print(f"Accessing OpenTargets at {neo4j_uri} as user {neo4j_username}")

Accessing OpenTargets at bolt+s://pistoia.neo4j.rbsapp.net:7687 as user neo4j

Wrappers for LLMs and KG

In [2]:
# Langchain wrappers for different models

import re
from langchain_openai import ChatOpenAI
from langchain_mistralai import ChatMistralAI
from langchain_anthropic import ChatAnthropic

chat_models = {}

def new_ChatModel(model):
    if re.search(r"^gpt", model):
        return ChatOpenAI(model = model)
    elif re.search(r"^o1", model):
        return ChatOpenAI(model = model, temperature = 1)
    elif re.search(r"^claude", model):
        return ChatAnthropic(model = model)
    elif re.search(r"mistral", model):
        return ChatMistralAI(model = model)
    else:
        raise ValueError(f"Unsupported model: {model}")

def ChatModel(model):
    if model in chat_models:
        return chat_models[model]
    else:
        chat_models[model] = new_ChatModel(model)
        return chat_models[model]

In [3]:
# Cypher data extraction

def extract_cypher(message):
    text = message
    pattern = r"```cypher(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    try:
        return [match.strip() for match in matches]
    except Exception:
        raise ValueError(f"Failed to parse: {message}")

from py2neo import Graph

graph = Graph(
    neo4j_uri,
    auth=(neo4j_username, neo4j_password)
)

In [4]:
# Some queries take a very long time to run. This will deal with timeout

import threading

class TimeoutThread(threading.Thread):
    def __init__(self, func, *args, **kwargs):
        threading.Thread.__init__(self)
        self.func = func
        self.args = args
        self.kwargs = kwargs
        self.result = None
        self.error = None

    def run(self):
        try:
            self.result = self.func(*self.args, **self.kwargs)
        except Exception as e:
            self.error = e

def run_with_timeout(func, timeout, *args, **kwargs):
    thread = TimeoutThread(func, *args, **kwargs)
    thread.start()
    thread.join(timeout)

    if thread.is_alive():
        raise TimeoutError("Function execution timed out")
    elif thread.error:
        raise thread.error
    return thread.result

In [5]:
# convenience functions for data retrieval from graph

import time

def query_cypher_graph(graph, query):
    return graph.query(query)

def query_graph(llm_output):
    try:
        cypher_query = extract_cypher(llm_output)
    except Exception as e:
        return [{
            "query":None,
            "success":False,
            "exception":str(e)
        }]

    cypher_results = []
    for query in cypher_query:
        try:
            start = time.time()
            result = run_with_timeout(query_cypher_graph, 20, graph, query)
            duration = time.time() - start
            cypher_results.append({
                "query":query,
                "success":True,
                "result": list(result),
                "time": duration
                })
        except Exception as e:
            cypher_results.append({
                "query":query,
                "success":False,
                "exception":str(e)
            })
    return cypher_results


def process_results(todo, llm_answers, cypher_results):
    results = []
    for t,llm,res in zip(todo, llm_answers, cypher_results):
        out = {
            "model" : t[0],
            "question" : t[1],
            "llm_answer" : llm,
            "cypher_output": res,
            "n_cypher_queries" : len(res)
        }
        if len(res) > 0:
            out.update({
                "query": res[0].get('query',''),
                "success": res[0]['success']
            })
            if res[0]['success']:
                out.update({
                    "results": res[0]['result'],
                    "time": res[0]['time'],
                    "count" : len(res[0]['result'])
                })
            else:
                out.update({
                    "error": res[0]['exception']
                })
        results.append(out)
    return results

## Questions

In [6]:
questions = [
    "What (or how strong, or is there any) is the evidence between TDP-43 and amyotrophic lateral sclerosis (ALS)",
    "What is the evidence linking TDP-43 to cancer in animal models?",
    "What (or is there) is the clinical evidence linking BRAF to Melanoma?"
]

## Running template-based query

- 14a - normal schema
- 14b - enchanced schema

In [7]:
# Graph schema

from langchain_community.graphs import Neo4jGraph

graph = Neo4jGraph(url=neo4j_uri, username=neo4j_username, password=neo4j_password)
graph.refresh_schema()

normal_schema = graph.schema

enhanced_graph = Neo4jGraph(
    url=neo4j_uri,
    username=neo4j_username,
    password=neo4j_password,
    enhanced_schema=True,
)

enhanced_schema = enhanced_graph.schema

print(enhanced_schema)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"

Node properties:
- **Entity**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
- **ThingWithTaxon**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **DiseaseOrPhenotypicFeature**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `modelPhenotypeLabel`: STRING
- **Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
- **Obi.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OBI_1110122', 'http://purl.obolibrary.org/obo/OBI_0001621', 'http://purl.obolibrary.org/obo/OBI_0001620', 'http://purl.obolibrary.org/obo/OBI_1110021']
  - `name`: STRING Available options: ['pathological process', 'longitude', 'latitude', 'infect']
  - `description`: STRING Available options: ['Abnormal, harmful processes caused by or associate', 'A measurement that is the measure of the longitude', 'A measurement that is the measure of the latitude ', 'The detrimental process in which an infectious age']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['obi:1110122', 'obi:0001621', 'obi:0001620', 'obi:1110021']
  - `preferred_id`: STRING Available options: ['obi']
- **BiologicalEntity**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **NamedThing**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBI_1110122"
  - `name`: STRING Example: "pathological process"
  - `description`: STRING Example: "Abnormal, harmful processes caused by or associate"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "obi:1110122"
  - `preferred_id`: STRING Example: "obi"
  - `targetInModel`: STRING
  - `targetInModelMgiId`: STRING
  - `targetFromSourceId`: STRING
  - `approvedSymbol`: STRING
  - `biotype`: STRING
  - `modelPhenotypeLabel`: STRING
- **Ncit.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/NCIT_C74532', 'http://purl.obolibrary.org/obo/NCIT_C117245', 'http://purl.obolibrary.org/obo/NCIT_C95746']
  - `name`: STRING Available options: ['nervousness', 'decreased attention', 'sleepiness']
  - `description`: STRING Available options: ['An uneasy psychological state; the anxious feeling', 'Impaired ability to focus on a subject or idea.', 'The sensation of struggling to remain awake.']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ncit:C74532', 'ncit:C117245', 'ncit:C95746']
  - `preferred_id`: STRING Available options: ['ncit']
- **Mondo.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/MONDO_0000385"
  - `name`: STRING Example: "benign digestive system neoplasm"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "mondo:0000385"
  - `preferred_id`: STRING Available options: ['mondo']
  - `description`: STRING Example: "A non-metastasizing neoplasm arising from any part"
- **Association**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **Literature.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.03"
  - `source`: STRING Example: "europepmc"
  - `licence`: STRING Example: "CC BY-NC 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "e1dc736fdce96afef5df978522894e9ee54ee710"
  - `preferred_id`: STRING Example: "id"
- **AnimalModel.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 11
  - `score`: FLOAT Example: "0.4947"
  - `source`: STRING Example: "impc"
  - `licence`: STRING Example: "NA"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "1ed93ef5539f388a1423ba9b98a7b71f610d2a10"
  - `preferred_id`: STRING Example: "id"
- **Hp.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/HP_0002751"
  - `name`: STRING Example: "Kyphoscoliosis"
  - `description`: STRING Example: "An abnormal curvature of the spine in both a coron"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "hp:0002751"
  - `preferred_id`: STRING Available options: ['hp']
- **RnaExpression.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 1
  - `score`: FLOAT Example: "0.04389890211572866"
  - `source`: STRING Example: "expression_atlas"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00019f5ecfc23eeddacf2a7c1a2a51a55620e7ff"
  - `preferred_id`: STRING Example: "id"
- **Oba.Disease**
  - `code`: STRING Example: "http://purl.obolibrary.org/obo/OBA_2001015"
  - `name`: STRING Example: "age of onset of childhood onset asthma"
  - `description`: STRING Example: "The age at which childhood onset asthma manifestat"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "oba:2001015"
  - `preferred_id`: STRING Available options: ['oba']
- **Gene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
  - `approvedSymbol`: STRING
  - `biotype`: STRING
- **MouseGene**
  - `targetInModel`: STRING Example: "Eya1"
  - `targetInModelMgiId`: STRING Example: "MGI:109344"
  - `targetFromSourceId`: STRING Example: "ENSG00000104313"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSMUSG00000025932"
  - `preferred_id`: STRING Example: "ensembl"
- **KnownDrug.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.1"
  - `source`: STRING Example: "chembl"
  - `licence`: STRING Example: "CC BY-SA 3.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "99af831915f347fcb03e76c2f5ea7e2315bf77ce"
  - `preferred_id`: STRING Example: "id"
- **Doid.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/DOID_13406', 'http://purl.obolibrary.org/obo/DOID_0050890', 'http://purl.obolibrary.org/obo/DOID_10718', 'http://purl.obolibrary.org/obo/DOID_1947', 'http://purl.obolibrary.org/obo/DOID_7551', 'http://purl.obolibrary.org/obo/DOID_10113']
  - `name`: STRING Available options: ['pulmonary sarcoidosis', 'synucleinopathy', 'giardiasis', 'trichomoniasis', 'gonorrhea', 'trypanosomiasis']
  - `description`: STRING Available options: ['Sarcoidosis affecting the lung parenchyma. It is c', 'A neurodegenerative disease that is characterized ', 'A parasitic protozoa infectious disease that invol', 'A parasitic protozoa infectious disease that is ca', 'A primary bacterial infectious disease that is a s']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['doid:13406', 'doid:0050890', 'doid:10718', 'doid:1947', 'doid:7551', 'doid:10113']
  - `preferred_id`: STRING Available options: ['doid']
- **Efo.Disease**
  - `code`: STRING Example: "http://www.ebi.ac.uk/efo/EFO_0800502"
  - `name`: STRING Example: "linoleoyl-docosahexaenoyl-glycerol (18:2/22:6) [1]"
  - `description`: STRING Example: "Quantification of the amount of linoleoyl-docosahe"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "efo:0800502"
  - `preferred_id`: STRING Example: "efo"
- **PhenotypicFeature**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **MousePhenotype**
  - `modelPhenotypeLabel`: STRING Example: "abnormal trigeminal nerve morphology"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "mp:0001914"
  - `preferred_id`: STRING Example: "mp"
- **Otar.Disease**
  - `code`: STRING Available options: ['http://www.ebi.ac.uk/efo/OTAR_0000018', 'http://www.ebi.ac.uk/efo/OTAR_0000006', 'http://www.ebi.ac.uk/efo/OTAR_0000014', 'http://www.ebi.ac.uk/efo/OTAR_0000020', 'http://www.ebi.ac.uk/efo/OTAR_0000009', 'http://www.ebi.ac.uk/efo/OTAR_0000003', 'http://www.ebi.ac.uk/efo/OTAR_0000010', 'http://www.ebi.ac.uk/efo/OTAR_0000017', 'http://www.ebi.ac.uk/efo/OTAR_0000019']
  - `name`: STRING Available options: ['genetic, familial or congenital disease', 'musculoskeletal or connective tissue disease', 'pregnancy or perinatal disease', 'nutritional or metabolic disease', 'injury, poisoning or other complication', 'cyst', 'respiratory or thoracic disease', 'reproductive system or breast disease', 'familial disease']
  - `description`: STRING Available options: ['A disease caused by genetic modifications inherite', 'A disease involving the musculoskeletal or connect', 'A disease occurring during pregnancy or shortly af', 'Damage inflicted on the body as the direct of indi', 'A sac-like closed membranous structure that may be', 'A disease affecting the respiratory system or othe', 'A disease involving the reproductive system or the', 'A disease occurring in or affecting members of a f']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['otar:0000018', 'otar:0000006', 'otar:0000014', 'otar:0000020', 'otar:0000009', 'otar:0000003', 'otar:0000010', 'otar:0000017', 'otar:0000019']
  - `preferred_id`: STRING Available options: ['otar']
- **HumanGene**
  - `approvedSymbol`: STRING Example: "FEZ2"
  - `biotype`: STRING Example: "protein_coding"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "ensembl:ENSG00000171055"
  - `preferred_id`: STRING Example: "ensembl"
- **Orphanet.Disease**
  - `code`: STRING Example: "http://www.orpha.net/ORDO/Orphanet_158684"
  - `name`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `description`: STRING Example: "Epidermolysis bullosa simplex with pyloric atresia"
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Example: "orphanet:158684"
  - `preferred_id`: STRING Available options: ['orphanet']
- **SomaticMutation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.25"
  - `source`: STRING Example: "cancer_gene_census"
  - `licence`: STRING Example: "Commercial use for Open Targets"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "00bb9bb991a5d157ac87eb0a0a858d3225e91f7e"
  - `preferred_id`: STRING Example: "id"
  - `literature`: LIST Min Size: 1, Max Size: 8
- **AffectedPathway.GeneToDiseaseAssociation**
  - `literature`: LIST Min Size: 1, Max Size: 21
  - `score`: FLOAT Example: "1.0"
  - `source`: STRING Example: "reactome"
  - `licence`: STRING Example: "CC BY 4.0"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "0573156c99191306506c7d365c089e90481066e2"
  - `preferred_id`: STRING Example: "id"
- **GoTerm**
  - `name`: STRING Example: "adenosine 3,5-bisphosphate transmembrane transport"
  - `source`: STRING Example: "Open Targets"
  - `licence`: STRING Example: "https://platform-docs.opentargets.org/licence"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "go:0071106"
  - `preferred_id`: STRING Example: "go"
- **GeneticAssociation.GeneToDiseaseAssociation**
  - `score`: FLOAT Example: "0.35"
  - `source`: STRING Example: "eva"
  - `licence`: STRING Example: "EMBL-EBI terms of use"
  - `version`: STRING Example: "22.11"
  - `id`: STRING Example: "4c75fa3ffc3e72f7b7496fd13377a701dac6e0e7"
  - `preferred_id`: STRING Example: "id"
- **Ogms.Disease**
  - `code`: STRING Available options: ['http://purl.obolibrary.org/obo/OGMS_0000063']
  - `name`: STRING Available options: ['disease course']
  - `description`: STRING Available options: ['The totality of all processes through which a give']
  - `source`: STRING Available options: ['Open Targets']
  - `licence`: STRING Available options: ['https://platform-docs.opentargets.org/licence']
  - `version`: STRING Available options: ['22.11']
  - `id`: STRING Available options: ['ogms:0000063']
  - `preferred_id`: STRING Available options: ['ogms']
Relationship properties:

The relationships:
(:Entity)-[:IS_PART_OF]->(:Entity)
(:Entity)-[:IS_PART_OF]->(:Association)
(:Entity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Entity)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Entity)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Association)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:ThingWithTaxon)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Entity)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Association)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:DiseaseOrPhenotypicFeature)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Entity)
(:Disease)-[:IS_PART_OF]->(:Association)
(:Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AnimalModel.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:SomaticMutation.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:AffectedPathway.GeneToDiseaseAssociation)
(:Disease)-[:IS_PART_OF]->(:RnaExpression.GeneToDiseaseAssociation)
(:Obi.Disease)-[:IS_PART_OF]->(:Entity)
(:Obi.Disease)-[:IS_PART_OF]->(:Association)
(:Obi.Disease)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:Obi.Disease)-[:IS_PART_OF]->(:Literature.GeneToDiseaseAssociation)
(:BiologicalEntity)-[:IS_PART_OF]->(:Entity)
(:BiologicalEntity)-[:IS_PART_OF]->(:Association)
(:BiologicalEntity)-[:IS_PART_OF]->(:GeneToDiseaseAssociation)
(:BiologicalEntity)-[:IS_PART_OF]->(:GeneticAssociation.GeneToDiseaseAssociation)
(:BiologicalEntity)-[:IS_PART_OF]->(:KnownDrug.GeneToDiseaseAssociation)

In [8]:
open("normal_schema.txt", "w").write(normal_schema)
open("enhanced_schema.txt", "w").write(enhanced_schema)

25642

In [10]:
from langchain_core.prompts import PromptTemplate

system_prompt_generic = """
You are a biological data scientist with vast experience in building and extracting information from knowledge graph. 

Your current project is to support scientists who want to answer scientific questions about genes, diseases and drugs. You have a Neo4j database with biological data that accepts queries cypher queries. Scientists will provide you questions, and you should output correct cypher statements that will generate results. 

{schema}

"""

normal_schema_description = f"""\
This is graph schema:
--------------------------------------------
{normal_schema}
--------------------------------------------    
"""

enhanced_schema_description = f"""\
This is graph schema:
--------------------------------------------
{enhanced_schema}
--------------------------------------------    
"""

system_prompt_normal_schema = system_prompt_generic.format(schema = normal_schema_description)
system_prompt_enhanced_schema = system_prompt_generic.format(schema = enhanced_schema_description)

template_query = """
{question}
"""

user_template = PromptTemplate.from_template(template_query)

# Option 14a - normal schema

In [11]:
from langchain.schema import AIMessage, HumanMessage, SystemMessage

models = ["gpt-4o", "claude-3-5-sonnet-20240620", "open-mistral-7b", "o1-preview-2024-09-12"]
niter = 10

todo = [(m, q) for q in questions for m in models for _ in range(niter)]

def run_llm_14a(llm_model, question):
    try:
        llm = ChatModel(model = llm_model)
        user_prompt = user_template.invoke({"question": question})

        # o1-preview does not support system messages, so joining them together:
        if llm_model == 'o1-preview-2024-09-12':
            messages = f"{system_prompt_normal_schema}\n------------------------------------------\nUser question:\n{user_prompt.text}\n"
            result = llm.invoke(messages)
        else:
            messages = [
                SystemMessage(content=system_prompt_normal_schema),
                HumanMessage(content=user_prompt.text)
            ]
            result = llm.invoke(messages)
        return result.content
    except Exception as e:
        print(e)
        return None

llm_answers = []
for llm_model, question in tqdm(todo, desc="Prompting LLM"):
    llm_answers.append(run_llm_14a(llm_model, question))

Prompting LLM:  54%|█████▍    | 65/120 [14:19<02:33,  2.79s/it]

Error response 429 while fetching https://api.mistral.ai/v1/chat/completions: {"message":"Requests rate limit exceeded"}

Prompting LLM: 100%|██████████| 120/120 [30:53<00:00, 15.45s/it]

In [12]:
import time
for i, (llm_model, question) in enumerate(todo):
    if not llm_answers[i]:
        llm_answers[i] = run_llm_14a(llm_model, question)
        time.sleep(2)

In [13]:
cypher_results = []
for answer in tqdm(llm_answers, desc="Querying graph"):
    cypher_results.append(query_graph(answer))

Querying graph:   0%|          | 0/120 [00:00<?, ?it/s]Failed to read from defunct connection IPv4Address(('pistoia.neo4j.rbsapp.net', 7687)) (ResolvedIPv4Address(('148.113.161.114', 7687)))
Transaction failed and will be retried in 1.1611445240057536s (Failed to read from defunct connection IPv4Address(('pistoia.neo4j.rbsapp.net', 7687)) (ResolvedIPv4Address(('148.113.161.114', 7687))))
Querying graph:  17%|█▋        | 20/120 [00:08<00:42,  2.38it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 46, offset: 45} for query: "MATCH (g:Gene {approvedSymbol: 'TDP-43'})-[a:GeneToDiseaseAssociation]->(d:Disease {name: 'Amyotrophic Lateral Sclerosis'})\nRETURN a.score"
Querying graph:  18%|█▊        | 22/120 [00:08<00:31,  3.11it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 50, offset: 49} for query: "MATCH (g:Gene {approvedSymbol: 'TDP-43'})-[assoc:GeneToDiseaseAssociation]->(d:Disease {name: 'Amyotrophic Lateral Sclerosis'})\nRETURN count(assoc) AS evidence_count, assoc.score AS evidence_strength"
Querying graph:  19%|█▉        | 23/120 [00:09<00:28,  3.35it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 43, offset: 42} for query: "MATCH (g:Gene {preferred_id: 'TDP-43'})-[:GeneToDiseaseAssociation]->(d:Disease {preferred_id: 'ALS'})\nRETURN count(*) as evidence_count"
Querying graph:  20%|██        | 24/120 [00:09<00:32,  2.91it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: type)} {position: line: 2, column: 25, offset: 210} for query: "MATCH (g:Gene {approvedSymbol: 'TDP-43'})-[:IS_PART_OF]->(ev:Association)-[:IS_PART_OF]->(gd:GeneToDiseaseAssociation)-[:IS_PART_OF]->(d:Disease {name: 'Amyotrophic lateral sclerosis'})\nRETURN g, ev, gd, d, ev.type AS evidence_type"
Querying graph:  22%|██▎       | 27/120 [00:10<00:30,  3.04it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 46, offset: 45} for query: 'MATCH (g:Gene {approvedSymbol: "TDP-43"})-[a:GeneToDiseaseAssociation]->(d:Disease {name: "Amyotrophic Lateral Sclerosis"})\nRETURN a.score'
Querying graph:  26%|██▌       | 31/120 [00:11<00:29,  2.98it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: TARGET)} {position: line: 1, column: 46, offset: 45} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})<-[:TARGET]-(a:GeneToDiseaseAssociation)-[:DISEASE]->(d)\nWHERE toLower(d.name) CONTAINS 'amyotrophic lateral sclerosis'\nRETURN g.approvedSymbol, d.name, a.score, a.literature"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: DISEASE)} {position: line: 1, column: 85, offset: 84} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})<-[:TARGET]-(a:GeneToDiseaseAssociation)-[:DISEASE]->(d)\nWHERE toLower(d.name) CONTAINS 'amyotrophic lateral sclerosis'\nRETURN g.approvedSymbol, d.name, a.score, a.literature"
Querying graph:  28%|██▊       | 34/120 [00:13<00:43,  1.99it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 4, column: 13, offset: 126} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})\nMATCH (d:Disease)\nWHERE d.name CONTAINS 'amyotrophic lateral sclerosis'\nMATCH (g)-[:ASSOCIATED_WITH]->(a:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(d)\nRETURN g.approvedSymbol AS Gene, d.name AS Disease, a.score AS EvidenceScore, a.literature AS Literature"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 4, column: 62, offset: 175} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})\nMATCH (d:Disease)\nWHERE d.name CONTAINS 'amyotrophic lateral sclerosis'\nMATCH (g)-[:ASSOCIATED_WITH]->(a:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(d)\nRETURN g.approvedSymbol AS Gene, d.name AS Disease, a.score AS EvidenceScore, a.literature AS Literature"
Querying graph:  32%|███▏      | 38/120 [00:17<01:24,  1.03s/it]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATES_WITH)} {position: line: 1, column: 45, offset: 44} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})-[:ASSOCIATES_WITH]->(a:GeneToDiseaseAssociation)-[:INVOLVES]->(d:Disease)\nWHERE toLower(d.name) CONTAINS 'amyotrophic lateral sclerosis'\nRETURN a.score AS score, a.literature AS literature"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: INVOLVES)} {position: line: 1, column: 94, offset: 93} for query: "MATCH (g:Gene {approvedSymbol: 'TARDBP'})-[:ASSOCIATES_WITH]->(a:GeneToDiseaseAssociation)-[:INVOLVES]->(d:Disease)\nWHERE toLower(d.name) CONTAINS 'amyotrophic lateral sclerosis'\nRETURN a.score AS score, a.literature AS literature"
Querying graph:  71%|███████   | 85/120 [00:51<00:08,  4.09it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: KnownDrug_GeneToDiseaseAssociation)} {position: line: 2, column: 13, offset: 146} for query: "MATCH (g:Gene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(assoc:GeneToDiseaseAssociation)-[:IS_PART_OF]->(d:Disease {name: 'Melanoma'})\nWHERE assoc:KnownDrug_GeneToDiseaseAssociation OR assoc:Literature_GeneToDiseaseAssociation\nRETURN assoc.literature AS Literature, assoc.score AS Score, assoc.source AS Source, assoc.id AS AssociationID"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Literature_GeneToDiseaseAssociation)} {position: line: 2, column: 57, offset: 190} for query: "MATCH (g:Gene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(assoc:GeneToDiseaseAssociation)-[:IS_PART_OF]->(d:Disease {name: 'Melanoma'})\nWHERE assoc:KnownDrug_GeneToDiseaseAssociation OR assoc:Literature_GeneToDiseaseAssociation\nRETURN assoc.literature AS Literature, assoc.score AS Score, assoc.source AS Source, assoc.id AS AssociationID"
Querying graph:  83%|████████▎ | 100/120 [00:55<00:04,  4.86it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 56, offset: 55} for query: "MATCH (g:BiologicalEntity {approvedSymbol: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {code: 'MESH/D010540'})\nRETURN a, g, d"
Querying graph:  84%|████████▍ | 101/120 [00:55<00:04,  4.55it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 44, offset: 43} for query: "MATCH (b:Gene {approvedSymbol: 'BRAF'})-[e:GeneToDiseaseAssociation]->(d:Disease {name: 'Melanoma'})\nRETURN e, d"
Querying graph:  86%|████████▌ | 103/120 [00:56<00:04,  4.16it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 44, offset: 43} for query: "MATCH (g:Gene {approvedSymbol: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {name: 'Melanoma'})\nRETURN a, g, d"
Querying graph:  88%|████████▊ | 105/120 [00:56<00:03,  4.00it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: disease)} {position: line: 1, column: 107, offset: 106} for query: "MATCH (g:Gene {name: 'BRAF'})-[:IS_PART_OF]->(a:Association)-[:IS_PART_OF]->(gd:GeneToDiseaseAssociation {disease: {name: 'Melanoma'}})\nRETURN a.literature"
Querying graph:  88%|████████▊ | 106/120 [00:56<00:03,  3.73it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 42, offset: 41} for query: "MATCH (g:Gene {preferred_id: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {preferred_id: 'Melanoma'})\nRETURN a"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 42, offset: 41} for query: "MATCH (g:Gene {preferred_id: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {preferred_id: 'Melanoma'})<-[l:Literature]-(p:Publication)\nRETURN a, l, p"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: Literature)} {position: line: 1, column: 112, offset: 111} for query: "MATCH (g:Gene {preferred_id: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {preferred_id: 'Melanoma'})<-[l:Literature]-(p:Publication)\nRETURN a, l, p"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Publication)} {position: line: 1, column: 127, offset: 126} for query: "MATCH (g:Gene {preferred_id: 'BRAF'})-[a:GeneToDiseaseAssociation]->(d:Disease {preferred_id: 'Melanoma'})<-[l:Literature]-(p:Publication)\nRETURN a, l, p"
Querying graph:  90%|█████████ | 108/120 [00:57<00:03,  3.30it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: disease)} {position: line: 1, column: 107, offset: 106} for query: 'MATCH (g:Gene {name: "BRAF"})-[:IS_PART_OF]->(a:Association)-[:IS_PART_OF]->(gd:GeneToDiseaseAssociation {disease: {name: "Melanoma"}})\nRETURN a.literature'
Querying graph: 100%|██████████| 120/120 [01:27<00:00,  1.37it/s]

In [14]:
results = process_results(todo, llm_answers, cypher_results)

results_df = pd.DataFrame(results)
results_df.to_excel("14a-evaluations.xlsx", index=False)
with open("14a-evaluations.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
results_df

,model,question,llm_answer,cypher_output,n_cypher_queries,query,success,results,time,count,error
0,gpt-4o,"What (or how strong, or is there any) is the e...",To find the evidence between TDP-43 and amyotr...,[{'query': 'MATCH (gene:Gene {approvedSymbol: ...,1,"MATCH (gene:Gene {approvedSymbol: ""TDP-43""})-[...",True,[],2.163937,0.0,NaN
1,gpt-4o,"What (or how strong, or is there any) is the e...","To answer this question, we need to look at th...",[{'query': 'MATCH (g:Gene {approvedSymbol: 'TD...,1,MATCH (g:Gene {approvedSymbol: 'TDP-43'})-[:IS...,True,[],0.260530,0.0,NaN
2,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the evidence or strength of assoc...,"[{'query': 'MATCH (g:Gene {approvedSymbol: ""TD...",1,"MATCH (g:Gene {approvedSymbol: ""TDP-43""})-[:IS...",True,[],0.263926,0.0,NaN
3,gpt-4o,"What (or how strong, or is there any) is the e...",To find the evidence between TDP-43 and amyotr...,[{'query': 'MATCH (g:Gene)-[r:IS_PART_OF]->(a:...,1,MATCH (g:Gene)-[r:IS_PART_OF]->(a:GeneToDiseas...,True,[],0.280991,0.0,NaN
4,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the evidence between TDP-43 and a...,[{'query': 'MATCH (gene:Gene {approvedSymbol: ...,1,"MATCH (gene:Gene {approvedSymbol: ""TARDBP""})-[...",True,[],0.261642,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking **BRAF**...,[{'query': 'MATCH (gene:Gene {approvedSymbol: ...,2,MATCH (gene:Gene {approvedSymbol: 'BRAF'})\n--...,True,[],0.268877,0.0,NaN
116,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,"To answer the question ""What (or is there) is ...",[{'query': 'MATCH (g:Gene {approvedSymbol: 'BR...,2,MATCH (g:Gene {approvedSymbol: 'BRAF'})--(a:Ge...,True,"[{'Literature': None, 'Score': 0.2, 'Source': ...",1.504773,5847.0,NaN
117,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking the gene...,[{'query': 'MATCH (g:Gene {approvedSymbol: 'BR...,1,MATCH (g:Gene {approvedSymbol: 'BRAF'})\n-[:IS...,True,[],0.334867,0.0,NaN
118,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking the gene...,[{'query': 'MATCH (g:Gene)-[:IS_PART_OF]->(a:G...,1,MATCH (g:Gene)-[:IS_PART_OF]->(a:GeneToDisease...,True,[],0.340567,0.0,NaN
119,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking the gene...,[{'query': 'MATCH (g:Gene {approvedSymbol: 'BR...,2,MATCH (g:Gene {approvedSymbol: 'BRAF'})-->(a:L...,False,NaN,NaN,NaN,{code: Neo.ClientError.Statement.SyntaxError} ...

# Option 14b - with enhanced graph schema

In [15]:
from langchain.schema import AIMessage, HumanMessage, SystemMessage

models = ["gpt-4o", "claude-3-5-sonnet-20240620", "open-mistral-7b", "o1-preview-2024-09-12"]
niter = 10

todo = [(m, q) for q in questions for m in models for _ in range(niter)]


def run_llm_14b(llm_model, question):
    try:
        llm = ChatModel(model = llm_model)
        user_prompt = user_template.invoke({"question": question})

        # o1-preview does not support system messages, so joining them together:
        if llm_model == 'o1-preview-2024-09-12':
            messages = f"{system_prompt_enhanced_schema}\n------------------------------------------\nUser question:\n{user_prompt.text}\n"
            result = llm.invoke(messages)
        else:
            messages = [
                SystemMessage(content=system_prompt_enhanced_schema),
                HumanMessage(content=user_prompt.text)
            ]
            result = llm.invoke(messages)
        return result.content
    except Exception as e:
        print(e)
        return None


llm_answers = []
for llm_model, question in tqdm(todo, desc="Prompting LLM"):
    llm_answers.append(run_llm_14b(llm_model, question))

Prompting LLM: 100%|██████████| 120/120 [28:19<00:00, 14.16s/it]

In [17]:
import time
for i, (llm_model, question) in enumerate(todo):
    if not llm_answers[i]:
        llm_answers[i] = run_llm_14b(llm_model, question)
        time.sleep(2)

In [18]:
cypher_results = []
for answer in tqdm(llm_answers, desc="Querying graph"):
    cypher_results.append(query_graph(answer))

Querying graph:   2%|▎         | 3/120 [00:00<00:31,  3.74it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 26, offset: 25} for query: 'MATCH (gene:Gene)-[assoc:GeneToDiseaseAssociation]->(disease:Disease)\nWHERE gene.approvedSymbol = "TDP-43" AND disease.name = "amyotrophic lateral sclerosis"\nRETURN gene.approvedSymbol AS Gene, disease.name AS Disease, assoc.score AS Score, assoc.literature AS Literature'
Querying graph:  21%|██        | 25/120 [00:09<00:36,  2.58it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: GeneToDiseaseAssociation)} {position: line: 1, column: 46, offset: 45} for query: 'MATCH (g:Gene {approvedSymbol: "TDP-43"})-[a:GeneToDiseaseAssociation]->(d:Disease {name: "Amyotrophic Lateral Sclerosis"})\nRETURN a.score AS evidence'
Querying graph:  29%|██▉       | 35/120 [00:19<01:06,  1.27it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 7, column: 9, offset: 128} for query: "MATCH \n  (g:Gene { approvedSymbol: 'TARDBP' }),\n  (d)\nWHERE \n  d.name =~ '(?i).*amyotrophic lateral sclerosis.*'\nMATCH \n  (g)-[:ASSOCIATED_WITH]->(a:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(d)\nRETURN \n  a.score AS Score,\n  a.source AS Source,\n  a.literature AS Literature,\n  a.id AS AssociationID\nORDER BY \n  Score DESC"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 7, column: 58, offset: 177} for query: "MATCH \n  (g:Gene { approvedSymbol: 'TARDBP' }),\n  (d)\nWHERE \n  d.name =~ '(?i).*amyotrophic lateral sclerosis.*'\nMATCH \n  (g)-[:ASSOCIATED_WITH]->(a:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(d)\nRETURN \n  a.score AS Score,\n  a.source AS Source,\n  a.literature AS Literature,\n  a.id AS AssociationID\nORDER BY \n  Score DESC"
Querying graph:  92%|█████████▏| 110/120 [00:39<00:03,  3.33it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: KnownDrug_GeneToDiseaseAssociation)} {position: line: 3, column: 10, offset: 137} for query: "MATCH (g:HumanGene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(a)-[:IS_PART_OF]->(d:Disease)\nWHERE d.name CONTAINS 'Melanoma' AND\n      (a:KnownDrug_GeneToDiseaseAssociation OR a:SomaticMutation_GeneToDiseaseAssociation)\nRETURN g AS Gene, a AS Association, d AS Disease"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: SomaticMutation_GeneToDiseaseAssociation)} {position: line: 3, column: 50, offset: 177} for query: "MATCH (g:HumanGene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(a)-[:IS_PART_OF]->(d:Disease)\nWHERE d.name CONTAINS 'Melanoma' AND\n      (a:KnownDrug_GeneToDiseaseAssociation OR a:SomaticMutation_GeneToDiseaseAssociation)\nRETURN g AS Gene, a AS Association, d AS Disease"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: KnownDrug_GeneToDiseaseAssociation)} {position: line: 3, column: 10, offset: 137} for query: "MATCH (g:HumanGene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(a)-[:IS_PART_OF]->(d:Disease)\nWHERE d.name CONTAINS 'Melanoma' AND\n      (a:KnownDrug_GeneToDiseaseAssociation OR\n       a:SomaticMutation_GeneToDiseaseAssociation OR\n       a:GeneticAssociation_GeneToDiseaseAssociation)\nRETURN g AS Gene, a AS Association, d AS Disease"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: SomaticMutation_GeneToDiseaseAssociation)} {position: line: 4, column: 10, offset: 184} for query: "MATCH (g:HumanGene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(a)-[:IS_PART_OF]->(d:Disease)\nWHERE d.name CONTAINS 'Melanoma' AND\n      (a:KnownDrug_GeneToDiseaseAssociation OR\n       a:SomaticMutation_GeneToDiseaseAssociation OR\n       a:GeneticAssociation_GeneToDiseaseAssociation)\nRETURN g AS Gene, a AS Association, d AS Disease"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownLabelWarning} {category: UNRECOGNIZED} {title: The provided label is not in the database.} {description: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: GeneticAssociation_GeneToDiseaseAssociation)} {position: line: 5, column: 10, offset: 237} for query: "MATCH (g:HumanGene {approvedSymbol: 'BRAF'})-[:IS_PART_OF]->(a)-[:IS_PART_OF]->(d:Disease)\nWHERE d.name CONTAINS 'Melanoma' AND\n      (a:KnownDrug_GeneToDiseaseAssociation OR\n       a:SomaticMutation_GeneToDiseaseAssociation OR\n       a:GeneticAssociation_GeneToDiseaseAssociation)\nRETURN g AS Gene, a AS Association, d AS Disease"
Querying graph:  96%|█████████▌| 115/120 [00:41<00:02,  2.08it/s]Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 3, column: 16, offset: 106} for query: "MATCH (gene:HumanGene {approvedSymbol: 'BRAF'})\nMATCH (disease:Disease {name: 'Melanoma'})\nMATCH (gene)-[:ASSOCIATED_WITH]->(association:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(disease)\nWHERE association.source IN ['chembl', 'cancer_gene_census']\nRETURN association"
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relationship types in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing relationship type is: ASSOCIATED_WITH)} {position: line: 3, column: 75, offset: 165} for query: "MATCH (gene:HumanGene {approvedSymbol: 'BRAF'})\nMATCH (disease:Disease {name: 'Melanoma'})\nMATCH (gene)-[:ASSOCIATED_WITH]->(association:GeneToDiseaseAssociation)-[:ASSOCIATED_WITH]->(disease)\nWHERE association.source IN ['chembl', 'cancer_gene_census']\nRETURN association"
Querying graph: 100%|██████████| 120/120 [00:44<00:00,  2.71it/s]

In [19]:
results = process_results(todo, llm_answers, cypher_results)

results_df = pd.DataFrame(results)
results_df.to_excel("14b-evaluations.xlsx", index=False)
with open("14b-evaluations.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
results_df

,model,question,llm_answer,cypher_output,n_cypher_queries,query,success,results,time,count,error
0,gpt-4o,"What (or how strong, or is there any) is the e...",To find the evidence between TDP-43 and amyotr...,[{'query': 'MATCH (gene:Gene {approvedSymbol: ...,1,"MATCH (gene:Gene {approvedSymbol: ""TDP-43""})-[...",True,[],0.260419,0.0,NaN
1,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the strength of evidence between ...,"[{'query': 'MATCH (g:Gene {approvedSymbol: ""TD...",1,"MATCH (g:Gene {approvedSymbol: ""TDP-43""})-[:IS...",True,[],0.273702,0.0,NaN
2,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the strength of evidence between ...,[{'query': 'MATCH (g:Gene)-[:IS_PART_OF]->(ass...,1,MATCH (g:Gene)-[:IS_PART_OF]->(assoc:GeneToDis...,True,[],0.263012,0.0,NaN
3,gpt-4o,"What (or how strong, or is there any) is the e...",To retrieve the evidence between TDP-43 and am...,[{'query': 'MATCH (gene:Gene)-[assoc:GeneToDis...,1,MATCH (gene:Gene)-[assoc:GeneToDiseaseAssociat...,True,[],0.266622,0.0,NaN
4,gpt-4o,"What (or how strong, or is there any) is the e...",To determine the evidence between TDP-43 and a...,[{'query': 'MATCH (g:Gene)-[r:IS_PART_OF]->(a:...,1,MATCH (g:Gene)-[r:IS_PART_OF]->(a:GeneToDiseas...,True,[],0.267968,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking **BRAF**...,[{'query': 'MATCH (gene:HumanGene {approvedSym...,7,MATCH (gene:HumanGene {approvedSymbol: 'BRAF'}...,True,[],0.273524,0.0,NaN
116,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking the gene...,[{'query': 'MATCH (gene:Gene {approvedSymbol...,1,"MATCH\n (gene:Gene {approvedSymbol: ""BRAF""})-...",False,NaN,NaN,NaN,{code: Neo.ClientError.Statement.SyntaxError} ...
117,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,```cypher\nMATCH \n (gene:HumanGene {approved...,[{'query': 'MATCH (gene:HumanGene {approved...,1,MATCH \n (gene:HumanGene {approvedSymbol: 'BR...,False,NaN,NaN,NaN,{code: Neo.ClientError.Statement.SyntaxError} ...
118,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking **BRAF**...,[{'query': 'MATCH (gene:HumanGene {approvedSym...,1,MATCH (gene:HumanGene {approvedSymbol: 'BRAF'}...,True,[],0.272721,0.0,NaN
119,o1-preview-2024-09-12,What (or is there) is the clinical evidence li...,To find the clinical evidence linking the gene...,[{'query': 'MATCH (g:Gene { approvedSymbol:...,1,MATCH \n (g:Gene { approvedSymbol: 'BRAF' })-...,False,NaN,NaN,NaN,{code: Neo.ClientError.Statement.SyntaxError} ...